### ISSUE TITLE
Autoreconf error: required file 'example/libssh2_config.h.in' not found

### ISSUE THREAD

**Issue by jean-christophe-manciot** [libssh2/libssh2#101]
With commit 6d553a7bb94966466c4db0abf9a26660e786a275:
sudo autoreconf -i -v -f
autoreconf: Entering directory .
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in ..
libtoolize: copying file ./ltmain.sh
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, m4.
libtoolize: copying file m4/libtool.m4
libtoolize: copying file m4/ltoptions.m4
libtoolize: copying file m4/ltsugar.m4
libtoolize: copying file m4/ltversion.m4
libtoolize: copying file m4/lt~obsolete.m4
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:54: installing ./compile
configure.ac:28: installing ./config.guess
configure.ac:28: installing ./config.sub
configure.ac:20: installing ./install-sh
configure.ac:20: installing ./missing
configure.ac:5: error: required file example/libssh2_config.h.in not found
example/Makefile.am: installing ./depcomp
parallel-tests: installing ./test-driver
autoreconf: automake failed with exit status: 1

**Comment by jean-christophe-manciot** [comment]
Same error with commit 7b9a9a782d69c097f69a1992023bde9e4ead046f

**Comment by lferro9000** [comment]
As a workaround (i was also affected by this issue), i copied the file present on src into example and the configuration was built correctly (as in without the error anymore).

I had to use

  autoreconf -vfi

To get it rebuilt.

**Comment by jean-christophe-manciot** [comment]
Yes, I used the same workaround months ago, but forgot to update this thread. I have a different workflow which enabled me to build 1.7.0:
```
        echo -------------------
        echo "Making ./configure"
        echo "or replace all calls by autoreconf -v"
        echo --------------------------------------
        libtoolize
        aclocal -I m4
        autoheader

        echo -----------------------
        echo "Workaround to the bug: https://github.com/libssh2/libssh2/issues/101"
        echo -----------------------
        echo "configure.ac:5: error: required file 'example/libssh2_config.h.in' not found"
        echo -----------------------------------------------------------------------------
        cp -v src/libssh2_config.h.in example
        automake --gnu --add-missing
        autoconf

        echo -----------
        echo Configuring
        echo -----------
        ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var

        echo ---------
        echo Compiling
        echo ---------
        make
```

**Comment by bagder** [comment]
We provide the `./buildconf` script which is supposed to set everything up. Doesn't it work?

**Comment by jean-christophe-manciot** [comment]
Yes, it does. I missed it in the first place because that's an unusual name for autogen.sh.
