### ISSUE TITLE
AES-CTR test fails when cross-compiling for Android because of libz

### ISSUE THREAD

**Issue by afalkenhahn** [libssh2/libssh2#1016]
There seems to be a problem with the `configure` script when cross-compiling for Android. I'm cross-compiling for Android on macOS using 

    ./configure --host aarch64-linux-android --with-crypto=openssl --disable-shared --with-pic

However, the `configure` script doesn't pass the test for the AES-CTR functions in OpenSSL. The AES-CTR function test reports **NO** even though the functions exist (I'm using OpenSSL 1.1.1t). A look into `config.log` reveals that the AES-CTR test fails because the linker fails to resolve symbols from libz, e.g. `inflateInit` etc. So I can fix the issue by modifying the `configure` script like this:

    # Not all OpenSSL have AES-CTR functions.
    libssh2_save_LIBS="$LIBS"
    LIBS="$LIBS $LIBSSL -lz"    <---- I've added -lz here
    ac_fn_c_check_func "$LINENO" "EVP_aes_128_ctr" "ac_cv_func_EVP_aes_128_ctr"  

The only change I made is adding `-lz` to `LIBS` (line 3). Of course, this is just a workaround and not a general fix because OpenSSL can also be built without libz in which case `-lz` shouldn't be added. So I think the `configure` script needs to be modified in a way to first determine whether OpenSSL is built with libz support and then add `-lz` only in that case. I'm not too familiar with `autoconf` so I'm leaving the fix to someone who knows his trade...

**Comment by dfandrich** [comment]
Are you building against a static OpenSSL by any chance? libssh2 doesn't use
pkg-config to find the libraries, which means that it won't know any extra
libraries that will be needed when linking statically. Use adding it to LIBS
ought to work.

**Comment by vszakats** [comment]
Testing for `-lz` requirement may fix this particular case, but upcoming OpenSSL v3.2 will also support `brotli` and `zstd`, making this complex.

**Comment by afalkenhahn** [comment]
>Are you building against a static OpenSSL by any chance?

Yes. The Android NDK doesn't ship with OpenSSL so I had to build it myself as a static library.

> Use adding it to LIBS ought to work.

For some reason it doesn't. I've tried this:

    $ LIBS="-lz"
    $ ./configure --host=aarch64-linux-android --with-crypto=openssl --disable-shared --with-pic

But for some reason `configure` doesn't pick up `-lz` from `LIBS` and compiles the test program without `-lz`:

    /Users/andreas/Library/Android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android23-clang -o conftest -g -O2   conftest.c  -lssl -lcrypto >&5

**Comment by vszakats** [comment]
Are you sure `LIBS` was visible to `./configure`?

**Comment by dfandrich** [comment]
That's probably it. You can also define it right in the configure command-line to avoid contaminating the environment.

**Comment by afalkenhahn** [comment]
Ok, right, I can confirm that it works when passing `LIBS` directly to `configure`, i.e.

    ./configure --with-crypto=openssl --disable-shared --with-pic --host=aarch64-linux-android LIBS="-lz"

No idea why it didn't work when setting `LIBS` as an environment variable, though.

**Comment by vszakats** [comment]
> No idea why it didn't work when setting `LIBS` as an environment variable, though.

A missing `export`?

**Comment by afalkenhahn** [comment]
Oops, yeah, that was it.
