### ISSUE TITLE
SSH_MSG_DISCONNECT causes infinite loop in channel_wait_eof

### ISSUE THREAD

**Issue by TDi-jonesds** [libssh2/libssh2#102]
when the server sends a SSH_MSG_DISCONNECT the _libssh2_packet_add() function sets session->socket_state = LIBSSH2_SOCKET_DISCONNECTED; (packet.c:504). The channel_wait_eof() function has a while loop that calls _libssh2_transport_read() that returns LIBSSH2_ERROR_NONE (transport.c:329). The loop (channel.c:2255-2268) has no '0' handler so loops forever.

Changing transport.c:~330 from:
        if (session->socket_state == LIBSSH2_SOCKET_DISCONNECTED) {
            return LIBSSH2_ERROR_NONE;
        }
to:
        if (session->socket_state == LIBSSH2_SOCKET_DISCONNECTED) {
            return LIBSSH2_ERROR_SOCKET_DISCONNECT;
        }
seems a simple fix.

I went farther in my local code and changed the loop in the channel_wait_eof() (6 lines marked with //new) which cleaned up some error returns but I'm not sure it's the best way or place to handle it:

```
do {
    if (channel->remote.eof) {
        break;
    }
    rc = _libssh2_transport_read(session);
    if (rc == LIBSSH2_ERROR_EAGAIN) {
        return rc;
    }
    else if (rc < 0) {
        channel->wait_eof_state = libssh2_NB_state_idle;
        if (rc == LIBSSH2_ERROR_SOCKET_DISCONNECT) { //new
          // when we're disconnected we can't do much, set some flags and return 'ok' //new
          channel->remote.eof = 1; //new
          channel->remote.close = 1; //new
          return 0; //new
        }//new
        return _libssh2_error(session, rc,
                              "_libssh2_transport_read() bailed out!");
    }
} while (1);
```

**Comment by TDi-jonesds** [comment]
as far as I know this still hasn't been addressed

**Comment by willco007** [comment]
Sorry for letting this go stale. It seems your fix in transport.c should be added. It looks like when transport.c return type was updated this no error value was added, it should probably return an error state in this case.

**Comment by TDi-jonesds** [comment]
THANKS!
