### ISSUE TITLE
Is there a way to reset libssh2_sftp_last_error in libssh2-1.10.0?

### ISSUE THREAD

**Issue by Juanancg** [libssh2/libssh2#1039]
Hello,

I am using libssh2 version 1.10.0 in a C++ code to download files via SFTP. During the download process, I encountered an issue where libssh2_sftp_last_error was not being reset after a failed attempt to open a file due to lack of permissions. This resulted in subsequent successful file downloads also returning the same error code.

To provide context, here is an overview of the process I am using:

1. I establish a connection using libssh2 to the remote machine.
2. I initiate an SFTP session using libssh2_sftp_init.
3. Once I have the SFTP session, I retrieve the contents of all the files in a remote directory (which have already been listed).
4. In a for loop for each file, I:
5. Attempt to open the file using libssh2_sftp_open_ex.
6. If the handler is not null, I read the file contents using libssh2_sftp_read.
7. After downloading all the files, I close the handler and the SSH/SFTP sessions.

My issue occurred during step 5 when I attempted to download a file that had reading permissions only for root. This caused the download to fail, resulting in an error code of 3 in libssh2_sftp_last_error. However, when I attempted to download subsequent files, which did not have any permission issues, I noticed that libssh2_sftp_last_error still had a value of 3, even though the download was successful. This inconsistency is confusing and can be problematic.

While I have managed to handle this issue in my code by implementing a wrapper to manage libssh2_sftp_last_error, I believe it would be more convenient if the library handled this. I was wondering if it would be possible to add the ability to reset libssh2_sftp_last_error in a future version of the library. I understand that adding this functionality may not be without its challenges and I would appreciate it if you could consider this request at your convenience. I am also happy to implement this functionality myself and submit a pull request for review, if that is something you would find helpful.

Thank you for your attention to this matter. Please let me know if you need any additional information.

Regards,

Jota

_Ps: I want to apologize if I have made any mistakes in opening this issue. This is the first time I have contributed to an open-source project, and I am not entirely familiar with the process. Please let me know if there is anything I should do differently or if I need to provide additional information._

**Comment by vszakats** [comment]
We've merged a fix that's meant to fix this: e1e78e367023704060ada53256bcf57fd57f7a63 #787

You may want to give it a try with the latest master.

**Comment by Juanancg** [comment]
Thanks! That's exactly what I was looking for :)
