### ISSUE TITLE
SHA1/2 issue

### ISSUE THREAD

**Issue by jmssil** [libssh2/libssh2#1092]
I believe there is still some issue with the latest release of libssh2 related to SHA1 vs SHA2.

If I build libssh2 like this:

-DLIBSSH2_NO_RSA_SHA1 -DLIBSSH2_NO_DSA -DLIBSSH2_NO_RC4 -DLIBSSH2_NO_CAST -DLIBSSH2_NO_3DES -DLIBSSH2_NO_MD5

curl cannot negotiate keys:

* Set "rsa-sha2-256,rsa-sha2-512,ssh-rsa" as SSH hostkey type
* Failure establishing ssh session: -8, Unable to exchange encryption keys

I then tried to add -DLIBSSH2_RSA_SHA2 but the result was the same.

It only works if I enable SHA1 with -DLIBSSH2_RSA_SHA1.

Even though the negotiation occurs with the available SHA2 key, SHA1 is still allowed by libssh2, which is a problem.

**Comment by willco007** [comment]
Could you attach a log of the full negotiation? Thanks.

**Comment by willco007** [comment]
Also, what backend are you using?

**Comment by jmssil** [comment]
> Could you attach a log of the full negotiation? Thanks.

Without compiling with `--enable-debug` I get:

$ curl -v -T A sftp://127.0.0.1/home/shared/B
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1:22...
* Connected to 127.0.0.1 (127.0.0.1) port 22 (#0)
* Found host 127.0.0.1 in /home/shared/.ssh/known_hosts
* Set "rsa-sha2-256,rsa-sha2-512,ssh-rsa" as SSH hostkey type
* Failure establishing ssh session: -8, Unable to exchange encryption keys
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
curl: (2) Failure establishing ssh session: -8, Unable to exchange encryption keys

With debug I get:

[libssh2] 0.752481 Transport: Packet type 31 received, length=633
[libssh2] 0.752487 Transport: Looking for packet of type: 31
[libssh2] 0.752865 Key Ex: Server's SHA1 Fingerprint: 8b:69:81:71:a4:e5:75:bf:d2:04:02:54:92:f8:85:3d:1d:fa:c0:d2
[libssh2] 0.752884 Key Ex: Server's SHA256 Fingerprint: yniRvPwicYvR9/sGSadyG82JcxbUyn/ZPxb/4drjlVY=
[libssh2] 0.752892 Failure Event: unexpected rsa type: ssh-rsa
[libssh2] 0.752959 Failure Event: -10 - Unable to initialize hostkey importer ECDH
[libssh2] 0.752975 Failure Event: -8 - Unrecoverable error exchanging keys
[libssh2] 0.752982 Failure Event: -8 - Unable to exchange encryption keys
* Failure establishing ssh session: -8, Unable to exchange encryption keys

**Comment by jmssil** [comment]
> Also, what backend are you using?

I think it's OpenSSL:

  version:          1.11.0
  Host type:        x86_64-pc-linux-gnu
  Install prefix:   /usr/local
  Compiler:         gcc
  Compiler flags:    -DLIBSSH2_NO_RSA_SHA1 -DLIBSSH2_RSA_SHA2 -DLIBSSH2_NO_DSA -DLIBSSH2_NO_RC4 -DLIBSSH2_NO_CAST -DLIBSSH2_NO_3DES -DLIBSSH2_NO_MD5 -g -W -Wall -Wwrite-strings -pedantic -Wpointer-arith -Wnested-externs -Winline -Wmissing-prototypes -Wmissing-declarations -Wbad-function-cast -Wundef -Wno-long-long -Wno-multichar -Wshadow -Wsign-compare -Wunused -Wfloat-equal -Wno-format-nonliteral -Wendif-labels -Wstrict-prototypes -Wdeclaration-after-statement -Wstrict-aliasing=3 -Wno-system-headers -Wcast-align -Wtype-limits -Wold-style-declaration -Wmissing-parameter-type -Wempty-body -Wignored-qualifiers -Wconversion -Wno-sign-conversion -Wvla -ftree-vrp -Wdouble-promotion -Wformat=2 -Warray-bounds=2 -Wshift-negative-value -Wshift-overflow=2 -Wnull-dereference -fdelete-null-pointer-checks -Wduplicated-cond -Wunused-const-variable -Wduplicated-branches -Wrestrict -Walloc-zero -Wformat-overflow=2 -Wformat-truncation=1 -Warith-conversion -Wenum-conversion
  Library types:    Shared=yes, Static=yes
  Crypto library:   OpenSSL
  zlib compression: disabled; no libz found
  Clear memory:     yes
  Debug build:      yes
  Build examples:   yes
  Run Docker tests: yes
  Run sshd tests:   yes
  Path to sshd:     /usr/sbin/sshd (only for self-tests)

**Comment by willco007** [comment]
This message `unexpected rsa type: ssh-rsa` is only logged only if `LIBSSH2_NO_RSA_SHA1 ` was set.  But as @vszakats notes, `ssh-rsa` is still valid as a last resort using sha2 if the server sends it.

**Comment by willco007** [comment]
The trace log isn't showing enough information to identify what algos the server is sending and what libssh2 is negotiating.  You want to set something like `libssh2_trace(session, LIBSSH2_TRACE_KEX | LIBSSH2_TRACE_AUTH | LIBSSH2_TRACE_PUBLICKEY | LIBSSH2_TRACE_ERROR);`

**Comment by willco007** [comment]
My _guess_ is your server isn't quite configured correctly to be sending just sha2 keys correctly so when you disable sha1 it fails to authenticate.

**Comment by jmssil** [comment]
> This message `unexpected rsa type: ssh-rsa` is only logged only if `LIBSSH2_NO_RSA_SHA1 ` was set. But as @vszakats notes, `ssh-rsa` is still valid as a last resort using sha2 if the server sends it.

Yes, I set LIBSSH2_NO_RSA_SHA1 with the hope to remove the corresponding code/support from the lib.

Hum, I', not sure this should be tried as a last resort if LIBSSH2_NO_RSA_SHA1 is set.

I think what @vszakats meant was that the code should probably be like:

 #if LIBSSH2_RSA_SHA2 
     if(key_method_len == 7 && 
        memcmp(key_method, "ssh-rsa", key_method_len) == 0) { 
 #if LIBSSH2_RSA_SHA1 
         return "rsa-sha2-512,rsa-sha2-256,ssh-rsa"; 
#else
         return "rsa-sha2-512,rsa-sha2-256"; 
#endif
     } 
 #endif 

I have successfully removed "ssh-rsa" from the string to fix the issue I was observing.
