### ISSUE TITLE
OpenSSL HMAC_cleanup, and HMAC_Init are stated as deprecated

### ISSUE THREAD

**Issue by bagder** [libssh2/libssh2#11]
According to OpenSSL commit 00a5a74bbc854972c4 (Feb 10 2015). https://git.openssl.org/?p=openssl.git;a=commit;h=00a5a74bbc854972c4484a0b204bc9437d2757d9

Thus, building libssh2 with an OpenSSL from then or later causes link errors.

**Comment by vszakats** [comment]
Unless I'm misreading something obvious, this issue should be resolved after 73930e657709a571f4ea0d9089dbc16ba167aeaa.

I can also confirm successful builds using latest OpenSSL 1.1.0 master/HEAD alongside the latest revision of libssh2.

**Comment by bagder** [comment]
Ok, let me double-check my build setup so that I didn't mess something up...

**Comment by bagder** [comment]
Should be moot now, especially after 1.1.0 support was merged in commit 64ebfd8182.
