### ISSUE TITLE
libssh2_poll blocks forever if the remote system reboots

### ISSUE THREAD

**Issue by andre-brizido** [libssh2/libssh2#110]
I know that libssh2_poll is deprecated but for some reason on my application standard poll does not work.
I found out that libssh2_poll blocks forever if the remote system reboots. 
When this situation occurs, the netstat command shows that the corresponding socket is in CLOSE_WAIT. This happens because the remote system has sent a FIN but the local application has not yet closed the socket.

The reason is in the following block of code (session.c line 1671):

```
  case LIBSSH2_POLLFD_CHANNEL: 
                   if (sockets[i].events & POLLIN) { 
                       /* Spin session until no data available */ 
                       while (_libssh2_transport_read(fds[i].fd.channel->session) 
                              > 0); 
                   } 
                   if (sockets[i].revents & POLLHUP) { 
                       fds[i].revents |= 
                           LIBSSH2_POLLFD_CHANNEL_CLOSED | 
                           LIBSSH2_POLLFD_SESSION_CLOSED; 
                   } 
                   sockets[i].revents = 0; 
                   break; 
```

If the remote system has rebooted  _libssh2_transport_read returns LIBSSH2_ERROR_SOCKET_RECV. 
This error should not be ignored.
One possible correction could be:

```
    case LIBSSH2_POLLFD_CHANNEL:
                if (sockets[i].events & POLLIN) {
                   int ret;

                    /* Spin session until no data available */
                    while ( (ret = _libssh2_transport_read(fds[i].fd.channel->session))
                           > 0);                        
                    if (LIBSSH2_ERROR_SOCKET_RECV == ret)
                    {
                      /* Connection has been closed */   
                       sockets[i].revents = POLLHUP;
                    }
                }
                if (sockets[i].revents & POLLHUP) {
                    fds[i].revents |=
                        LIBSSH2_POLLFD_CHANNEL_CLOSED |
                        LIBSSH2_POLLFD_SESSION_CLOSED;
                }
```

Probably there are more errors that should not be ignored.

**Comment by tpham3783** [comment]
Do you know why libssh2_poll has been (or is going to be) depreciated.  The reason I am asking because I wrote my app for windows and linux, I had to use POSIX poll on linux, but on windows, poll api is very ugly.  I had a hard time getting it to work in windows.  Please share if you know why libssh2_poll should not be used..... thanks...

**Comment by andre-brizido** [comment]
I don't know exactly why libssh2_poll is deprecated.

That's what is stated in the manual: https://www.libssh2.org/libssh2_poll.HTML<https://www.libssh2.org/libssh2_poll.html>

Probably because there are more bugs than the one I reported.

Perhaps you should try asking to the developers.



________________________________
De: Toan <notifications@github.com>
Enviado: 4 de maio de 2017 21:49
Para: libssh2/libssh2
Cc: andre-brizido; Author
Assunto: Re: [libssh2/libssh2] libssh2_poll blocks forever if the remote system reboots (#110)


Do you know why libssh2_poll has been (or is going to be) depreciated. The reason I am asking because I wrote my app for windows and linux, I had to use POSIX poll on linux, but on windows, poll api is very ugly. I had a hard time getting it to work in windows. Please share if you know why libssh2_poll should not be used..... thanks...
