### ISSUE TITLE
libssh2_userauth_publickey_frommemory may not clear all errors

### ISSUE THREAD

**Issue by tjk** [libssh2/libssh2#1107]
**Describe the bug**

Successful operations using a memory ssh key seem to leave OpenSSL errors which causes other libraries that also check these errors to think they triggered an error when none did.

**To Reproduce**

https://github.com/tjk/libssh2-issues-1107

**Version (please complete the following information):**
 - OS and version: macOS
 - libssh2 version: 1.10.0
 - crypto backend and version: OpenSSL

**Additional context**

In ruby, using `libgit2`, we call `OpenSSL.errors.clear` after operations and everything works.
Pretty sure I traced this into `libssh2` rather than `libgit2` but will confirm tomorrow.

**Comment by tjk** [comment]
Added a repro to the original message.

**Comment by willco007** [comment]
It likely needs to be cleared on lines openssl.c:3899 and openssl.c:3531. If you add clearing there, does it fix your error?

**Comment by tjk** [comment]
@willco007 Sorry, I didn't see this message before -- but before I try this, are you thinking `PEM_read_bio_PrivateKey` leaves errors around? Or what makes you think those lines specifically? And also do you have examples of how the errors should be cleared?

**Comment by willco007** [comment]
Because it makes sense based on the code path you described. You can clear the error by calling `ERR_clear_error()` from OpenSSL.

**Comment by willco007** [comment]
I should elaborate a bit; when using a key that OpenSSL doesn't natively support, it will return an error and then we turn around and read it internally without clearing the OpenSSL error first.

**Comment by willco007** [comment]
@tjk did you have a chance to try my suggestion?

**Comment by tjk** [comment]
@willco007 been way too swamped recently. My workaround at least solves the immediate issue for me. Would be much more optimal for someone familiar with the repo to poke around and try to find the right fix than for me to do it at this time. Sorry.

**Comment by vszakats** [comment]
I think it's any code's responsibility to clear error codes before checking them. It also seems fair to assume that in most case there is an explicit operation setting the error code before checking it.

This doesn't seem like a libssh2 bug to me.
