### ISSUE TITLE
NMakefile not producing static library in Windows

### ISSUE THREAD

**Issue by feered** [libssh2/libssh2#111]
I am trying to compile libssh2 under Windows 10 environment with NMake. It is compiling with no issues but is only producing a DLL rather then a LIB file. I've gone through your documentation and have not seen anything regarding static libraries for Windows.

**Comment by sbredahl** [comment]
Are you sure it is actually a DLL file? I remember having a similar issue some time ago (with cmake maybe, not sure) where the resulting libssh2.dll was actually a static library with a wrong extension.

**Comment by alamaison** [comment]
On Thu, 26 May 2016 18:46 Chris, <notifications@github.com> wrote:

> I am trying to compile libssh2 under Windows 10 environment with NMake. It
> is compiling with no issues but is only producing a DLL rather then a LIB
> file. I've gone through your documentation and have not seen anything
> regarding static libraries for Windows.
>

If you're not already doing so, please generate the NMake file using CMake.
Make sure you set the BUILD_SHARED_LIBS option to OFF. That's the default
but you might have set it accidentally.

>

**Comment by feered** [comment]
@alamaison That is what I originally did but I noticed nothing really changed. Here is my command line:

> cmake -G "NMake Makefiles"

Is there something I am missing?

@sbredahl I had hopes for a second... but verified it's a shared library.

**Comment by alamaison** [comment]
Can you try the following with a fresh binary directory:

cmake -G "NMake Makefiles" -DBUILD_SHARED_LIBS=OFF

**Comment by feered** [comment]
@alamaison Tried that and no luck. Is this suppose to completely replace my NMakefile? I renamed it and cmake did not generate a new one.

Is there more documentation somewhere on this? I'm afraid that my environment is the reason this won't generate the new build files.

**Comment by alamaison** [comment]
Are you talking about the NMakefile in the project root directory?  CMake won't touch that.  It generates a separate build directory with the NMakefile in.  Where did you tell CMake to use as binary directory?  Check there.

I realise it's confusing having the NMakefile in the root directory too.  The repo contains several hardcoded build files for Windows but they aren't well maintained and you can't configure many options.  The ones you generate with CMake are all generated from the same source.  So anything you can do with one type, you can do with all of them.

**Comment by feered** [comment]
@alamaison Ah. That's what I was confused about. I ran the cmake build and was able to create the build files. I am generating my static library now.

My last question, is there something I need to set for a 64bit compile?

**Comment by alamaison** [comment]
CMake decides which compiler to choose for NMake based on the environment.  So to configure a 64-bit build, you need to run cmake from the 64-bit command prompt that came with your compiler.  Remember to use a fresh build directory.

**Comment by feered** [comment]
Ah. Okay. This is my first time using CMake. I was attempting to target 64bit after I had compiled the build files. I opened up the VS project file and noticed the targets were all set for x86. Rebuilt with Win64 arch set and compiled.
