### ISSUE TITLE
libssh2_scp_recv2 not populating fileinfo on Raspbian cross-build

### ISSUE THREAD

**Issue by DevAGCO** [libssh2/libssh2#1115]
**Describe the bug**
After having built the libssh2 library with Raspberry Pi cross-compiling tools and using the official scp example for reading, it has been noticed that the fileinfo (`libssh2_struct_stat`) is not populated by a successful call to `libssh2_scp_recv2`.

**To Reproduce**
Build the project with official Raspberry Pi cross-compiling tools: https://github.com/raspberrypi/tools
Use scp.c from examples (https://www.libssh2.org/examples/scp.html)
Create a text file with some text on remote unit, update path, ip and password accordingly.
Program runs correctly up to the while loop (`while(got < fileinfo.st_size) {`), where `fileinfo.st_size` is then equal to 0!

Interesting observations:
- By tweaking the code a bit, it is possible to call `libssh2_channel_read` and successfully extract all the data from the remote file.
- scp_write  (https://www.libssh2.org/examples/scp_write.html) works as a charm!

**Expected behavior**
It was expected that the fileinfo.st_size field would be populated with the remote file's size.

**Version (please complete the following information):**
 - Ubuntu 20.04
 - libssh2 version: 1.11.0
 - openssl version: 1.0.2s (built from conan) (note that latest version could not be used (see #1116)
 - pi tools: arm-linux-gnueabihf-gcc (crosstool-NG linaro-1.13.1+bzr2650 - Linaro GCC 2014.03) 4.8.3 20140303 (prerelease)

**Comment by DevAGCO** [comment]
Here you go!
[build.log](https://github.com/libssh2/libssh2/files/12023773/build.log)
[output.log](https://github.com/libssh2/libssh2/files/12023845/output.log)
Note: tested with different remote targets (embedded linux, Jetson NX) with same behaviour observed.
Thank you!

**Comment by vszakats** [comment]
Thanks @DevAGCO! It looks like the size is correctly read from the wire, but gets lost before returning it?

We had one possibly related patch (a cast added) since the 1.11.0 release. Does this make a difference in your case?:
c317e06faaee580e450f44cf3fca0b9e76f14ee5

**Comment by DevAGCO** [comment]
Thanks so much @vszakats for looking into this. Yes exactly. It's strange.

Nop! The patch does not solve the issue.

**Comment by vszakats** [comment]
Thanks for you tests. A next best thing is perhaps adding `printf()`s to strategic places (in between the correct readout and returning it to the caller) and see what happens there. It'd also useful to see the `sizeof(fileinfo.st_size)` vs. `sizeof(libssh2_struct_stat_size)`, just in case.

**Comment by DevAGCO** [comment]
Alright, I've been doing some testing. There seems to be a size mismatch for the type `off_t` between library code and application code.

Output below is pretty self-explanatory:
```
---------------------------------
Additional debug from scp.c
   session->scpRecv_size = 11, sizeof(session->scpRecv_size) = 8
   sb->st_size           = 11, sizeof(sb->st_size)           = 8   (<- assignement successful)
                               sizeof(off_t)                 = 8
   address of sb=0xFFD16F28
   address of sb->st_size=0xFFD16F58
         values @ address: 0xB, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 
---------------------------------
===========================================================
READING from main.c (after successful call to libssh2_scp_recv2):
	fileinfo.st_size = 0, sizeof(fileinfo.st_size) = 4
	                      sizeof(off_t)            = 4
   address of fileinfo=0xFFD16F28
   address of fileinfo.st_size=0xFFD16F54
         values @ address: 0x0, 0x0, 0x0, 0x0, 0xB, 0x0, 0x0, 0x0, 
===========================================================
```
That explains why value was 0. Where to go from here?

**Comment by vszakats** [comment]
It seems that libssh2 and the example code (`main.c`) end up using different cross-build settings/env.

Can you replicate the issue using the `example/scp` binary built as part of the libssh2 build process?

**Comment by DevAGCO** [comment]
Nop... :/ 
Then something is wrong in our setup.
Do you have any idea what it could be? I've attached our toolchain file just in case.
[raspberrypi_toolchain.txt](https://github.com/libssh2/libssh2/files/12035712/raspberrypi_toolchain.txt)

**Comment by DevAGCO** [comment]
Solved it! :)
`#define _FILE_OFFSET_BITS 64` was missing.
