### ISSUE TITLE
have the old canonical repo redirect here

### ISSUE THREAD

**Issue by jay** [libssh2/libssh2#112]
Up until today I had my libssh2 remote pointing to `git://git.libssh2.org/libssh2.git` but that doesn't appear to be updated anymore. It looks as though this is now the canonical repo. I changed my remote:
~~~
git remote set-url upstream https://github.com/libssh2/libssh2.git
~~~
but I could not cleanly update without a merge commit, I think because something in master in the old repo is missing from this one. So instead I reset my master branch and now everything is ok:
~~~
git reset --hard upstream/master
~~~
My suggestion is redirect to the new location if it's possible.

**Comment by bagder** [comment]
git doesn't support redirects in any convenient fashion AFAIK. I asked Sara to remove the DNS entry for `git.libssh2.org` now so at least people will start to get DNS errors if they keep using this name. That should hopefully trigger those users to check what's wrong and should make them figure out the repo is no longer there.
