### ISSUE TITLE
How to create a use OpenSSL library project by CMake?

### ISSUE THREAD

**Issue by nmgwddj** [libssh2/libssh2#116]
Use `CMake -G"Visual Studio 10 2010"` created project is not inlucde OpenSSL files.

How to create a use OpenSSL library project by CMake?

**Comment by alamaison** [comment]
It will use OpenSSL if it can find it.  Otherwise it will use native Windows cryptography.  If you want to force OpenSSL, specify `CRYPTO_BACKEND=OpenSSL`

**Comment by nmgwddj** [comment]
@alamaison Thanks for you.
