### ISSUE TITLE
Add Support for new OpenSSL 3 APIs

### ISSUE THREAD

**Issue by MichaelBuckley** [libssh2/libssh2#1206]
I'll be submitting a pull request shortly that implements this.

OpenSSL 1.1.1 and earlier have now been end-of-lifed, at least for those without a paid extended support contract. libssh2 still compiles with OpenSSL 3 and later, but many of the functions and types that it uses are deprecated, causing the compiler to warn about their use. This prevents projects with -Wall and -Werror enabled from compiling libssh2 from source.

OpenSSL defines a `OPENSSL_VERSION_NUMBER` that can be used to detect the version number at compile time. This could be used to conditionally compile code that uses the new, non-deprecated OpenSSL APIs.

**Comment by vszakats** [comment]
Implemented in #1207.

Closing this in favour of #1235, where we track a remaining issue.
