### ISSUE TITLE
Memory leak with diffie-helman-group-exchange-sha256 KEX

### ISSUE THREAD

**Issue by exaexa** [libssh2/libssh2#124]
I've noticed that libssh2 (standard debian stretch-available version, 1.7.0) leaks some amount of memory when using key exchange methods based on sha256 hashes. I'm running a fairly standard code (mostly the same as in "execute command" tutorial), with multiple sessions being created subsequently in one program run. Amount of transferred data in each program run is ~2MB. Server is standard debian openssh 6.7p1 with default configuration.

I have noticed that when using KEX method `diffie-hellman-group-exchange-sha256`, each session leaks around 5MB of memory. The problem completely disappears when I manually specify e.g. `diffie-hellman-group14-sha1`, with the exactly same code otherwise.

I'm using the other KEX as a workaround now, but having the leak fixed would be much better.

If there's some way I can help (provide some specific debug info?), please let me know.

**Comment by sbredahl** [comment]
Maybe you could run valgrind (apt get valgrind) and post your results?

$ valgrind --leak-check=yes <your_ssh_program> <your args>

/Sune

**Comment by exaexa** [comment]
```
==11430== Memcheck, a memory error detector
==11430== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==11430== Using Valgrind-3.12.0.SVN and LibVEX; rerun with -h for copyright info
==11430== Command: ./admslave
==11430== 
transfer start: VmSize:	  172200 kB
ssh done: VmSize:	  177372 kB
transfer start: VmSize:	  177372 kB
ssh done: VmSize:	  185980 kB
transfer start: VmSize:	  185980 kB
ssh done: VmSize:	  186412 kB
transfer start: VmSize:	  186428 kB
ssh done: VmSize:	  186860 kB
transfer start: VmSize:	  186860 kB
ssh done: VmSize:	  191388 kB
==11430== 
==11430== HEAP SUMMARY:
==11430==     in use at exit: 2,744,340 bytes in 9,589 blocks
==11430==   total heap usage: 13,296 allocs, 3,707 frees, 13,026,323 bytes allocated
==11430== 
==11430== 120 bytes in 5 blocks are definitely lost in loss record 10 of 27
==11430==    at 0x4C2BBCF: malloc (vg_replace_malloc.c:299)
==11430==    by 0x6E7F2B0: ??? (in /lib/x86_64-linux-gnu/libgcrypt.so.20.1.3)
==11430==    by 0x6E8047B: ??? (in /lib/x86_64-linux-gnu/libgcrypt.so.20.1.3)
==11430==    by 0x6F387C1: ??? (in /lib/x86_64-linux-gnu/libgcrypt.so.20.1.3)
==11430==    by 0x507355E: ??? (in /usr/lib/x86_64-linux-gnu/libssh2.so.1.0.1)
==11430==    by 0x5074D35: ??? (in /usr/lib/x86_64-linux-gnu/libssh2.so.1.0.1)
==11430==    by 0x507C1E8: libssh2_session_handshake (in /usr/lib/x86_64-linux-gnu/libssh2.so.1.0.1)
==11430==    by 0x404E6B: ssh_exec(char const*, char const*, char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, int) (ssh.cpp:121)
==11430==    by 0x403C15: transfer() (admslave.cpp:280)
==11430==    by 0x402EC2: main (admslave.cpp:516)
==11430== 
==11430== 120 bytes in 5 blocks are definitely lost in loss record 11 of 27
==11430==    at 0x4C2BBCF: malloc (vg_replace_malloc.c:299)
==11430==    by 0x6E7F2B0: ??? (in /lib/x86_64-linux-gnu/libgcrypt.so.20.1.3)
==11430==    by 0x6E8047B: ??? (in /lib/x86_64-linux-gnu/libgcrypt.so.20.1.3)
==11430==    by 0x6F387C1: ??? (in /lib/x86_64-linux-gnu/libgcrypt.so.20.1.3)
==11430==    by 0x507356C: ??? (in /usr/lib/x86_64-linux-gnu/libssh2.so.1.0.1)
==11430==    by 0x5074D35: ??? (in /usr/lib/x86_64-linux-gnu/libssh2.so.1.0.1)
==11430==    by 0x507C1E8: libssh2_session_handshake (in /usr/lib/x86_64-linux-gnu/libssh2.so.1.0.1)
==11430==    by 0x404E6B: ssh_exec(char const*, char const*, char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, int) (ssh.cpp:121)
==11430==    by 0x403C15: transfer() (admslave.cpp:280)
==11430==    by 0x402EC2: main (admslave.cpp:516)
==11430== 
==11430== 76,096 (57,072 direct, 19,024 indirect) bytes in 2,378 blocks are definitely lost in loss record 24 of 27
==11430==    at 0x4C2BBCF: malloc (vg_replace_malloc.c:299)
==11430==    by 0x6E7F2B0: ??? (in /lib/x86_64-linux-gnu/libgcrypt.so.20.1.3)
==11430==    by 0x6E8047B: ??? (in /lib/x86_64-linux-gnu/libgcrypt.so.20.1.3)
==11430==    by 0x6F387C1: ??? (in /lib/x86_64-linux-gnu/libgcrypt.so.20.1.3)
==11430==    by 0x6F36494: ??? (in /lib/x86_64-linux-gnu/libgcrypt.so.20.1.3)
==11430==    by 0x6E7C3D8: gcry_mpi_scan (in /lib/x86_64-linux-gnu/libgcrypt.so.20.1.3)
==11430==    by 0x507368F: ??? (in /usr/lib/x86_64-linux-gnu/libssh2.so.1.0.1)
==11430==    by 0x5074D35: ??? (in /usr/lib/x86_64-linux-gnu/libssh2.so.1.0.1)
==11430==    by 0x507C1E8: libssh2_session_handshake (in /usr/lib/x86_64-linux-gnu/libssh2.so.1.0.1)
==11430==    by 0x404E6B: ssh_exec(char const*, char const*, char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, int) (ssh.cpp:121)
==11430==    by 0x403C15: transfer() (admslave.cpp:280)
==11430==    by 0x402EC2: main (admslave.cpp:516)
==11430== 
==11430== 532,672 (57,072 direct, 475,600 indirect) bytes in 2,378 blocks are definitely lost in loss record 26 of 27
==11430==    at 0x4C2BBCF: malloc (vg_replace_malloc.c:299)
==11430==    by 0x6E7F2B0: ??? (in /lib/x86_64-linux-gnu/libgcrypt.so.20.1.3)
==11430==    by 0x6E8047B: ??? (in /lib/x86_64-linux-gnu/libgcrypt.so.20.1.3)
==11430==    by 0x6F387C1: ??? (in /lib/x86_64-linux-gnu/libgcrypt.so.20.1.3)
==11430==    by 0x6F36494: ??? (in /lib/x86_64-linux-gnu/libgcrypt.so.20.1.3)
==11430==    by 0x6E7C3D8: gcry_mpi_scan (in /lib/x86_64-linux-gnu/libgcrypt.so.20.1.3)
==11430==    by 0x507366C: ??? (in /usr/lib/x86_64-linux-gnu/libssh2.so.1.0.1)
==11430==    by 0x5074D35: ??? (in /usr/lib/x86_64-linux-gnu/libssh2.so.1.0.1)
==11430==    by 0x507C1E8: libssh2_session_handshake (in /usr/lib/x86_64-linux-gnu/libssh2.so.1.0.1)
==11430==    by 0x404E6B: ssh_exec(char const*, char const*, char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, int) (ssh.cpp:121)
==11430==    by 0x403C15: transfer() (admslave.cpp:280)
==11430==    by 0x402EC2: main (admslave.cpp:516)
==11430== 
==11430== LEAK SUMMARY:
==11430==    definitely lost: 114,384 bytes in 4,766 blocks
==11430==    indirectly lost: 494,624 bytes in 4,756 blocks
==11430==      possibly lost: 0 bytes in 0 blocks
==11430==    still reachable: 2,135,332 bytes in 67 blocks
==11430==         suppressed: 0 bytes in 0 blocks
==11430== Reachable blocks (those to which a pointer was found) are not shown.
==11430== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==11430== 
==11430== For counts of detected and suppressed errors, rerun with: -v
==11430== ERROR SUMMARY: 4 errors from 4 contexts (suppressed: 0 from 0)
```

Actually it seems gcrypt is leaking something. The program is doing a ssh operation five times and measures VmSize after each. It would otherwise run infinitely (and the memory would also grow infinitely). If I switch to the -group14-sha1 KEX, there is no increase in the VmSize, and no leaks.

(btw. the size reported by valgrind seems smaller than the size difference reported by VmSize; I suspect that gcrypt is leaking something internally that it destroys only on library `_fini` or something. I've ruled out that the leaked data could be deallocated by `ssh_shutdown()`)

**Comment by sbredahl** [comment]
Ok, I've never used libgcrypt with libssh2, only openssl and WINCNG. I have done extensive memory-leak testing on Windows using diffie-hellman-group-exchange-sha256 with no problems. Only the SHA256 hash is actually needed from the crypto lib, the kex function itself is native to libssh2. So I would probably look at the libgcrypt bindings to see what goes wrong here.

**Comment by doorsdown** [comment]
I also show this in my code but I am not using gcrypt and the amount I'm missing matches my leak summary

> ==13491==
==13491== 168 bytes in 1 blocks are definitely lost in loss record 155 of 190
==13491==    at 0x4C2AC00: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13491==    by 0x4FB11B5: CRYPTO_zalloc (mem.c:107)
==13491==    by 0x5BF129: _libssh2_cipher_init (openssl.c:239)
==13491==    by 0x5C5928: crypt_init (crypt.c:87)
==13491==    by 0x5A5DC5: diffie_hellman_sha256 (kex.c:1156)
==13491==    by 0x5A75EB: kex_method_diffie_hellman_group_exchange_sha256_key_exchange (kex.c:1657)
==13491==    by 0x5A9756: _libssh2_kex_exchange (kex.c:2542)
==13491==    by 0x5AEA1D: session_startup (session.c:726)
==13491==    by 0x5AECC8: libssh2_session_handshake (session.c:804)
==13491==    by 0x59E193: LdsSftp::setupHandshake() (in exe)
==13491==    by 0x59EFD5: LdsSftp::LdsSftp(std::string const&, std::string const&, ldsmdtcomms::Job_Authtype const&, int, std::string const&, bool) (in exe)
==13491==    by 0x4373F9: ldsarchive::archive_main(boost::shared_ptr<LdsArchiver>&) (in exe)
==13491==
==13491== 168 bytes in 1 blocks are definitely lost in loss record 156 of 190
==13491==    at 0x4C2AC00: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13491==    by 0x4FB11B5: CRYPTO_zalloc (mem.c:107)
==13491==    by 0x5BF129: _libssh2_cipher_init (openssl.c:239)
==13491==    by 0x5C5928: crypt_init (crypt.c:87)
==13491==    by 0x5A6348: diffie_hellman_sha256 (kex.c:1203)
==13491==    by 0x5A75EB: kex_method_diffie_hellman_group_exchange_sha256_key_exchange (kex.c:1657)
==13491==    by 0x5A9756: _libssh2_kex_exchange (kex.c:2542)
==13491==    by 0x5AEA1D: session_startup (session.c:726)
==13491==    by 0x5AECC8: libssh2_session_handshake (session.c:804)
==13491==    by 0x59E193: LdsSftp::setupHandshake() (in exe)
==13491==    by 0x59EFD5: LdsSftp::LdsSftp(std::string const&, std::string const&, ldsmdtcomms::Job_Authtype const&, int, std::string const&, bool) (in exe)
==13491==    by 0x4373F9: ldsarchive::archive_main(boost::shared_ptr<LdsArchiver>&) (in exe)
==13491==
==13491== LEAK SUMMARY:
==13491==    definitely lost: 336 bytes in 2 blocks
==13491==    indirectly lost: 0 bytes in 0 blocks

**Comment by doorsdown** [comment]
This seems to be fixed on the latest branch of the code base since 1.8.0 was release
