### ISSUE TITLE
Tests test_sshd.test 1 and 2 fail when environment variable $USER is not set

### ISSUE THREAD

**Issue by babelouest** [libssh2/libssh2#1240]
**Describe the bug**
If the tests are executed on a system where the environment variable `$USER` is not set, the tests `test_sshd.test` 1 and 2 fail.

I'm the maintainer for libssh2 in debian and I was informed in this bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1056348

The patch provided in the bug uses `$LOGNAME` if $USER isn't set.

**To Reproduce**
to reproduce the bug, unset the `$USER` variable, then run the tests:
`$ USER= make check`

**Expected behavior**
The test should pass but the tests `test_sshd.test` 1 and 2 fail when `$USER` isn't set

**Version (please complete the following information):**
Linux Debian Bookworm with libssh2 1.11.0 and libssh2 github master branch

**Additional context**
The variable `$USER` isn't mandatory on POSIX systems, so some shell don't set it by default, the variable `$LOGNAME` is mandatory though, so it could be a replacement, or, as mentioned in the bugreport, calling `get(e)uid` and
`getpwent()` would be a better solution, but I'm relying on your wisdom here.

**Comment by vszakats** [comment]
@babelouest: Thanks for your report. Falling back to `$LOGNAME` seems sensible (and simple) to cover this.

We're already falling back to `$USERNAME` for Windows, and I made a patch to do the same for `$LOGNAME` on other platforms.

Proposal here: #1241

**Comment by babelouest** [comment]
Thanks!
