### ISSUE TITLE
Alternative AS/400 port with Server-side KEX and SFTP channels

### ISSUE THREAD

**Issue by sprichard** [libssh2/libssh2#128]
This is a message for @bagder and @monnerat.
Please checkout my fork/branch at https://github.com/sprichard/libssh2/tree/as400_client_server_for_1.6.0.
This contains an alternative AS/400 port, based on OpenSSL which supports RSA and DSS Keys. It also supports i5/OS V5R4.
It also contains server-side key exchange and provides messaging support for SFTP channels, for use as an SFTP Server.

This was built on version 1.6.0, so as not to conflict with the AS/400 changes in the V1.7.0 master. I could not make a pull request, because there is no V1.6.0 branch.

Please let me know your thoughts on merging this with master and @monnerat 's work.

Thank you,
Stan Prichard

**Comment by bagder** [comment]
So this is different or in addition to #118 ?

Can you please make it a real pull-request in this repo so that we and others can review and possibly merge your work easier? Shouldn't your changes be made on top or in conjunction with the "AS/400 changes in the V1.7.0 master" ?

I can't speak for @monnerat, but my impression is that he will not be doing a lot of OS/400 work going forward so your assistance in this area will be greatly appreciated!

**Comment by sprichard** [comment]
To @bagder ,

Actually, this is different from the AS/400 changes that #118 mentions. This port does not use the iSeries Crypto Library. It uses OpenSSL. So, if adopted, these changes would obviate any existing issues with the Crypto Library. It also contains server-side support for SFTP channels and messages. My implementation does not require SCP at this time so that has not been done yet.

For a little history, I originally made these changes in V1.2.7.  I had originally contacted you about the V1.2.7 changes and you requested they be made to a more recent version. That was V1.6.0 at the time. Since then, V1.7.0 came out with a different AS/400 implementation. I have ported my AS/400 changes into V1.6.0 because my changes differ extensively from the changes made by @monnerat in V1.7.0.

As for making it a pull-request, there is a problem doing that against the V1.6.0 tag. I'm not sure what that problem is. Unfortunately, I am new to GIT and I'm still trying to figure this stuff out.

Thank you,
Stan Prichard

**Comment by sprichard** [comment]
To @bagder ,

Should I make this a pull-request against the master? It seems I cannot do it against the V1.6.0 tag.

Please let me know what I can do to make these changes available. I can send them to you if .zip format, if that would help.

I will be happy to do whatever needs to be done to make these changes part of the code base.

Thank you,
Stan Prichard

**Comment by bagder** [comment]
Against master would be the most helpful, but if you prefer emailing patches you can send them to the libssh2-devel mailing list and we can work them out there.

**Comment by monnerat** [comment]
I am currently in vacation, with a very limited access to internet. However I can confirm I do not yet know if I would still be in a position to maintain the OS/400 port.
I just wonder whether you have used a true OS/400 version of OpenSSL or have implemented libssl2 in the Pase environment. In the later case, your port cannot be called from a true OS/400 program, and your port is much like an AIX port...
Will be back in 2 weeks for further discussion if needed.

**Comment by sprichard** [comment]
It is a true OS/400 version of both OpenSSL and LIBSSH2. They do not use PASE.

Thank you,
Stan Prichard
