### ISSUE TITLE
Feature request: CMake setting to allow for libssh2.dll static VC++ runtime on Windows

### ISSUE THREAD

**Issue by jpluimers** [libssh2/libssh2#130]
Apparently my `CMake` foo is way below par as the below does not work so I'm missing something in https://cmake.org/Wiki/CMake_FAQ#How_can_I_build_my_MSVC_application_with_a_static_runtime.3F

Aim is to get rid of the `VCRUNTIME140.DLL` dependency by switching from `vcruntime.lib` (dynamic linking) to `libvcruntime.lib` (static linking of the VC++ runtime).

```
    git clone https://github.com/libssh2/libssh2.git
    pushd libssh2

    :: Try to force Static libraries (so VCRUNTIME140.DLL is not needed; hopefully this links libvcruntime.lib instead of vcruntime.lib)
    pushd cmake
    > c_flag_overrides.cmake type NUL
    >> c_flag_overrides.cmake echo    if(MSVC)
    >> c_flag_overrides.cmake echo        set(CMAKE_C_FLAGS_DEBUG_INIT "/D_DEBUG /MTd /Zi /Ob0 /Od /RTC1")
    >> c_flag_overrides.cmake echo        set(CMAKE_C_FLAGS_MINSIZEREL_INIT     "/MT /O1 /Ob1 /D NDEBUG")
    >> c_flag_overrides.cmake echo        set(CMAKE_C_FLAGS_RELEASE_INIT        "/MT /O2 /Ob2 /D NDEBUG")
    >> c_flag_overrides.cmake echo        set(CMAKE_C_FLAGS_RELWITHDEBINFO_INIT "/MT /Zi /O2 /Ob1 /D NDEBUG")
    >> c_flag_overrides.cmake echo    endif()

    > cxx_flag_overrides.cmake type NUL
    >> cxx_flag_overrides.cmake echo    if(MSVC)
    >> cxx_flag_overrides.cmake echo        set(CMAKE_CXX_FLAGS_DEBUG_INIT "/D_DEBUG /MTd /Zi /Ob0 /Od /RTC1")
    >> cxx_flag_overrides.cmake echo        set(CMAKE_CXX_FLAGS_MINSIZEREL_INIT     "/MT /O1 /Ob1 /D NDEBUG")
    >> cxx_flag_overrides.cmake echo        set(CMAKE_CXX_FLAGS_RELEASE_INIT        "/MT /O2 /Ob2 /D NDEBUG")
    >> cxx_flag_overrides.cmake echo        set(CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT "/MT /Zi /O2 /Ob1 /D NDEBUG")
    >> cxx_flag_overrides.cmake echo    endif()

    > MSVCC_static_linking.cmake type NUL
    >> MSVCC_static_linking.cmake echo set(CMAKE_USER_MAKE_RULES_OVERRIDE
    >> MSVCC_static_linking.cmake echo    ${CMAKE_CURRENT_SOURCE_DIR}/c_flag_overrides.cmake)
    >> MSVCC_static_linking.cmake echo set(CMAKE_USER_MAKE_RULES_OVERRIDE_CXX
    >> MSVCC_static_linking.cmake echo    ${CMAKE_CURRENT_SOURCE_DIR}/cxx_flag_overrides.cmake)

    > MSVCC_static_linking.cmake type NUL
    >> MSVCC_static_linking.cmake echo MESSAGE( WARNING "CMAKE_CURRENT_SOURCE_DIR: " ${CMAKE_CURRENT_SOURCE_DIR} )
    >> MSVCC_static_linking.cmake echo set(CMAKE_USER_MAKE_RULES_OVERRIDE
    >> MSVCC_static_linking.cmake echo    ${CMAKE_CURRENT_SOURCE_DIR}/cmake/c_flag_overrides.cmake)
    >> MSVCC_static_linking.cmake echo set(CMAKE_USER_MAKE_RULES_OVERRIDE_CXX
    >> MSVCC_static_linking.cmake echo    ${CMAKE_CURRENT_SOURCE_DIR}/cmake/cxx_flag_overrides.cmake)

    >> max_warnings.cmake echo include(MSVCC_static_linking)
    popd

    mkdir buildWin64
    pushd buildWin64
    :: Generate build for MSVS 2015
    ::cmake .. -G"Visual Studio 14 Win64" -D"BUILD_SHARED_LIBS=1" -D"CMAKE_BUILD_TYPE=Release" -D"OPENSSL_ROOT_DIR=../../openssl" -D"OPENSSL_LIBRARIES=../../openssl/ssl"
    cmake .. -G"Visual Studio 14 Win64" -D"BUILD_SHARED_LIBS=1" -D"CMAKE_BUILD_TYPE=Release"
    :: this fails bitching about v100 not being there:
    :: cmake --build . --config "Visual Studio 14 Win64"
    :: this just works:
    set Platform=
    call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\vcvars64.bat"
    call msbuild libssh2.sln /p:Configuration=Release /p:Platform=x64
    call dumpbin /headers example\Release\libssh2.dll | find "machine"
    popd
```

**Comment by kadorken** [comment]
Using the hints at http://stackoverflow.com/questions/10113017/setting-the-msvc-runtime-in-cmake
I have made the following change in libssh2-1.0.8/CMakeLists.txt as an experiment that changes the dynamic to static linking on the CFLAGS for WIN32. Note this change MUST be before the add_subdirectory(src) call in the CmakeLists.txt file.

The message calls can be removed; they were necessary for determining why it wasn't working as i put the change in various places.  Will try to clean up and make a module out of it and submit for consideration.

if(BUILD_SHARED_LIBS STREQUAL "OFF" AND WIN32)
message (STATUS, "HI THERE MANGLING CMAKE_CXX FLAGS"	)
  foreach(flag_var
		CMAKE_C_FLAGS_DEBUG CMAKE_C_FLAGS_MINSIZEREL CMAKE_C_FLAGS_RELEASE CMAKE_C_FLAGS_RELWITHDEBINFO
        CMAKE_CXX_FLAGS CMAKE_CXX_FLAGS_DEBUG CMAKE_CXX_FLAGS_RELEASE
        CMAKE_CXX_FLAGS_MINSIZEREL CMAKE_CXX_FLAGS_RELWITHDEBINFO)
	message( STATUS "BEFORE - '${flag_var}': ${${flag_var}}")
   if(${flag_var} MATCHES "/MD")
      string(REGEX REPLACE "/MD" "/MT" ${flag_var} "${${flag_var}}")
   endif(${flag_var} MATCHES "/MD")
   message( STATUS "AFTER  - '${flag_var}': ${${flag_var}}")
endforeach(flag_var)
endif()
#insert the above BEFORE this call for this to work
add_subdirectory(src)

**Comment by jpluimers** [comment]
Thanks. I've not had a chance yet to try looking deeper into CMake yet, so I'm really glad you took the effort.

Did you use the macros at https://github.com/onqtam/ucm#ucm_set_runtime as referred in the second answer of the question you referred to? http://stackoverflow.com/questions/10113017/setting-the-msvc-runtime-in-cmake/35328333#35328333

**Comment by kadorken** [comment]
No, I didn't use that macro package. I looked at it, but I don't use CMAKE myself and didn't see the need to add a whole macro package (sledgehammer) to solving the issue; I wanted the minimal change (small hammer) to make libssh2 statically linked on WIN32 for my purpose. I'll try to clean it up as an include file that libssh2 can keep and be included in the root level CmakeLists.txt file.

There are some other problems I need to address as well linking to the openssl 1.1.0c libraries (warnings about libssleay etc that are incorrect and do not apply when openssl 1.1.0c is being used)

**Comment by alamaison** [comment]
@jpluimers Were you able to test whether you were able to link against OpenSSL statically using CMake 3.5.2?

**Comment by kadorken** [comment]
Not very familiar with git pull requests; here is a patch file that modifies the src/CmakeLists.txt file to apply the CFLAG changes for static building.

[0001-Modify-WIN32-compiler-flags-for-BUILD_SHARED_LIBS-se.zip](https://github.com/libssh2/libssh2/files/632620/0001-Modify-WIN32-compiler-flags-for-BUILD_SHARED_LIBS-se.zip)
