### ISSUE TITLE
libssh2 tests are failing

### ISSUE THREAD

**Issue by bandi13** [libssh2/libssh2#1329]
**Describe the bug**
Tests are now failing with `libssh2_session_handshake failed (-43): Failed getting banner`. For example: see [here](https://github.com/libssh2/libssh2/actions/runs/8247987271/job/22557351094?pr=1327#step:11:137) or [here](https://github.com/libssh2/libssh2/actions/runs/8255358151/job/22581636483?pr=1328#step:15:1366)

**To Reproduce**
Open a PR with a non-substantive change (ie: change a README file)

**Expected behavior**
Tests should be passing

**Comment by vszakats** [comment]
Thank you @bandi13, this has been addressed via #1338 and #1339.
