### ISSUE TITLE
LIBSSH2_ERROR_EAGAIN ambiguity

### ISSUE THREAD

**Issue by victorstewart** [libssh2/libssh2#1395]
take `libssh2_session_handshake` for example, `session_startup` way return `LIBSSH2_ERROR_EAGAIN` when a send might block OR when a read might block... which makes it impossibly to elegantly integrate libssh2 into an asynchronous architecture around polling on the socket. i'd have to specify POLLIN and POLLOUT on every call, regardless of which we're blocking on. so we might really be blocking on a write but the poll operation will return success being able to read, creating a lot of unnecessary noise. ideally there would be different error codes to disambiguate this.

**Comment by bagder** [comment]
See [libssh2_session_block_directions](https://libssh2.org/libssh2_session_block_directions.html)

**Comment by victorstewart** [comment]
thank you!!!
