### ISSUE TITLE
Instable connections in case of SSH transfers over nonblocking sockets

### ISSUE THREAD

**Issue by klux21** [libssh2/libssh2#1397]
I faced instable TCP connections that are tunneled over SSH in case of transferring huge buffers using libssh2 1.10.0. 
I'm using libssh2 for SSH connections together with libressl and nonblocking sockets with possibly slow connections in usually single threaded applications. The problem was the usage of storage on the stack and relying on that data and it's address on the stack in subsequent calls once sending fails with EAGAIN or EWOULDBLOCK.
I did create a patch for version 1.10.0 and did see, that you have been working on a similar issue in 1.11.0 without resolving the reason of the problem. You'll find my patches of the sources in the attachment. I didn't yet verify the patch for version 1.11.0 and can't provide any test case. But it's just some few lines and not hard to understand. May be some of the maintainer of the library is able to have a look on the patches and to add those or better ones to the sources? Thanks in advance and for that library of course as well!

I have attached my patches and copies of the original files for version 1.10.0 and 1.11.0. I'm not insisting on any copyright of those little changes so everybody is free to use and modify that code according the copyright conditions of libssh2.
[libssh2-patches.tgz](https://github.com/libssh2/libssh2/files/15476613/libssh2-patches.tgz)

**Comment by vszakats** [comment]
> [...], that you have been working on a similar issue in 1.11.0 without resolving the reason of the problem.

Can you say which existing commit and/or PR was meant to address this issue?

Also, would you mind opening a PR with your modifications so that we can review and get it tested by CI?

**Comment by klux21** [comment]
I did only download the sources from https://libssh2.org only ( https://libssh2.org/download/libssh2-1.11.0.tar.gz ). 
I didn't checkout the sources from github and don't know git yet very well. A PR would take some time to learn git and 
I have no idea whether my changes are even suitable for the people here. That's why I attached the patches together with the original sources as a tgz. The sources should match the release tag libssh2-1.11.0  ( 1c3f1b7 ) here.

**Comment by vszakats** [comment]
@klux21 Perhaps this?: 33dddd2f8ac3bc811719e6422e9bec6458f91de3 #720

**Comment by vszakats** [comment]
Here's the suggested patch diffed from the tarball:
```diff
diff -r -u orig/src/libssh2_priv.h patch/src/libssh2_priv.h
--- orig/src/libssh2_priv.h	2023-05-04 08:32:38.000000000 +0200
+++ patch/src/libssh2_priv.h	2024-05-29 00:07:58.000000000 +0200
@@ -565,6 +565,8 @@
     unsigned char buf[PACKETBUFSIZE];
     unsigned char init[5];  /* first 5 bytes of the incoming data stream,
                                still encrypted */
+    unsigned char reply[5]; /* first 5 bytes of the outgoing data stream
+                               to continue with after EAGAIN */
     size_t writeidx;        /* at what array index we do the next write into
                                the buffer */
     size_t readidx;         /* at what array index we do the next read from
diff -r -u orig/src/packet.c patch/src/packet.c
--- orig/src/packet.c	2023-05-22 21:30:17.000000000 +0200
+++ patch/src/packet.c	2024-05-29 00:14:45.000000000 +0200
@@ -1109,9 +1109,10 @@
 
 
                 if(want_reply) {
-                    unsigned char packet[5];
+                    unsigned char *packet;
 libssh2_packet_add_jump_point4:
                     session->packAdd_state = libssh2_NB_state_jump4;
+                    packet = session->packet.reply;
                     packet[0] = SSH_MSG_CHANNEL_FAILURE;
                     memcpy(&packet[1], data + 1, 4);
                     rc = _libssh2_transport_send(session, packet, 5, NULL, 0);
diff -r -u orig/src/transport.c patch/src/transport.c
--- orig/src/transport.c	2023-05-22 21:30:17.000000000 +0200
+++ patch/src/transport.c	2024-05-28 23:34:47.000000000 +0200
@@ -775,8 +775,8 @@
            we don't add this one up until the previous one has been sent. To
            make the caller really notice his/hers flaw, we return error for
            this case */
-        _libssh2_debug((session, LIBSSH2_TRACE_SOCKET,
-                       "Address is different, but will resume nonetheless"));
+        return LIBSSH2_ERROR_EAGAIN;  /* Called with wrong packet address,
+                                         may be for a parallel connection */
     }
 
     *ret = 1;                   /* set to make our parent return */
```

/cc @migueldeicaza What do you think?

**Comment by klux21** [comment]
> @klux21 Perhaps this?: [33dddd2](https://github.com/libssh2/libssh2/commit/33dddd2f8ac3bc811719e6422e9bec6458f91de3) #720

Right - that  "return LIBSSH2_ERROR_BAD_USE;" before caused the termination of the connection. There was also a second problem because of the parallel connections and a different one was entering the function and forced to terminate because of that error and not being the expected one that provided the right pointer. That's  why I added that return of LIBSSH2_ERROR_EAGAIN so the right connection had a chance to continue later and the second one did just wait. But I didn't study the details of the library. For this it was just a workaround for preventing the cancellation of the connections.

**Comment by klux21** [comment]
To me your code above looks fine. Of course I didn't even try the new library version and don't have any test for that problem anymore as well. Thank you for that correction!
