### ISSUE TITLE
MAXPATHLEN not defined on hurd systems

### ISSUE THREAD

**Issue by babelouest** [libssh2/libssh2#1414]
**Describe the bug**
When building libssh2 on hurd* systems, the tests fail to build because `MAXPATHLEN` is not defined on those systems:

```
session_fixture.c:231:36: error: ‘MAXPATHLEN’ undeclared (first use in
this function)
  231 |     static char filepath[NUMPATHS][MAXPATHLEN];
      |                                    ^~~~~~~~~~
```

See [Debian build logs on hurd-i386](https://buildd.debian.org/status/fetch.php?pkg=libssh2&arch=hurd-i386&ver=1.11.0-5&stamp=1716421017&raw=0)

**Version (please complete the following information):**
 - OS and version: Debian hurd i386 and Debian hurd amd64
 - libssh2 version: 1.11.0
 - crypto backend and version: OpenSSL 3.2.2

**Additional context**
The build issue is in the test file [tests/session_fixture.c](https://github.com/libssh2/libssh2/blob/master/tests/session_fixture.c#L257)

The bug open in debian is [#1068076](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1068076)

**Comment by vszakats** [comment]
`MAXPATHLEN` has been in use since 54bef4c5dad868a9d45fdbfca9729b191c0abab5 (2018-03-21), released in 1.9.0. I'm curious why this didn't come up earlier. Could be a header that I deleted recently (though the report says that not offering this macro is intentional in hurd), or tests were not built earlier?

Either way, the patch posted by Mattias Ellert to the report looks like a good solution:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1068076#15

```diff
diff --git a/tests/session_fixture.c b/tests/session_fixture.c
index 3bb9da2..caeabfc 100644
--- a/tests/session_fixture.c
+++ b/tests/session_fixture.c
@@ -225,11 +225,7 @@ void stop_session_fixture(void)
 #define NUMPATHS 32
 const char *srcdir_path(const char *file)
 {
-#ifdef WIN32
-    static char filepath[NUMPATHS][_MAX_PATH];
-#else
-    static char filepath[NUMPATHS][MAXPATHLEN];
-#endif
+    static char *filepath[NUMPATHS];
     static int curpath;
     char *p = getenv("srcdir");
     if(curpath >= NUMPATHS) {
@@ -237,16 +233,14 @@ const char *srcdir_path(const char *file)
     }
     assert(curpath < NUMPATHS);
     if(p) {
-        /* Ensure the final string is nul-terminated on Windows */
-        filepath[curpath][sizeof(filepath[0]) - 1] = 0;
-        snprintf(filepath[curpath], sizeof(filepath[0]) - 1, "%s/%s",
-                 p, file);
+        int len = snprintf(NULL, 0, "%s/%s", p, file);
+        filepath[curpath] = malloc(len + 1);
+        snprintf(filepath[curpath], len + 1, "%s/%s", p, file);
     }
     else {
-        /* Ensure the final string is nul-terminated on Windows */
-        filepath[curpath][sizeof(filepath[0]) - 1] = 0;
-        snprintf(filepath[curpath], sizeof(filepath[0]) - 1, "%s",
-                 file);
+        int len = snprintf(NULL, 0, "%s", file);
+        filepath[curpath] = malloc(len + 1);
+        snprintf(filepath[curpath], len + 1, "%s", file);
     }
 
     return filepath[curpath++];
```

Would you like to open a PR for that?

**Comment by babelouest** [comment]
If you're ok with the patch then I can make a PR with pleasure.

Although the `malloc` in `filepath[curpath] = malloc(len + 1);` should be free afterwards.

**Comment by vszakats** [comment]
Thanks, I think the patch is good. I agree to free the pointers when appropriate.

**Comment by babelouest** [comment]
I've updated the patch to free allocated chars and made the PR https://github.com/libssh2/libssh2/pull/1415

Although, I wasn't able to test the patch with valgrind to make sure all the allocated data is cleaned. Do you have a method to test memory leaks?
