### ISSUE TITLE
The function "agent_sign" seems to always return ERROR

### ISSUE THREAD

**Issue by H3CzDong** [libssh2/libssh2#1417]
**Describe the bug**

The function "agent_sign" seems to always return ERROR.
can I return a error none to fix it?

**Version **

Trunk

**Comment by vszakats** [comment]
Can you tell more about your build, platform and code/example to reproduce?
You may also want to enable `ENABLE_DEBUG_LOGGING=ON` / `--enable-debug` for detailed error messages.

**Comment by vszakats** [comment]
Without more information it's not possible to act on or categorize this report.

Feel free to reopen in case of any new information.
