### ISSUE TITLE
rcvd too much data: Occasional Duplicate Packet Sent Causing Corrupted Data

### ISSUE THREAD

**Issue by rolag** [libssh2/libssh2#1431]
**Describe the bug**
While writing various stress tests for a library I'm writing built on libssh2 I found numerous errors where the data
sent over ssh (scp, exec, direct-tcp) does not match the data sent.

Usually this is accompanied by the following error in the openssh-server logs:
```text
channel 0: rcvd too much data 2176, win 1836
```
The exact amount of data in each case varies and the number of times this error occurs per session varies too.

**To Reproduce**
I uploaded a [repo](https://github.com/rolag/debug_libssh2) containing a minimum example necessary to reproduce this reliably.

```bash
# Download libssh2
git submodule update --init --recursive
# Build docker image for openssh-server
cd docker && DOCKER_BUILDKIT=1 docker build -t debug_libssh2:latest -f sshd.dockerfile . && cd ..
cd bugs/
./compile.sh
while [ $? -eq 0 ]; do
    ./run.sh ./rcvd 2>&1 >log
done
```

The while loop will keep running the code in `bugs/rcvd.c` until the error occurs. Usually this happens within 10 minutes or so but on powerful machines I find I need to execute the following to simulate a slow machine and/or busy network:
```bash
sudo tc qdisc change dev docker0 root netem loss 2.0%
# To undo the above changes:
# sudo tc qdisc delete dev docker0 root netem loss 2.0%
```

I have example output logs of `rcvd.c` in the file `bugs/rcvd.log` and at the very end it shows channel 3 received more data than was sent (by exactly one libssh2 packet size `16809916 - 32700 = 16777216`).
```
channel 3: rcvd too much data 32700, win 4352/2097152 (excess 28348)
channel 3: rcvd too much data 4352, win 0/2097152 (excess 32700)
...
Channel 3 total_sent=16777216 total_read=16809916
```

**Expected behavior**
The data sent should match the data received.

**Version:**
 - OS and version: macOS (M1 sonoma), Linux x86_64 (Ubuntu, Debian)
 - libssh2 version: 1.11.0
 - crypto backend and version: OpenSSL (Linux: 1.1.1f-1ubuntu2.22, Linux: 3.3.1-r3, Mac: 3.3.0)
 - openssh-server: 9.2 (Debian Bookworm), 9.8 (Debian Sid)

**Additional context**
Some additional testing showed that the duplicate packet matches an existing packet but "wrapped around" such that the total sent/received data matches the following equation for some values `x < y < z`: `sent[:y] == recv[:y] and sent[y:] == recv[y+32700:] and recv[y:y+32700] == (sent[y:z] + sent[x:y])`

When testing normally I only see duplicate packets, but when running the `tc qdisc` command I see either duplicate or missing data.

**Comment by dfandrich** [comment]
What crypto protocol has been negotiated when this happens?

**Comment by rolag** [comment]
```
kex algorithm: curve25519-sha256
kex: host key algorithm: ecdsa-sha2-nistp256
kex: client->server cipher: aes256-gcm@openssh.com
kex: server->client cipher: aes256-gcm@openssh.com
```

**Comment by rolag** [comment]
I tried the patch in issue #1397 and it appears to fix it because I can't reproduce the bug anymore with the patch applied. It seems that not returning early when `send_existing` is called by another thread causes libssh2 to send data it shouldn't

**Comment by klux21** [comment]
Can someone file a merge request for the patch in https://github.com/libssh2/libssh2/issues/1397 please?
