### ISSUE TITLE
session handshake fails on server banners larger than 256 bytes

### ISSUE THREAD

**Issue by palmin** [libssh2/libssh2#1442]
**Describe the bug**
`libssh2_session_handshake()` returns -1 when server has banner message that exceeds the 256 characters allowed by `_LIBSSH2_SESSION.banner_TxRx_banner` as key exchange fails because the full banner hasn't been read.

**To Reproduce**
Configure OpenSSH server with very long banner message by adding
`VersionAddendum " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit."`
to `sshd_config`

Connect to server using examples/ssh2

**Expected behavior**
`libssh2_session_handshake()` should be able to negotiate a connection. OpenSSH clients have no issues connecting to servers with very large banners.

**Version (please complete the following information):**
 - OS and version: macOS 14.6.1 (23G93)
 - libssh2 version: 1.11.1_DEV (814a850c97b0d535341868b4aefdfe76179330e9)
 - crypto backend and version: OpenSSL

**Additional context**
I have a [minimal fix](https://github.com/palmin/libssh2/commit/0b08e75d2010aa1ad7b8cb90743f3aacff6f4124) that keeps reading the server banner until reaching `\n` allocating new chunks of memory for session->remote.banner for each 256 bytes read.

Should I submit this as a PR?

**Comment by vszakats** [comment]
> **Additional context** I have a [minimal fix](https://github.com/palmin/libssh2/commit/0714d9dfd05739f88b2a3edb27613088227f2641) that keeps reading the server banner until reaching `\n` allocating new chunks of memory for session->remote.banner for each 256 bytes read.

Nice catch! Thanks for your report and patch.

> Should I submit this as a PR?

Yes, by all means!

**Comment by palmin** [comment]
PR #1443 is passing tests and ready for human review.
