### ISSUE TITLE
Memory leaks / heap corruption

### ISSUE THREAD

**Issue by muton85** [libssh2/libssh2#147]
Hello.

If:
1. Work with session in non-blocking mode.
2. Create channel with libssh2_channel_direct_tcpip (operation in blocking mode and switch back).
3. Close channel  libssh2_channel_free (operation in blocking mode and switch back).

Leads to memory leaks and sometimes to heap corruption.

Maybe I do something wrong?

**Comment by salva** [comment]
@muton85: it would help to get that issue fixed if you show us the program code (or even better, a reduced version that still exposes the issue) and also the output you get when running it with debug enabled.

**Comment by muton85** [comment]
Sorry for late response. I uploaded simple Visual Studio project.
It is socks proxy with non-blocking sockets.
As I don't know what to wait when I create tunnel (direct_tcpip) and close it (channel_free) - I switch session to blocking mode to not heat CPU on empty cycles.
Leaks occur on channel_free or maybe on session_free.

[Test.zip](https://github.com/libssh2/libssh2/files/604659/Test.zip)

**Comment by muton85** [comment]
Hi,
Any new here?

**Comment by salva** [comment]
The debugging output from your program is missing.

Anyway, you are not using libssh2 correctly!

In non-blocking mode, once you get a `LIBSSH2_EAGAIN_ERROR` you are expected to call the failed function again repeatedly with *exactly* the same arguments until it succeeds or returns other different error code.

If you call any other `libssh2` function (besides those given you information about the socket state and channel window sizes), the session state may become corrupted.

**Comment by muton85** [comment]
Salva,

I can not just call libssh2_channel_direct_tcpip in cycle, It eats 100% of CPU.
And can I use select to wait for channel will be opened? How to do it (wait for reading)?

I didn't call any other functions. I just switch library in blocking mode to be sure libssh2_channel_direct_tcpip will finish.

**Comment by muton85** [comment]
How to use select for waiting libssh2_session_free and libssh2_channel_free ?
I can't run them in cycle too.

**Comment by salva** [comment]
When you get a `LIBSSH2_ERROR_EAGAIN` after calling any of the library functions causing a network interaction, you have to call [libssh2_session_block_directions](https://libssh2.org/libssh2_session_block_directions.html) in order to discover if the library needs to write or/and to read to the socket, and then call `select` accordingly.

Once `select` tells you the socket is ready again, you have to call again the former libssh2 function passing exactly the same arguments.

**Comment by muton85** [comment]
Salva,

Thanks. I'll try it.

**Comment by muton85** [comment]
Salva,

I found two memory leaks:
1. libssh2_session_free logic in BLOCK_ADJUST (in blocking mode). if _libssh2_wait_socket will fail (for example with code LIBSSH2_ERROR_TIMEOUT - the session will be not freed.

2. crypt_dtor(LIBSSH2_SESSION * session, void **abstract)
does not have correspondent EVP_CIPHER_CTX_free((*cctx)->h);

**Comment by muton85** [comment]
Guys, any update? It causes a lot of memory leaks here.

**Comment by salva** [comment]
@muton85: could you confirm that using the function `libssh2_set_socket_closed` from pull request #165 fixes the first memory leak for you?

**Comment by muton85** [comment]
Salva,

Yes. If fixed the problem with realeasing memory of session.
But we have high-loaded application and I found some new leaks:
1. functions like _libssh2_EVP_aes_128_ctr in openssl.c has static var aes_ctr_cipher (pointer) which are passed make_ctr_evp - it will always allocate new memory, because you pass pointer * (not **).

2. this code must be at the session_free:
	/* startup_key_state */
    key_state = &session->startup_key_state.key_state_low;
    _libssh2_bn_free(key_state->g);
    key_state->g = NULL;
    _libssh2_bn_free(key_state->p);
    key_state->p = NULL;

	    /* exchange_state */
    exchange_state = &key_state->exchange_state;
    _libssh2_bn_free(exchange_state->x);
    exchange_state->x = NULL;
    _libssh2_bn_free(exchange_state->e);
    exchange_state->e = NULL;
    _libssh2_bn_free(exchange_state->f);
    exchange_state->f = NULL;
    _libssh2_bn_free(exchange_state->k);
    exchange_state->k = NULL;
    _libssh2_bn_ctx_free(exchange_state->ctx);
    exchange_state->ctx = NULL;

    if (exchange_state->e_packet) {
      LIBSSH2_FREE(session, exchange_state->e_packet);
      exchange_state->e_packet = NULL;
    }

    if (exchange_state->s_packet) {
      LIBSSH2_FREE(session, exchange_state->s_packet);
      exchange_state->s_packet = NULL;
    }

    if (exchange_state->k_value) {
      LIBSSH2_FREE(session, exchange_state->k_value);
      exchange_state->k_value = NULL;
    }

when some error occurs or I manually control the timeout on session in non-blocking mode - this resource will not be freed.

I'll ad some more places with leaks little bit later.

**Comment by salva** [comment]
@muton85: as it seems you are able to find and fix those issues by yourself, it would be better if instead of commenting code in this bug report, you just submitted pull requests with the fixes for those issues.

Pull request are far easier to understand, review and incorporate in the library than code excerpts from bug reports.

**Comment by muton85** [comment]
Salva,
I'll try to do this!
I found 2 more leaks:
1. session->server_hostkey in session_free is not always freed. I fixed it.
2. Here is I need your help. session->packet.payload in session_free - it seems that session->packet.total_num can be 0, but session->packet.payload is not freed. Can you look at it?

**Comment by salva** [comment]
> 2. Here is I need your help. session->packet.payload in session_free - it seems that session->packet.total_num can be 0, but session->packet.payload is not freed. Can you look at it?

I have pushed a fix for that into #165. Could you check it?

**Comment by muton85** [comment]
Hi Salva,

I already found the leak I told about. It occurs in non-blocking mode, then operation doesn't complete because of timeout. I am testing it's stability.

Actualy I fixed about 5 places and I would be very grateful if sombody can help me to make a pull request, because I never work with git. My code is fixed 1.8.1 ver.

**Comment by salva** [comment]
There should be several guides explaining that (for example, [this one](https://help.github.com/articles/fork-a-repo/)), so I am not going to write a new one, but the process is quite simple:

1. fork the project repository
2. clone your repository to your local machine
3. make your changes
4. commit
5. push
6. go back to your repository page at GitHub and create a pull request.

The GitHub documentation at [help.github.com](https://help.github.com/) is pretty good.

**Comment by muton85** [comment]
Hi Salva,
Here is my fixed code (1.8.1). I found about 5 places with leaks, and 1 with crash.
It seems code doesn't check buffer sizes and if lib receives wrong data - lib will crash.
[src.zip](https://github.com/libssh2/libssh2/files/806812/src.zip)

**Comment by willco007** [comment]
@muton85 instead of attaching your source files, please create a pull request.

**Comment by leo-zspace** [comment]
Guys, please don't give a helper hard times. Just pick up his fixes. LibSSH2 is really leaky and it's a shame in 2017. Peace. Git pull request is not a picnic for one who never used git (speaking from experience)... And we all have day time jobs.
