### ISSUE TITLE
Newline on trace messages is inconsistent

### ISSUE THREAD

**Issue by chrisemsen** [libssh2/libssh2#1485]
Build the library with debugging enabled, and enable tracing in any old ssh code.

The trace messages don't normally include a `\n`, except for memory dumps which do... 

![image](https://github.com/user-attachments/assets/b6c5e8ce-2262-43a5-aa2e-5da6f66ff4d5)

**Comment by vszakats** [comment]
Thanks for your report.

Can you tell which libssh2 version, OS, terminal have you seen this with? or anything important that reproduce it.

In CI, the newlines don't reproduce with the current version, as seen here on Linux and Windows:
https://github.com/libssh2/libssh2/actions/runs/11620453129/job/32362264057#step:17:661
https://ci.appveyor.com/project/libssh2org/libssh2/builds/50434492/job/k62rocyy58mfl54d#L21324

**Comment by chrisemsen** [comment]
Was latest version (at time of report) running on Windows.

 

I’d redirected logging to my own handler (below) which sends the output to my standard logging functions which prefixes the message with a timestamp and who’s generated the log message.

The code below does some formatted string magic to remove any newline character which fixed the problem for me.

 

static void ssh2_trace_handler (LIBSSH2_SESSION *pSession,

                                                           void *pContext,

                                                           const char *pString,

                                                           size_t Sz)

{

      int                              len = static_cast <int> ((pString [Sz-1] == '\n') ? (Sz-1) : Sz);

      Log::Info (LOG_SSH, "%.*s", len, pString);

}

 

 

                            /* Enable all debugging when libssh2 was built with debugging enabled */

                            libssh2_trace (mpSSH,/* LIBSSH2_TRACE_TRANS        |     */

                                                             LIBSSH2_TRACE_KEX          |

                                                             LIBSSH2_TRACE_AUTH         |

                                                             LIBSSH2_TRACE_CONN         |

                                                             LIBSSH2_TRACE_SCP          |

                                                             LIBSSH2_TRACE_SFTP         |

                                                             LIBSSH2_TRACE_ERROR        |

                                                             LIBSSH2_TRACE_PUBLICKEY    |

                                                             LIBSSH2_TRACE_SOCKET  );

                            libssh2_trace_sethandler (mpSSH, this, &ssh2_trace_handler);

 

Chris 
-----------------------------------------------------------------

**Comment by vszakats** [comment]
On an initial review the code looked correct to me, it left me wondering where any extra CR or LF may be coming from.

Do you see any place in the may be causing this?

**Comment by chrisemsen** [comment]
Looks like the problem is inconsistency in adding the \n.

 

 

void _libssh2_debug_low(LIBSSH2_SESSION * session, int context, const char *format,  ...)

{

    ...

    if(session->tracehandler)

        (session->tracehandler)(session, session->tracehandler_context, buffer,

                                msglen);

    else

        fprintf(stderr, "%s\n", buffer);

}

 

Adds the \n but only when using the default handler (tracehandler == nullptr)

 

Where as this function always added the \n, and then passes the same string the fault and non-default handlers.

 

static void debugdump(LIBSSH2_SESSION * session, const char *desc, const unsigned char *ptr, size_t size)

{

   ...

   buffer[used++] = '\n';

   buffer[used] = 0;

 

  if(session->tracehandler)

      (session->tracehandler)(session, session->tracehandler_context, buffer, used);

   else

       fprintf(stderr, "%s", buffer);

}

 

Chris 
-----------------------------------------------------------------

**Comment by vszakats** [comment]
Ah OK, thanks, I can see it.

Would this patch fix it for you?
```diff
--- a/src/transport.c
+++ b/src/transport.c
@@ -104,14 +104,13 @@ debugdump(LIBSSH2_SESSION * session,
             buffer[used++] = isprint(ptr[i + c]) ?
                 ptr[i + c] : UNPRINTABLE_CHAR;
         }
-        buffer[used++] = '\n';
         buffer[used] = 0;
 
         if(session->tracehandler)
             (session->tracehandler)(session, session->tracehandler_context,
                                     buffer, used);
         else
-            fprintf(stderr, "%s", buffer);
+            fprintf(stderr, "%s\n", buffer);
     }
 }
 #else
```

**Comment by vszakats** [comment]
historical context for this issue:

`debugdump()` has been working like it is since the trace handler has been introduced in 44eba0c9936af05a50651ecd2845a0b081052f8c (2010-01-15).
At that point a newline was passed to the trace handler always.
Then the newline was removed from the trace handler string for `libssh2_debug()`: 0f0652a3093111fc7dac0205fdcf8d02bf16e89f (2010-06-23)

Question is how to unbreak this breakage after so many years?
