### ISSUE TITLE
0x00007FFE7748F3C9 (ntdll.dll) (libcurlTest.exe 中)处有未经处理的异常: 0xC0000374: 堆已损坏。 (参数: 0x00007FFE774F97F0)。

### ISSUE THREAD

**Issue by u32744** [libssh2/libssh2#1493]
ntdll.dll!RtlReportCriticalFailure()	未知
 	ntdll.dll!RtlpHeapHandleError()	未知
 	ntdll.dll!RtlpHpHeapHandleError()	未知
 	ntdll.dll!RtlpLogHeapFailure()	未知
 	ntdll.dll!RtlpAllocateHeap()	未知
 	ntdll.dll!RtlpAllocateHeapInternal()	未知
 	ucrtbased.dll!heap_alloc_dbg_internal(const unsigned __int64 size, const int block_use, const char * const file_name, const int line_number) 行 359	C++
 	ucrtbased.dll!heap_alloc_dbg(const unsigned __int64 size, const int block_use, const char * const file_name, const int line_number) 行 450	C++
 	ucrtbased.dll!_calloc_dbg(unsigned __int64 count, unsigned __int64 element_size, int block_use, const char * file_name, int line_number) 行 518	C++
 	ucrtbased.dll!calloc(unsigned __int64 count, unsigned __int64 size) 行 30	C++
 	libcurl-d.dll!init_resolve_thread(connectdata * conn, const char * hostname, int port, const addrinfo * hints) 行 382	C
 	libcurl-d.dll!Curl_resolver_getaddrinfo(connectdata * conn, const char * hostname, int port, int * waitp) 行 648	C
 	libcurl-d.dll!Curl_getaddrinfo(connectdata * conn, const char * hostname, int port, int * waitp) 行 151	C
 	libcurl-d.dll!Curl_resolv(connectdata * conn, const char * hostname, int port, Curl_dns_entry * * entry) 行 484	C
 	libcurl-d.dll!Curl_resolv_timeout(connectdata * conn, const char * hostname, int port, Curl_dns_entry * * entry, __int64 timeoutms) 行 665	C
 	libcurl-d.dll!resolve_server(Curl_easy * data, connectdata * conn, bool * async) 行 6184	C
 	libcurl-d.dll!create_conn(Curl_easy * data, connectdata * * in_connect, bool * async) 行 6864	C
 	libcurl-d.dll!Curl_connect(Curl_easy * data, connectdata * * in_connect, bool * asyncp, bool * protocol_done) 行 6970	C
 	libcurl-d.dll!multi_runsingle(Curl_multi * multi, curltime now, Curl_easy * data) 行 1436	C
 	libcurl-d.dll!curl_multi_perform(Curl_multi * multi, int * running_handles) 行 2160	C
 	libcurl-d.dll!easy_transfer(Curl_multi * multi) 行 708	C
 	libcurl-d.dll!easy_perform(Curl_easy * data, bool events) 行 794	C
>	libcurl-d.dll!curl_easy_perform(Curl_easy * data) 行 814	C
 	libcurlTest.exe!connect_cloud(char * pc_ret, const char * host_addr, const int portno, const char * pc_method, curl_slist * http_headers) 行 121	C++
 	libcurlTest.exe!sina_get_stock(char * pc_ret, const char * pc_stockid) 行 180	C++
 	libcurlTest.exe!main() 行 197	C++

**Comment by vszakats** [comment]
Is libssh2 involved in this?
