### ISSUE TITLE
Curl_GetAddrInfoExW crashed

### ISSUE THREAD

**Issue by u32744** [libssh2/libssh2#1494]
when second run Curl_GetAddrInfoExW function , it's will crashed.  

  if((w_len > 0) && (w_len < MAX_NAME_LEN)) {
      /* do utf8 conversion */
      w_len = MultiByteToWideChar(CP_UTF8, 0, hostname, -1, namebuf, w_len);
      if((w_len > 0) && (w_len < MAX_NAME_LEN)) {
        swprintf(portbuf, MAX_PORT_LEN, L"%d", port);
        td->tsd.w8.hints.ai_family = hints->ai_family;
        td->tsd.w8.hints.ai_socktype = hints->ai_socktype;
        td->complete_ev = CreateEvent(NULL, TRUE, FALSE, NULL);
        if(!td->complete_ev) {
          /* failed to start, mark it as done here for proper cleanup. */
          td->tsd.done = 1;
          goto err_exit;
        }
        err = Curl_GetAddrInfoExW(namebuf, portbuf, NS_DNS,
                                  NULL, &td->tsd.w8.hints, &td->tsd.w8.res,
                                  NULL, &td->tsd.w8.overlapped,
                                  &query_complete, &td->tsd.w8.cancel_ev);

**Comment by vszakats** [comment]
How is it related to libssh2?

**Comment by u32744** [comment]
none depends libssh2, where you seen libssh2?

**Comment by vszakats** [comment]
You posted these issues to the libssh2 project.

**Comment by u32744** [comment]
so
