### ISSUE TITLE
configure script is ignoring --with-libssl-prefix flag

### ISSUE THREAD

**Issue by dibyendu** [libssh2/libssh2#166]
While configuring for 32 bit architecture on a 64 bit system with `./configure --with-openssl --with-libssl-prefix=[DIR] CFLAGS=-m32`, `configure` script is showing error that `libssl not found` (even though the 32 bit `libssl` library exists in `DIR`).

And when I remove the `CFLAGS=-m32` as  `./configure --with-openssl --with-libssl-prefix=[DIR]`, the script is taking `libssl` from system (i.e `/usr/local/lib/`), completely ignore the flag `--with-libssl-prefix`.

There is a bug in the logic of `configure.ac`

**Comment by Croydon** [comment]
I can confirm this. Please fix this.
