### ISSUE TITLE
can't seem to link to nonstandard openssl

### ISSUE THREAD

**Issue by kotoroshinoto** [libssh2/libssh2#17]
no matter what I do, it ends up linking to the system files:
libssl.so.10 => /usr/lib64/libssl.so.10 (0x00007f83a6248000)
libcrypto.so.10 => /usr/lib64/libcrypto.so.10 (0x00007f83a5e68000)

it should be linking to the ones in 
ls /UCHC/HPC/Gooch/biotoolmodules/openssl/1.0.2a/lib/
engines  libcrypto.a  libcrypto.so  libcrypto.so.1.0.0  libssl.a  libssl.so  libssl.so.1.0.0  pkgconfig

what do I need to tell the configure script to accomplish this?

**Comment by bagder** [comment]
Is that what ldd shows? If so, you need to make sure it picks the right libs at run-time, so it depends on your /etc/ld.so.conf setup. And you can also specify dir with `LD_LIBRARY_PATH`

**Comment by kotoroshinoto** [comment]
it wasn't a runtime link problem because that soname was the system version of openssl which was not binary compatible with the one I wanted it to use. When I added an additional line forcing it to give a directory path to the linker it then was able to find the correct library.

I'm still not quite sure why this was happening nor why I had to go out of my way to be explicit. I already HAD the runtime AND compile time environmental variables set, and it was defaulting to the system path library anyway.

**Comment by foldedspace** [comment]
It looks like "configure" is not honouring the "--with-libssl-prefix" argument:

     ./configure --prefix="/opt/libssh2-1.6.0" --with-openssl --with-libssl-prefix=/opt/openssl-1.0.2d

Gives me:
     ....
      configure: error: No crypto library found!
      Try --with-libssl-prefix=PATH
      or --with-libgcrypt-prefix=PATH
      or --with-wincng on Windows

Despite:

     $ ls /opt/openssl-1.0.2d/{bin,lib}
     /opt/openssl-1.0.2d/bin:
     c_rehash*  openssl*

     /opt/openssl-1.0.2d/lib:
     engines/  lib64@  libcrypto.a  libcrypto.so@  libcrypto.so.1.0.0*  libssl.a  libssl.so@    libssl.so.1.0.0*  pkgconfig/

However, the following works:

      CPPFLAGS="-I/opt/openssl-1.0.2d/include" LDFLAGS="-L/opt/openssl-1.0.2d/lib" ./configure --prefix="/opt/libssh2-1.6.0" --with-openssl --with-libssl-prefix=/opt/openssl-1.0.2d

**Comment by superbem** [comment]
Hi
I'm trying to compile with openssl git, but it returns the following error:
openssl.c: In function ‘_libssh2_rsa_new’:
openssl.c:71:11: error: dereferencing pointer to incomplete type ‘RSA {aka struct rsa_st}’

**Comment by bagder** [comment]
@superbem that's separate from this issue though, and I'd say most probably because OpenSSL has broken their API (which they've done a lot in their 1.1.x branch).

**Comment by superbem** [comment]
Changes between 1.0.2g and 1.1.0  [xx XXX xxxx]
  *) Made RSA and RSA_METHOD opaque. The structures for managing RSA
     objects have been moved out of the public header files. New
     functions for managing these have been added.
     [Richard Levitte]

  *) Made DSA and DSA_METHOD opaque. The structures for managing DSA objects
     have been moved out of the public header files. New functions for managing
     these have been added.
     [Matt Caswell]

**Comment by bagder** [comment]
so I was right...

**Comment by superbem** [comment]
Is there somewhere a libssh2 ready for openssl 1.1.0?

**Comment by bagder** [comment]
As soon as we get the patches that adapt and have them merged. Feel free help us making this happen. But please, stop using this issue for that topic.
