### ISSUE TITLE
libssh2_sftp_close() memory leaks

### ISSUE THREAD

**Issue by chenwanzh** [libssh2/libssh2#170]
hi
if 
1.Work with session in blocking mode. time out 2 second.
2.I delete file of writing on sftp server.
3.I continue to libssh2_sftp_write() will alway return LIBSSH2_ERROR_EAGAIN.
4. I call libssh2_sftp_close() will also return LIBSSH2_ERROR_EAGAIN, don't close sftp handle.
5.Leads to memory leaks;
Maybe I do something wrong?
how to slove the error?

**Comment by salva** [comment]
Attach the source code of your program (or even better, a reduced version that still triggers the bug).

Recompile the library with debugging support (`./configure --enable-debug ...`), add a call to `libssh2_trace` add the beginning of your program, run it and capture the output and attach it here.

Finally, include a detailed description of your environment, libssh2 version and compilation flags, your OS and version, etc.

**Comment by chenwanzh** [comment]
hi salva
    I debug some msg:
 1, write error:
50.991716 Socket: Sent 30080/30080 bytes at 0x57dbe280
 50.991722 SFTP: Writing packet requestid:5580
 50.991724 Conn: Writing 30029 bytes on channel 0/0, stream #0
 50.991728 Conn: Splitting write block due to 29247 byte window_size on 0/0/0
 50.991730 Conn: Sending 29247 bytes on channel 0/0, stream_id=0
 50.992255 Socket: Sent 29312/29312 bytes at 0x57dbe280
 50.992262 SFTP: Requiring packet 101 id 5509
 50.992265 SFTP: recv packet
 50.992267 Conn: channel_read() wants 4 bytes from channel 0/0 stream #0
 50.992272 Failure Event: -37 - would block
write errmsg:would block, rc:-9, direction:1
2, close sftp handle,  and adjust window:
 54.033591 SFTP: Closing handle
 54.033606 Conn: Writing 17 bytes on channel 0/0, stream #0
 54.033642 Socket: Recved 2336/16384 bytes to 0x57dba240+0
 54.033674 Conn: Window adjust for channel 0/0, adding 32768 bytes, new window_size=32768
 54.033686 Conn: 28 bytes packet_add() for 0/0/0
 54.033690 Conn: increasing read_avail by 28 bytes to 28/1942783
 54.033699 Conn: Window adjust for channel 0/0, adding 32768 bytes, new window_size=65536
 54.033705 Conn: 28 bytes packet_add() for 0/0/0
 54.033707 Conn: increasing read_avail by 28 bytes to 56/1942783
 54.033712 Conn: Window adjust for channel 0/0, adding 32768 bytes, new window_size=98304
3, always waiting close packet ask request:

 94.039340 SFTP: Writing close packet requestid:5660
 94.039351 SFTP: Requiring packet 101 id 5660
 94.039370 SFTP: recv packet
 94.039373 Conn: channel_read() wants 4 bytes from channel 0/0 stream #0
 94.039383 Failure Event: -37 - would block
failed,error msg:would block ,error code:-9, dir:1

 97.160742 SFTP: Writing close packet requestid:5660
 97.160758 SFTP: Requiring packet 101 id 5660
 97.160781 SFTP: recv packet
 97.160786 Conn: channel_read() wants 4 bytes from channel 0/0 stream #0
 97.160798 Failure Event: -37 - would block
failed,error msg:would block ,error code:-9, dir:1
4, for don't ask close packet on sftp server, so,sftp don't close, memory leaks.

**Comment by salva** [comment]
1. Attach the source code of your program (or even better, a reduced version that still triggers the bug).

2. Recompile the library with debugging support (./configure --enable-debug ...), add a call to libssh2_trace add the beginning of your program, run it and capture the output and attach it here.

3. Finally, include a detailed description of your environment, libssh2 version and compilation flags, your OS and version, etc.

**Comment by fjocean** [comment]
Hi,
libssh2_sftp_close()  has a memory leak issue?  How many Bytes will be leaked each time？

Thanks.
FJ
