### ISSUE TITLE
Libssh2.dll with latest version

### ISSUE THREAD

**Issue by jagadishthadakamalla** [libssh2/libssh2#183]
Hello,

Is there anyone having the compiled "libssh2.dll" in release mode. Preferably latest versions.
If so, can you please share them?

Thanks

**Comment by jagadishthadakamalla** [comment]
Hello.. 

Any one can help me out here, please.

**Comment by Samega7Cattac** [comment]
#184 
This file is libssh2.dll from apache
I don't know if this file will work but give it a try
[libssh2.zip](https://github.com/libssh2/libssh2/files/1061407/libssh2.zip)

**Comment by Samega7Cattac** [comment]
I have found the real one!
[libssh2.zip](https://github.com/libssh2/libssh2/files/1061475/libssh2.zip)

**Comment by bagder** [comment]
I would **strongly discourage** anyone from just blindly downloading and using random binaries posted on the Internet.

libssh2 is easy to build from source if you can't find a version to download from a trustworthy source.
