### ISSUE TITLE
libssh2.dll windows latest  binaries

### ISSUE THREAD

**Issue by jagadishthadakamalla** [libssh2/libssh2#184]
Hello,

Can anyone provide me the windows (compiled with visual studio) latest libssh2.dlls please?

Thanks.

**Comment by Samega7Cattac** [comment]
This file is libssh2.dll from apache
I don't know if this file will work but give it a try
[libssh2.zip](https://github.com/libssh2/libssh2/files/1061400/libssh2.zip)

**Comment by Samega7Cattac** [comment]
I have found the real one!
[libssh2.zip](https://github.com/libssh2/libssh2/files/1061472/libssh2.zip)

**Comment by jagadishthadakamalla** [comment]
Thanks for all the help. I could able to compile the code and generated the new dlls.
