### ISSUE TITLE
src/session.c doesn’t deal with both HAVE_POLL and HAVE_SELECT undefined

### ISSUE THREAD

**Issue by eschaton** [libssh2/libssh2#192]
I tried to port libssh2-1.8.0 to a non-POSIX platform yesteray—Mac OS 9.2.2 with Metrowerks CodeWarrior, using mbedTLS for crypto—and discovered that `_libssh2_wait_socket()` makes the assumption that `HAVE_POLL` being undefined implies `HAVE_SELECT` will be defined. Most of the rest of the file checks both explicitly and has some accomodation for not having either set.

(Really, I think it would be ideal if there were some “platform poll” abstraction to make it easier to port libssh2 to non-POSIX platforms, modeled after the “platform send” and “platform recv” abstractions.)

**Comment by eschaton** [comment]
With respect to the latter, see [Ticket 292 in Trac](http://trac.libssh2.org/ticket/292) which I filed a couple years ago. One thing I found with that is that libssh2 didn’t have an abstraction for setting a socket nonblocking, either. In that ticket, I suggested the following:

1. A `poll()` callback to be used in `_libssh2_wait_socket()` in place of `poll()` or `select()` directly.
2. A `get_blocking()` callback to get the blocking state of a socket.
3. A `set_blocking()` callback to set the blocking state of a socket.

**Comment by bagder** [comment]
Since nobody has implemented any such abstractions I figure there's not a huge demand. Maybe you should consider rolling up your sleeves and making this change yourself? If done properly I see no reason why we shouldn't accept such a PR into the project.

**Comment by eschaton** [comment]
I’m entirely aware of how both Open Source and pull requests work, thanks.

I haven’t done this myself not because I can’t, but because in order to do so I’ll have to go through a lot of bureaucracy. Not everyone can just automatically contribute whatever they do to an Open Source project.

**Comment by bagder** [comment]
> Not everyone can just automatically contribute

Exactly. And in this project we seem to basically have not a single person left who contributes code with regularity (merely 12 commits done since Jan 1st 2017!), so no code gets added...
