### ISSUE TITLE
Windows build errors

### ISSUE THREAD

**Issue by simon-p-r** [libssh2/libssh2#193]
Hi

I am having lots of errors when trying to compile libssh2 on Windows 10, it appears I cannot use a custom install location for OpenSSL to link against.  

Thanks
Simon

**Comment by simon-p-r** [comment]
I was about to ask on stackoverflow before someone but this [question](https://stackoverflow.com/questions/44889540/compiling-libssh2-on-windows) up, it appears building with openssl crypto backend is the problem.

**Comment by Samega7Cattac** [comment]
Ya, I made that question.
Using OpenSSL is tricky, now work well.
Is better to see the configs if you use cmake-gui.

**Comment by pkittenis** [comment]
There's a [conda package for libssh2](https://github.com/conda-forge/libssh2-feedstock) that seems to use OpenSSL backend.
