### ISSUE TITLE
Download files with different number of lines

### ISSUE THREAD

**Issue by Samega7Cattac** [libssh2/libssh2#195]
I'm trying to use the lib to download a file.
The problem is when I download the file and check is size with the original one, the sizes don't match!
The file created with libssh2 `libssh2_sftp_read` function have some extra bytes.

Code I use :
```
sftp_handle = libssh2_sftp_open(sftp_session, remotefile, LIBSSH2_FXF_READ, 0);
	if (!sftp_handle) return -1;
	char buf[99999];
	FILE * tmp = fopen(filename, "a+");
	size_t x = 0;
	do
	{
		x = libssh2_sftp_read(sftp_handle, buf, sizeof(buf));
		if(x > 0) fwrite(buf, sizeof(char), x, tmp);
	} while (x > 0);
	fclose(tmp);
	return x;
```

For example:
If I try to read a 147456 bytes file from my device it will create a file with 147456 bytes file, thats ok. But If I open the files, the original one have 809 lines and the downloaded have 1095 lines.

Some byte length with different number of lines.

**Comment by frankencode** [comment]
Try `fopen(filename, "a+b"`.
