### ISSUE TITLE
Memory leak in libgcrypt.c

### ISSUE THREAD

**Issue by beckmi** [libssh2/libssh2#209]
call to gcry_sexp_find_token in line 394 (function _libssh2_rsa_sha1_sign) has no corresponding call to gcry_sexp_release

**Comment by bagder** [comment]
Thanks, any change you can work up a pull-request to fix it?

**Comment by beckmi** [comment]
No - I have got that error using valgrind for one of my own programs.
Think it should be easy to place the corresponding gcry_sexp_release call for someone who is familiar with the code ...

**Comment by apccurtiss** [comment]
I just submitted pull request #370 to fix this - it's my first one, so let me know if I missed anything.

**Comment by willco007** [comment]
Fixed with #370, thanks for the PR!
