### ISSUE TITLE
Version Bump

### ISSUE THREAD

**Issue by smvoss** [libssh2/libssh2#220]
Hey everyone,

I was wondering if there is anything stopping version bumping from 1.8? I noticed it had been a year and there have been a lot of fixes since then.

**Comment by Croydon** [comment]
Please release a new version.

**Comment by bagder** [comment]
Brought to the list now: https://libssh2.org/mail/libssh2-devel-archive-2018-10/0002.shtml

**Comment by bagder** [comment]
See #277
