### ISSUE TITLE
libssh2 1.8.0 - Debian 9 - WARNING: secure clearing/zeroing of memory is not supported

### ISSUE THREAD

**Issue by dertin** [libssh2/libssh2#230]
Hi,

I'm seeing some mistakes that I do not understand. Maybe it's not important, but just in case I share it.
I'm running the test on Travis, the compilation works inside Docker with Debian 9. 64x

Source: https://libssh2.org/download/libssh2-1.8.0.tar.gz

```
./configure --with-openssl --with-libssl-prefix=/usr/local --with-libz --with-libz-prefix=/usr/local

make
make install

ldconfig
```
https://github.com/dertin/lemp-stack-debian/blob/develop/install.sh#L304-L309

The installation does not cancel, but leaves the following warning:
(stderr only, not stdout)
```
configure: WARNING: secure clearing/zeroing of memory is not supported by the selected crypto backend

ar: u modifier ignored since D is the default (see U)
```
https://travis-ci.org/dertin/lemp-stack-debian/jobs/314049987#L471-L472

**Comment by willco007** [comment]
This warning is stating the `clear memory` flag was not used at build time, that flag only affects the mbedtls and wincng backends. OpenSSL zeros memory by default and other sensitive locations are explicitly zero'd with the fix for #120 on master.
