### ISSUE TITLE
libssh2_session_banner_set()

### ISSUE THREAD

**Issue by davidwed** [libssh2/libssh2#231]
If I set my own banner, the error "Unable to exchange encryption keys" is returned by the "libssh2_session_handshake ()" function.

You can check the error with the example "sftp_write. c" by simply inserting "libssh2_banner_set (session,"myCustomBanner");" in front of the "libssh2_session_handshake()" function.

Without calling the function "libssh2_banner_set (session,"myCustomBanner");" the connection works fine.

With libssh2_banner_set():
[LogFile_libssh2_Fail.log](https://github.com/libssh2/libssh2/files/1643068/LogFile_libssh2_Fail.log)

Without libssh2_banner_set():
[LogFile_libssh2_OK.log](https://github.com/libssh2/libssh2/files/1643069/LogFile_libssh2_OK.log)

Environment:
libssh2 version 1.8.0

SSH-Server:
Debian 10 / SSH-2.0-OpenSSH_7.4p1
- sshd_config -> RekeyLimit 10M 30m

**Comment by davidwed** [comment]
Could also be related to
#203

**Comment by willco007** [comment]
According to the logs, both have the custom banner set. The one that succeeds is in blocking mode while the one that fails is not.

**Comment by davidwed** [comment]
However, the function "libssh2_session_set_blocking ()" is executed before the "libssh2_banner_set()" in both cases.

Enclosed a source code excerpt.
----
    /* Since we have set non-blocking, tell libssh2 we are blocking */
    libssh2_session_set_blocking(session, 1);
     
    rc = libssh2_banner_set(session,"myCustomBanner");
    if(rc)
    {
        fprintf(stderr, "Failure setting Banner: %d\n", rc);
        return -1;        
    }
 
    /* ... start it up. This will trade welcome banners, exchange keys,
     * and setup crypto, compression, and MAC layers
     */
    rc = libssh2_session_handshake(session, sock);

    if(rc) {
        fprintf(stderr, "Failure establishing SSH session: %d\n", rc);
        return -1;
    }
----

**Comment by salva** [comment]
Commit 712c6cbdd2f1b509f586aea5889a5c1deb7c9bda includes some fixes that may solve this issue

**Comment by salva** [comment]
Have you noticed that on the blocking case, the log shows that the banner being sent is the default one and not the custom one? It seems to me you are creating the ssh session object twice.

I think the real problem in the failing case is that the remote side is closing the connection because it doesn't like the banner. Note that banners must comply with [RFC 4253](https://tools.ietf.org/html/rfc4253#section-4.2) and yours isn't.

**Comment by davidwed** [comment]
That was the problem, thanks for the quick help.
