### ISSUE TITLE
Unpacking 'configure' with configure.ac

### ISSUE THREAD

**Issue by s103619** [libssh2/libssh2#233]
Need to generate the configure file, but running autoconf produces the following:

	configure.ac:6: error: possibly undefined macro: AM_MAINTAINER_MODE
		  If this token and others are legitimate, please use m4_pattern_allow.
		  See the Autoconf documentation.
	configure.ac:20: error: possibly undefined macro: AM_INIT_AUTOMAKE
	configure.ac:78: error: possibly undefined macro: AM_CONDITIONAL
	configure.ac:79: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
	configure.ac:80: error: possibly undefined macro: AC_PROG_LIBTOOL
	configure.ac:147: error: possibly undefined macro: AC_LIB_HAVE_LINKFLAGS

Afterwards the configure file doesn't work. 

	./configure: line 2202: AM_MAINTAINER_MODE: command not found
	checking for sed... /bin/sed
	./configure: line 2255: AM_INIT_AUTOMAKE: command not found
	checking libssh2 version... 1.8.1_DEV
	./configure: line 2265: AB_INIT: command not found
	configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."

**Comment by s103619** [comment]
Ah, you need to use buildconf. Why isn't this in the installation document? If it is, could someone show me where I was supposed to look? Thanks.

**Comment by bagder** [comment]
Because the release tarballs come with a `configure` script that you can just run?

**Comment by s103619** [comment]
Where in the repository are these tarballs?

**Comment by bagder** [comment]
The releases are not in the repository at all, they're on the [web site](https://libssh2.org/).

**Comment by bagder** [comment]
That's your decision. Those generic install instructions are however done for building from a release.

If you want to build straight off git, that's also fine but then you need to either invoke `./buildconf` before using `configure`, or take the cmake route.

**Comment by s103619** [comment]
Okay. I'm kind of new to building from repositories, so I thought the instructions were for that and not the releases.

Thanks for the help!
