### ISSUE TITLE
gen_publickey_from_rsa() in mbedtls.c doesn't seem to work correctly

### ISSUE THREAD

**Issue by swisspol** [libssh2/libssh2#234]
If building libssh2 against OpenSSL then `libssh2_userauth_publickey_fromfile()` works when passed a private key but no public key.

However, when building against mbedTLS, it doesn't return an error when trying to compute the public key from the private key using `gen_publickey_from_rsa()` but the resulting public key is not correct since SSH authentication fails.

**Comment by willco007** [comment]
If you wouldn't mind, could you wrap this up into a pull request? I'm not sure who, if anyone, is actively working on the mbedtls backend.

**Comment by skuodi** [comment]
Proposed fix PR #1560
