### ISSUE TITLE
Block directions returning bad values in latest master branch

### ISSUE THREAD

**Issue by pkittenis** [libssh2/libssh2#247]
There seems to have been a regression in `libssh2_session_block_directions` with the latest master branch changes.

With the latest code and session set to non-blocking mode, `block_directions` incorrectly returns both very large negative and positive values (possible overflow?) that make non-blocking clients think they should wait on the socket when they should not. 

This causes clients to constantly be waiting on the socket and the client hangs.

Here is an example with 1.8.0. `Directions <X>` is the output of `libssh2_session_block_directions` which the issue was tracked at.

```
DEBUG:pssh.ssh2_client:Connecting to 127.0.0.1:2222
DEBUG:pssh.ssh2_client:Proceeding with public key file authentication
DEBUG:pssh.ssh2_client:Attempting authentication with public key XXX.pub for user XXX
DEBUG:pssh.ssh2_client:Opening channel
Directions 1

DEBUG:pssh.ssh2_client:Executing command 'sleep 1; exit 2'
Directions 1

DEBUG:pssh.ssh2_client:Waiting for eof with timeout None
Directions 1

DEBUG:pssh.ssh2_client:Closing channel
```

And with latest master branch:

```
DEBUG:pssh.ssh2_client:Connecting to 127.0.0.1:2222
DEBUG:pssh.ssh2_client:Proceeding with public key file authentication
DEBUG:pssh.ssh2_client:Attempting authentication with public key XXX.pub for user XXX
DEBUG:pssh.ssh2_client:Opening channel
Directions -277438195
DEBUG:pssh.ssh2_client:Executing command 'sleep 1; exit 2'
Directions 0
DEBUG:pssh.ssh2_client:Waiting for eof with timeout None
Directions -1768319830
Directions -1768319830
<..>
```

After command is executed, `block_directions` returns a very large negative or positive integer. If the number happens to match the inbound/outbound masks, this causes the client to block forever.

```
DEBUG:pssh.ssh2_client:Connecting to 127.0.0.1:2222
DEBUG:pssh.ssh2_client:Proceeding with public key file authentication
DEBUG:pssh.ssh2_client:Attempting authentication with public key XXX.pub for user XXX
DEBUG:pssh.ssh2_client:Opening channel

Directions -1491489401

DEBUG:pssh.ssh2_client:Executing command 'sleep 1; exit 2'
Directions 0

DEBUG:pssh.ssh2_client:Waiting for eof with timeout None
Directions 2063908616

<Client blocks forever here>

```

This is repeatable, but client hanging only happens if the bad block directions number happens to match the masks. It seems to be more easy to repeat when running a command like `sleep 1` that causes socket waits.

In all cases with latest master, block directions output is incorrect when there is pending data on the socket. Does anyone have any info on this, any changes that could be causing block directions to return bad values? It looks suspiciously like an integer overflow error.

Can provide a standalone test case if needed, the output above is from a python wrapper. Be warned that with latest master non-blocking mode is broken.

**Comment by pkittenis** [comment]
Tracked it down [to this commit](https://github.com/libssh2/libssh2/commit/bbc43cb3337aebd36f8a484d296be268acd07d61) for adding SHA-256 host key fingerprints. 

Commit immediately prior does not have the issue and starts occurring from that commit onwards.

Do not yet understand why though, hopefully will mean something to someone else.

**Comment by willco007** [comment]
Hi Pan,
This is interesting issue. This commit seems innocuous at first glance. In fact, I've been running that specific code for years with no issues in non-blocking mode. Are you sure this commit is the one you're having troubles with?  A sample app would be most helpful. 

Thanks,

Will

**Comment by pkittenis** [comment]
My mistake - the changes in libssh2.h by that commit were causing code to get incorrect values. The project was not rebuilt after header was updated, so this occurred. Also explains why the seemingly innocuous commit caused it. Sorry for the false positive.

**Comment by willco007** [comment]
That would do it, glad you got it figured out!
