### ISSUE TITLE
Does this package supports openssl 1.1.0 ?

### ISSUE THREAD

**Issue by sadasant** [libssh2/libssh2#250]
I'm getting errors trying to build this package using 1.1.0. I'm building it through nodegit's dependency chain. See here for more info: https://github.com/nodegit/nodegit/issues/1490

Here are my logs: https://gist.github.com/sadasant/031d3f8bf1c4e5d2ac83b3841b7807fc

**Comment by willco007** [comment]
It does, you have to insure you're using version 1.7 or higher. In the logs I couldn't tell what version it was attempting to build, but it looked like it didn't include 1.1.0 support.

**Comment by sadasant** [comment]
Hello, yes, nodegit is using libssh2 version 1.7.0

**Comment by sadasant** [comment]
These erros in my logs are kind of odd: https://gist.github.com/sadasant/031d3f8bf1c4e5d2ac83b3841b7807fc#file-nodegit-node10-build-error-openssl-L887-L1110 does anyone see why would these errors be happening?

**Comment by RobinGeuze** [comment]
Libssh2 1.7.0 is not compatible with OpenSSL 1.1.0, for example the _libssh2_rsa_new function does not properly utilize the opaque structs introduced in 1.1.0. However the version tagged as 1.8.0 does appear to be compatible, however there doesn't seem to be an actual release made for that.

**Comment by kdudka** [comment]
On Wednesday, May 9, 2018 10:48:45 AM CEST RobinGeuze wrote:
> However the version tagged as 1.8.0 does appear to be compatible, however
> there doesn't seem to be an actual release made for that.

It has not been uploaded to Github but you can download the latest release
of libssh2 from the project page:

https://libssh2.org/

Kamil

**Comment by jaxxzer** [comment]
+1 same problem, looks like it requires libssh1.8, but nodegit is using 1.7

relevant issue report for libssh:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=874679

**Comment by willco007** [comment]
Libssh2 1.8 or higher supports OpenSSL 1.1 I'm going to close this report.
