### ISSUE TITLE
Replace public API convenience macros with functions

### ISSUE THREAD

**Issue by MSonn** [libssh2/libssh2#252]
I would like to discuss replacing the public API convenience macros e.g. libssh2_sftp_open for libssh2_sftp_open_ex with functions of the same signature as the macros.

This would result in 2 advantages for C and mainly C++ developers:

C and C++:
more shared code in the library

C++:
it would be possible to write generic template based handlers for code like this, that you have to repeatedly write otherwise 
 ```
do {
        sftp_handle =
        libssh2_sftp_open(sftp_session, sftppath,

                          LIBSSH2_FXF_WRITE|LIBSSH2_FXF_CREAT|LIBSSH2_FXF_TRUNC,
                          LIBSSH2_SFTP_S_IRUSR|LIBSSH2_SFTP_S_IWUSR|
                          LIBSSH2_SFTP_S_IRGRP|LIBSSH2_SFTP_S_IROTH);
 
        if (!sftp_handle &&
            (libssh2_session_last_errno(session) != LIBSSH2_ERROR_EAGAIN)) {

            fprintf(stderr, "Unable to open file with SFTP\n");
            goto shutdown;
        }
    } while (!sftp_handle);
```
Currently you have to resort to the ex functions in order to achieve this.

Afaik the ABI should be still backward compatible

**Comment by bagder** [comment]
I would approve of this. File a PR?

**Comment by bagder** [comment]
I'd call that a bug in the stale bot...!
