### ISSUE TITLE
when connect dropbear question

### ISSUE THREAD

**Issue by jiang-bei** [libssh2/libssh2#254]
when connect dropbear question
whataever the password is correct or not 
`        if (rc = (libssh2_userauth_password(session, username, passwd_arr[i])))
        {
            printf(FONT_COLOR_RED"%s:%d Found ssh eeeee %s \n"FONT_COLOR_NONE,__FILE__,__LINE__,passwd_arr[i]);
        }
        else
        {
            printf(FONT_COLOR_RED"%s:%d  Found ssh passwd %s \n"FONT_COLOR_NONE,__FILE__,__LINE__,passwd_arr[i]);
            break;
        }`

rc value is 0

Then the next connection will crash :
`crypto/evp/evp_enc.c:157: OpenSSL internal error: assertion failed: ctx->cipher->block_size == 1 || ctx->cipher->block_size == 8 || ctx->cipher->block_size == 16
`
 Can you give me an idea ？ Where do I make a mistake ？

**Comment by in7egral** [comment]
Faced the same problem just now - dropbear_2012.55
