### ISSUE TITLE
OpenSSL with no engine support

### ISSUE THREAD

**Issue by jlcharton** [libssh2/libssh2#255]
Hi all,

Header file openssl.h includes <openssl/engine.h>and openssl.c calls to ENGINE_load_builtin_engines() and ENGINE_register_all_complete() unconditionally even though openssl was compiled with no-engine option (that is OPENSSL_NO_ENGINE is explicitely defined in <openssl/opensslconf.h>).
Would you mind if I fix this with a couple of #ifndef OPENSSL_NO_ENGINE?

Regards,
J-L Charton

**Comment by willco007** [comment]
Fixed with commit d071e0e.

**Comment by jlcharton** [comment]
Hi Will,

Thank you for the fix.
However I think that the inclusion of <openssl/engine.h> in src/openssh.h should also be made conditional.
Regards,
JL

**Comment by willco007** [comment]
Good eye, I'll push a fix.

**Comment by willco007** [comment]
Added conditional with commit dd1b8be.

**Comment by DavidRusso** [comment]
Is it possible to get a rough idea when a release will be made that works with OpenSSL w/o engine support?

**Comment by Jan-E** [comment]
> Is it possible to get a rough idea when a release will be made that works with OpenSSL w/o engine support?

That might be May 21, according to Will Cosgrove in the mailinglist.
