### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by tuhaolam** [libssh2/libssh2#261]
In function ‘int do_session_handshake(lua_State*, int, lua_KContext)’:
error: ‘libssh2_session_handshake’ was not declared in this scope
In function ‘int l_set_timeout(lua_State*)’:
error: ‘libssh2_session_set_timeout’ was not declared in this scope

**Comment by willco007** [comment]
Are you attempting to build the library using a Lua wrapper? It looks like the Lua wrapper build is failing, not libssh2 directly.

**Comment by bagder** [comment]
No response
