### ISSUE TITLE
Update Minimum CMake version?

### ISSUE THREAD

**Issue by slurps-mad-rips** [libssh2/libssh2#265]
Hello,

libssh2 currently targets an extremely ancient version of CMake, and this causes some issues when trying to use it in newer contexts. While I understand the desire to permit its use on older systems, most systems out there have a post 3.0 CMake version available (even RedHat has moved off of CMake 2.8 IIRC). While I'm willing to put in the work to handle a build file rewrite, I'm curious to know if this sort of change would be accepted?

**Comment by kdudka** [comment]
On Wednesday, September 5, 2018 12:10:44 AM CEST Isabella Muerte wrote:
> Hello,
> 
> libssh2 currently targets an extremely ancient version of CMake, and this
> causes some issues when trying to use it in newer contexts.

Some issues?  What exactly did you try and what happened?

> While I
> understand the desire to permit its use on older systems, most systems out
> there have a post 3.0 CMake version available (even RedHat has moved off of
> CMake 2.8 IIRC).

Are you sure?  I can still see cmake-2.8.12.2 on my RHEL-7 box.

**Comment by slurps-mad-rips** [comment]
> Some issues? What exactly did you try and what happened?

The new FetchContent module in CMake 3.11 and later permits using projects as a subdirectory. To get libssh2 to work, I had to manually override cache variables before anything, and then I had to manually create an `INTERFACE` library so that other dependencies that used libssh2 could safely link against it. I also couldn't choose to *not* build unit tests (and anyone else down stream of my project would not be able to do so either) if I wanted to rely on the builtin `BUILD_TESTING` option for my own project. (Handling this sort of thing is actually fairly easy, but `FetchContent` has a tendency to show that many projects have... subpar cmake files).

Lastly, I have to manually modify the root CMake file to do a `list(APPEND CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/cmake)` *after* the `project` call so I can override some of the CMake modules that output way too much text during a rebuild (primarily FeatureSummary, as this would result in it rerunning a bunch of configuration checks... every... time...)

> Are you sure? I can still see cmake-2.8.12.2 on my RHEL-7 box.

Oh my mistakes. This is an instance of me assuming our machines at work were running stock RHEL 😅.

One other thing I would like to note: while I do appreciate the `find_package` capabilities built into the current CMake (something I'm also trying to fix with libgit2 at the moment, as they just dump a pkg-config file out and call it a day), it would be nice to have the ability to have my library pull down a specific commit of libssh2 as part of a build process, rather than requiring any users to have to do the download, configure, build, install steps themselves. As an example if there was a way for libgit2 to optionally download libssh2 as part of their build process under newer CMake versions that would solve my having to set some weird as hell variables to get them to place nice with FetchContent.

you can ignore the details of these cache wrapper functions in the code example below, but this is what I currently have to do to get libgit2 to play nice with libssh2 via FetchContent. You'll notice I'm forcing "USE_SSH" to off specifically so that it will... use ssh... :/

`module::SSH` is a special interface library I setup so that if we find libssh2 via `find_package` it'll be under there, otherwise libssh2 is manually placed under it instead for safe transitive linking.

```cmake
cache(ENABLE_ZLIB_COMPRESSION ON BOOL)
cache(CRYPTO_BACKEND WinCNG STRING)

cache(BUILD_EXAMPLES OFF BOOL)
cache(BUILD_CLAR OFF BOOL)

cache(USE_SSH OFF BOOL)
cache(LIBSSH2_FOUND TRUE BOOL)
cache(LIBSSH2_LIBRARIES module::SSH STRING)
cache(LIBSSH2_LIBRARY_DIRS $<TARGET_FILE_DIR:module::SSH> STRING)
```
