### ISSUE TITLE
about sftp copy file

### ISSUE THREAD

**Issue by lanjinh520** [libssh2/libssh2#270]
i want to copy remote file from directorA to directorB, What should I do?

**Comment by doorsdown** [comment]
Most sftp servers don't support this feature so there is no direct copy function, the best thing I can think of is using libssh2_sftp_opendir and libssh2_sftp_readdir_ex together to get the listing of directoryA and then either trying to opening file handles and directly writing, though I suspect this would not be a local copy as it would most likely come back to the calling program before going back into the destination file. In that case it would be better to download a copy of a file to your local machine and put it back up in the new location. While this is not ideal I believe it would better than trying to do bit wise copies.

**Comment by bagder** [comment]
SFTP has no "remote copy" feature.
