### ISSUE TITLE
new release: 1.8.1 is due on March 13, 2019

### ISSUE THREAD

**Issue by rc-matthew-l-weber** [libssh2/libssh2#277]
Would you mind releasing a new drop and I'll update the Buildroot package to use this version for the upcoming LTS release?

**Comment by ararslan** [comment]
Bump @bagder --- seems you do the release management around these parts. [Julia](https://github.com/JuliaLang/julia) needs to carry around a couple of patches for changes on libssh2 master that aren't in 1.8.0. It would be great to be able to update libssh2 and drop the patches. :slightly_smiling_face:

**Comment by bagder** [comment]
The (minuscule) libssh2 security team got a several security issues reported a while ago and we've been busy working on fixes to them as well as working on the documentation and coming advisories etc which has put a little dent in the release planning for the next release.

I think we all are ready for a release but it felt unnecessary to stress one out that doesn't have these issues fixed now that we are aware of them. I should hope that we get control of the situation and can offer a new release soon. Please bear with us.

**Comment by ararslan** [comment]
Thanks for the update, much appreciated!

**Comment by doorsdown** [comment]
Is there any update on this? Just curious on a ruff timeline to be expected.

**Comment by kloczek** [comment]
Even if it is several already reported issue on fixing each one would be good to make new release.
Really please make new release asap.

**Comment by hvariant** [comment]
any update on this?

**Comment by bagder** [comment]
I promise that you will notice when there is one.

**Comment by doorsdown** [comment]
Thank you, it is live now

**Comment by bagder** [comment]
Yes, but @willco007 decided to only do a 1.8.0 + security-fixes branch so 1.8.1 contains no other fixes than that... So I will suggest we make a 1.9.0 release from master asap.

**Comment by willco007** [comment]
We have the second half of the security fixing on master in a PR but we are cleaning up a bit more in that commit before taking it. Should be landed by EOD.

**Comment by bagder** [comment]
1.8.1 has been released. A 1.9.0 release is now discussed on the mailing list.

**Comment by jonathanturcotte** [comment]
Is there any update for a 1.9.0 release? The last thing I saw in the mailing list was a loose plan to release 1.9.0 on April 11th, but I haven't seen anything since.
