### ISSUE TITLE
libssh2_session_handshake.3 and libssh2_userauth_publickey_frommemory.3 man pages not installed by cmake build system

### ISSUE THREAD

**Issue by Arfrever** [libssh2/libssh2#278]
`docs/Makefile.am` and `docs/CMakeLists.txt` are out-of-sync.
`docs/Makefile.am` has references to all `libssh2_*.3` man pages, but `docs/CMakeLists.txt` is missing references to 2 man pages:
* `libssh2_session_handshake.3`
* `libssh2_userauth_publickey_frommemory.3`

```
$ cd docs
$ (for x in libssh2_*.3; do grep -q "${x}" Makefile.am || echo "${x}"; done)
$ (for x in libssh2_*.3; do grep -q "${x}" CMakeLists.txt || echo "${x}"; done)
libssh2_session_handshake.3
libssh2_userauth_publickey_frommemory.3
$ 
```

**Comment by bagder** [comment]
Thanks!
