### ISSUE TITLE
Memory leaks in wincng.c, kex.c, session.c

### ISSUE THREAD

**Issue by Zenju** [libssh2/libssh2#28]
Hi,

I've found the following memory leaks originating from the cryptography code:
1. file wincng.c, function _libssh2_wincng_cipher_init() allocates variable "ctx->pbIV":

```
    if (type.dwUseIV) {
        pbIV = malloc(dwBlockLength);
        if (!pbIV) {
            BCryptDestroyKey(hKey);
            free(pbKeyObject);
            return -1;
        }
        dwIV = dwBlockLength;
        memcpy(pbIV, iv, dwIV);
    } else {
        pbIV = NULL;
        dwIV = 0;
    }
```

But there is no corresponding clean up in function _libssh2_wincng_cipher_dtor()
1. In file kex.c an md5 checksum is generated as follows:

```
#if LIBSSH2_MD5
        {
            libssh2_md5_ctx fingerprint_ctx;

            if (libssh2_md5_init(&fingerprint_ctx)) {
                libssh2_md5_update(fingerprint_ctx, session->server_hostkey,
                                   session->server_hostkey_len);
                libssh2_md5_final(fingerprint_ctx, session->server_hostkey_md5);
                session->server_hostkey_md5_valid = TRUE;
            }
            else {
                session->server_hostkey_md5_valid = FALSE;
            }
        }
```

The check "if (libssh2_md5_init(&fingerprint_ctx))" seems to be incorrect and should probably be "if (libssh2_md5_init(&fingerprint_ctx) == 0)"

What happens is that "_libssh2_wincng_hash_init" internally allocs memory, which is never freed:

```
    pbHashObject = malloc(dwHashObject);
    if (!pbHashObject) {
        return -1;
    }
```
1. wincng.c, function _libssh2_wincng_hash.
   Leak if _libssh2_wincng_hash_update fails:

```
int
_libssh2_wincng_hash(unsigned char *data, unsigned long datalen,
                     BCRYPT_ALG_HANDLE hAlg,
                     unsigned char *hash, unsigned long hashlen)
{
    _libssh2_wincng_hash_ctx ctx;

    if (!_libssh2_wincng_hash_init(&ctx, hAlg, hashlen, NULL, 0)) {
        if (!_libssh2_wincng_hash_update(&ctx, data, datalen)) {
            if (!_libssh2_wincng_hash_final(&ctx, hash)) {
                return 0;
            }
        }
    }

    return -1;
}
```
1. file session.c, function session_free

This function cleans up cryptography only in case of LIBSSH2_STATE_NEWKEYS, but this is insufficient:

```
    if (session->state & LIBSSH2_STATE_NEWKEYS) {
        /* hostkey */
        if (session->hostkey && session->hostkey->dtor) {
            session->hostkey->dtor(session, &session->server_hostkey_abstract);
        }
```

It's possible that "session->state == 0", and but "session->hostkey->init" was run so that _libssh2_wincng_rsa_new internally allocated resources. Thous a "session->hostkey->dtor" is needed, but due to "if (session->state & LIBSSH2_STATE_NEWKEYS)" never called, therefore leaking memory.

How can "session->state == 0" while "session->hostkey->init" was run?
When libssh2_session_handshake() calls _libssh2_kex_exchange, which calls diffie_hellman_sha1, which runs

```
        if (session->hostkey->init(session, session->server_hostkey,
                                   session->server_hostkey_len,
                                   &session->server_hostkey_abstract)) {
            ret = _libssh2_error(session, LIBSSH2_ERROR_HOSTKEY_INIT,
                                 "Unable to initialize hostkey importer");
            goto clean_exit;
        }
```

if any of the subsequent failure conditions occur, e.g.

```
        exchange_state->k_value =
            LIBSSH2_ALLOC(session, exchange_state->k_value_len);
        if (!exchange_state->k_value) {
            ret = _libssh2_error(session, LIBSSH2_ERROR_ALLOC,
                                 "Unable to allocate buffer for K");
            goto clean_exit;
        }
```

then memory is leaked. There are probably more circumstances where this leak occurs, so it seems as if the session_free() function is to blame for not cleaning up thorougly.

PS: all these leaks occur in my libssh2 use, none of them is only theoretical.

Regards, Zenju

**Comment by mback2k** [comment]
> file wincng.c, function _libssh2_wincng_cipher_init() allocates variable "ctx->pbIV":
> ...
> But there is no corresponding clean up in function _libssh2_wincng_cipher_dtor()

Is already fixed since 6 May 2015 with https://github.com/libssh2/libssh2/commit/08fa27b6285c6634f837249936533542940bf165.

> In file kex.c an md5 checksum is generated as follows:
> ...
> The check "if (libssh2_md5_init(&fingerprint_ctx))" seems to be incorrect and should probably be "if (libssh2_md5_init(&fingerprint_ctx) == 0)"

No, because libssh2_md5_init is already defined as:

```#define libssh2_md5_init(ctx) \
  (_libssh2_wincng_hash_init(ctx, _libssh2_wincng.hAlgHashMD5, \
                            MD5_DIGEST_LENGTH, NULL, 0) == 0)```

> wincng.c, function _libssh2_wincng_hash. Leak if _libssh2_wincng_hash_update fails:

Thanks, should be fixed with https://github.com/libssh2/libssh2/commit/d0ffeba72e7100ea5af8a099660e90e74a4f1619.

@bagder, would you mind taking a look at the last more complex memory leak?
