### ISSUE TITLE
signed ed25519 keys

### ISSUE THREAD

**Issue by dsyeager** [libssh2/libssh2#289]
I'm hoping this is user error. Sorry if this is the wrong place to submit this.

For test purposes I've trimmed down example/ssh2.c to only try libssh2_userauth_publickey_fromfile and am calling that with:
user: root
pub key: /root/.ssh/id_ed25519-cert.pub
priv key: /root/.ssh/id_ed25519
passwd: ""

I've pulled down and build with the latest libssh2 (2 weeks ago) and the latest openssl. 

I've also cloned openssh-portable, built and tested with it's ssh which works.

My pub key starts with:
    ssh-ed25519-cert-v01@openssh.com
My priv key looks like:
-----BEGIN OPENSSH PRIVATE KEY-----
....
-----END OPENSSH PRIVATE KEY-----

when I attempt to run my modified example/ssh2.c 

userauth_publickey_fromfile, pub: /root/.ssh/id_ed25519-cert.pub, priv: /root/.ssh/id_ed25519
calling _libssh2_userauth_publickey (2) with sign_fromfile
_libssh2_userauth_publickey
calling sign_callback
sign_fromfile: /root/.ssh/id_ed25519
available method: ecdsa-sha2-nistp256
available method: ecdsa-sha2-nistp384
available method: ecdsa-sha2-nistp521
available method: ssh-ed25519
available method: ssh-rsa
available method: ssh-dss
No handler for specified private key, method: 'ssh-ed25519-cert-v01@openssh.com' 

Based on what openssh-portable's ssh is doing that looks like the correct flow it just doesn't have a method to handle "ssh-ed25519-cert-v01@openssh.com".

Any help would be appreciated.

**Comment by willco007** [comment]
Unfortunately, libssh2 currently doesn't support cert based auth.

**Comment by dsyeager** [comment]
Any plans to support it in the near future?

**Comment by willco007** [comment]
There are no immediate plans, but it's on the list. We'd be glad to review an PRs on it.

**Comment by dsyeager** [comment]
Was just reviewing, more indepth, what ssh is doing to sign the public key with the private key. I'm not a crypto guy and am foggy on the requirements of ssh in general. But it looks like it is just a matter of appending a signed version of the private key to the public key then sending that to the server? Which looks like it would be a method hander with the needed callback functions in hostkeys.c for the "ssh-ed25519-cert-v01@openssh.com" method?

Am I over simplifying that? How much more involved would it be?

**Comment by dsyeager** [comment]
I do have 2 weeks of slow time I can devote to getting this working but will need a little support for initial guidance/direction and reviews. It's either get libssh2 to work with it or try to use openssh-portable but I've already got libssh2 working in my framework for normal keys so would prefer to stick with libssh2.

**Comment by willco007** [comment]
I haven't looked at it in depth since demand has been low for the feature. A quick glance shows there is also signed host key support that would also need to be added. I'd be happy to help you out any way I could. I did the ECDSA/ED25519 key support so I have a general idea how things work. :)

**Comment by dsyeager** [comment]
The signed host key support in libssh2 was what I've been blocked on so far. ssh2 tries the private key, fails, then tries the pubic id_ed25519-cert.pub file. When trying the -cert.pub file it calls sign_fromfile(.."id_ed25519"..) but passes "ssh-ed25519-cert-v01@openssh.com" from the -cert.pub file as the method so it fails to read in the private key. Was hoping that most of the work would be implementing a LIBSSH2_HOSTKEY_METHOD for "ssh-ed25519-cert-v01@openssh.com". Probably similar to 

static const LIBSSH2_HOSTKEY_METHOD hostkey_method_ssh_ed25519 = {
    "ssh-ed25519",
    SHA256_DIGEST_LENGTH,
    hostkey_method_ssh_ed25519_init,
    hostkey_method_ssh_ed25519_initPEM,
    hostkey_method_ssh_ed25519_initPEMFromMemory,
    hostkey_method_ssh_ed25519_sig_verify,
    hostkey_method_ssh_ed25519_signv,
    NULL,                       /* encrypt */
    hostkey_method_ssh_ed25519_dtor,
};

but specific to certs.

I'll look more into what sign_fromfile does and how that differs from the ssh cmd.

**Comment by dsyeager** [comment]
Lots more to ssh than expected from the outside. Think I have the signature being generated, formatted correctly. Ends up 83 bytes and mostly matches the signature generated by openssh-portable's ssh. 

It looks like openssh-portable uses sha512 when generating the signature. I started by using  EVP_DigestSign (from your ed25519 word) to get the signature but that says PureEdDSA instead of specifying SHA512. Am I reading that wrong? If not should PureEdDSA work in place of sha512?

**Comment by willco007** [comment]
If it works like the other host key types, the signature would be sha512'd and stored in kex.c.

**Comment by DerekTBrown** [comment]
@dsyeager do you have a branch somewhere I can take a look?

**Comment by carlhoerberg** [comment]
I'm happy to sponsor the support for signed ed25519 certificates. Please contact me at carl@84codes.com if you're interested.
