### ISSUE TITLE
bugs found by our scanner 

### ISSUE THREAD

**Issue by lqiulin** [libssh2/libssh2#290]
Hi, we developed a taint analysis based static analysis tool named Vanguard. It could prognosis potential vulnerabilities by identifying security-sensitive operations (e.g. divide-zero, mod-zero, array-index-access, and sensitive function calls) without proper checks for their operands.

Some code locations are listed in the following. We think these locations maybe bugs after our manual analysis. Please check them, and add precondition checks if necessary.

**Sensitive-Function-Call**
1.in function `sftp_stat`, [sftp.c#L3301](https://github.com/libssh2/libssh2/blob/master/src/sftp.c#L3301)
`memset(attrs, 0, sizeof(LIBSSH2_SFTP_ATTRIBUTES));`
[memset] is a security-sensitive function using tainted data: [attrs]

2.in function `_libssh2_dsa_sha1_sign`, [openssl.c#L1844](https://github.com/libssh2/libssh2/blob/master/src/openssl.c#L1844)
`memset(signature, 0, 40);`
[memset] is a security-sensitive function using tainted data: [signature]

3.in function `_libssh2_transport_read`, [transport.c#L425](https://github.com/libssh2/libssh2/blob/master/src/transport.c#L425)
`memcpy(p->init, block, 5);`
[memcpy] is a security-sensitive function using tainted data: [p->init]

4.in function `netconf_read_until`, [subsystem_netconf.c#L77](https://github.com/libssh2/libssh2/blob/master/example/subsystem_netconf.c#L77)
`memset(buf, 0, buflen);`
[memset] is a security-sensitive function using tainted data: [buflen  buf  ]

5.in function `mac_method_hmac_sha1_96_hash`, [mac.c#L246](https://github.com/libssh2/libssh2/blob/master/src/mac.c#L246)
`memcpy(buf, (char *) temp, 96 / 8);`
[memcpy] is a security-sensitive function using tainted data: [buf ]

6.in function `mac_method_hmac_md5_96_hash`, [mac.c#L318](https://github.com/libssh2/libssh2/blob/master/src/mac.c#L318)
`memcpy(buf, (char *) temp, 96 / 8);`
[memcpy] is a security-sensitive function using tainted data: [buf ]

**Comment by willco007** [comment]
Thanks for the notes; I've reviewed these issues and here are my notes:

#1 - API is a consumer facing feature, if the consumer passes in bogus data it could crash.
#2 - _libssh2_dsa_sha1_sign() internal API call and is called with a buffer size of 40, will be the correct size for memset() call.
#3 - Will be fixed with future PR.
#4 - example app and not part of library
#5 - buf is fixed size of 64, temp is fixed size of 20, only copying 12 bytes into buffer.
#6 - same as #5.

**Comment by willco007** [comment]
#3 was resolved with commit f6a8d1202cccd8527b623f3957763deb879ad435

**Comment by willco007** [comment]
The main issue here was resolved, we could add additional bounds checking for 4 and 5 to prevent API mis-use.
