### ISSUE TITLE
libssh2 1.5.0 is not working with openssl1.1.1a

### ISSUE THREAD

**Issue by anthekool** [libssh2/libssh2#291]
i am building libssh2 version 1.5.0 with openssl 1.1.1a but getting error during build.it is building successfully with openssl1.0.2.
is there any patch available for libssh2 for support of openssl1.1.1a

**Comment by doorsdown** [comment]
I would say try building with version 1.8.0

**Comment by willco007** [comment]
Yes, 1.8 was the first version to support OpenSSL 1.1.
