### ISSUE TITLE
ed25519 Error "Invalid address specified to RtlFreeHeap" if use different memory manager

### ISSUE THREAD

**Issue by dimmaq** [libssh2/libssh2#292]
Hello/
I use libssh2.dll in delphi project. Libssh2 initiated with delphi mem manager.
```
function sshAllocMem(count: UINT; _abstract: PPointer): Pointer; cdecl;
begin
  Result := GetMemory(count);
end;
procedure sshFreeMem(ptr: Pointer; _abstract: PPointer); cdecl;
begin
  FreeMemory(ptr);
end;
function sshReallocMem(ptr: Pointer; count: UINT; _abstract: PPointer): Pointer; cdecl;
begin
  Result := ReallocMemory(ptr, count);
end;

begin
  // using delphi memory manager
  FSession := libssh2_session_init_ex(sshAllocMem, sshFreeMem, sshReallocMem, nil);
```
If server use ed25519, i get error *Invalid address specified to RtlFreeHeap* on `libssh2_session_free()`.
Because, As I understand , memory's allocated by delphi, but freed by openssl

Alloc:
https://github.com/libssh2/libssh2/blob/5c805e23ea980c3628923c59ea284d7985242009/src/hostkey.c#L831
Free:
https://github.com/libssh2/libssh2/blob/5c805e23ea980c3628923c59ea284d7985242009/src/hostkey.c#L968
https://github.com/libssh2/libssh2/blob/5c805e23ea980c3628923c59ea284d7985242009/src/openssl.h#L328-L334

**Comment by willco007** [comment]
Should be fixed with commit #53aba03, thanks for the report.
