### ISSUE TITLE
Yet another discrepancy malloc + LIBSSH2_FREE

### ISSUE THREAD

**Issue by dimmaq** [libssh2/libssh2#296]
Look `_libssh2_curve25519_new()`

Alloc:
https://github.com/libssh2/libssh2/blob/b45333b2b6fe2e207176d9d93fb1f3966a4e68b9/src/openssl.c#L1512
https://github.com/libssh2/libssh2/blob/b45333b2b6fe2e207176d9d93fb1f3966a4e68b9/src/openssl.c#L1504
Free:
https://github.com/libssh2/libssh2/blob/b45333b2b6fe2e207176d9d93fb1f3966a4e68b9/src/kex.c#L3058
https://github.com/libssh2/libssh2/blob/b45333b2b6fe2e207176d9d93fb1f3966a4e68b9/src/kex.c#L3064

**Comment by willco007** [comment]
Added session arg to '_libssh2_curve25519_new()' and '_libssh2_ecdsa_create_key()' so they can use 'LIBSSH2_ALLOC()' when allocating variables which are then freed in 'kex.c' using 'LIBSSH2_FREE()' to keep 'free()' out of shared code. Thanks again for these reports!

**Comment by willco007** [comment]
Fixed with f7dd7d1, thanks again.
