### ISSUE TITLE
Compile on IBM i (AS400) failed

### ISSUE THREAD

**Issue by jindrichhron** [libssh2/libssh2#298]
Hello,
I am trying to compile last version of libssh2 on AS400, but compile of every module fails with error:
CZM1003:  /libssh2-master/src/libssh2_priv.h, 278.5: CZM0046(30) Syntax error.

**Comment by willco007** [comment]
Which backend are you building with?

**Comment by jindrichhron** [comment]
If you mean version of i5/OS, so it is version V7R3M0.

Regards,
   Jindřich Hron

Dne pá 22. úno 2019 18:49 uživatel Will Cosgrove <notifications@github.com>
napsal:

**Comment by willco007** [comment]
Sorry, I wasn't clear. Which crypto backend are you using; e.g. OpenSSL, libgcrypt, wincng, etc. And what version.

**Comment by jindrichhron** [comment]
I am using Openssl version 1.0.2o.


Dne pá 22. úno 2019 22:44 uživatel Will Cosgrove <notifications@github.com>
napsal:

**Comment by willco007** [comment]
If you change line 75 in `openssl.h` from `#ifdef OPENSSL_NO_ECDSA` to `#ifdef OPENSSL_NO_EC` does that fix your build issue?

**Comment by jindrichhron** [comment]
Hi Will,

unfortunately this change doesn't help.

Here is the whole log from compilation in attachment.

Regards,
   Jindřich Hron


pá 22. 2. 2019 v 23:34 odesílatel Will Cosgrove <notifications@github.com>
napsal:

**Comment by willco007** [comment]
It looks like EC_KEY type isn't defined but it should be when compiling against 1.0.2. Make sure your header and library search paths are set up correctly and something isn't pointing at an older version of OpenSSL.
