### ISSUE TITLE
Memory leak  in `libssh2_session_handshake()`

### ISSUE THREAD

**Issue by dimmaq** [libssh2/libssh2#299]
In my case, if set little timeout `libssh2_session_set_timeout(session, 5000)` then `libssh2_session_handshake()` failed with last error **(-9) API timeout expired** and have memory leak

`diffie_hellman_sha1()`
allocated
https://github.com/libssh2/libssh2/blob/f7dd7d1d434d73baa44a1e560232df9196aa2dd7/src/kex.c#L165-L166

return without freeing
https://github.com/libssh2/libssh2/blob/f7dd7d1d434d73baa44a1e560232df9196aa2dd7/src/kex.c#L234-L242

tested on example ssh2.c
```
libssh2_session_set_timeout(session, 5000)
    if (libssh2_session_handshake(session, sock)) {
		char *errmsg;
		int errlen;
		int err = libssh2_session_last_error(session, &errmsg, &errlen, 0);
		fprintf(stderr, "Unable to open a session: (%d) %s\n", err, errmsg);
        fprintf(stderr, "Failure establishing SSH session\n");
		system("pause");
        return -1;
    }
```

**Comment by tiennou** [comment]
I've been toying at this one, and I caught another related leak. Sadly I forgot to grab the actual leakstack (a leak of the negotiated ecdsa key IIRC, starting under `session->kex->exchange_keys(…);`), but it seems to be the same issue: a timeout in the middle of a session being setup can leak parts of the setup done by `_libssh2_kex_exchange`.

**Comment by doublex** [comment]
@tiennou 
Did you try this provisionally patch?
https://github.com/libssh2/libssh2/pull/357

**Comment by tiennou** [comment]
Yes, and have the same opinion as @willco007: it's not quite the correct fix, and a more complete solution is needed (eg. you're only fixing the issue on timeouts — anything else that can cause the code to bail and never retry is still going to leak). Right now I'm still confused by the async state-machine code, but my gut feeling is that `session_create` needs a counter "destructor" that handles half-negotiated KEXes correctly, so if the code detects a timeout, it can tear down all transient data that would be overwritten on a retry. And the async wrapper macro (`BLOCK_ADJUST`?) need to take that destructor.

It sounds complex 😉.

**Comment by doorsdown** [comment]
I tend to agree that my patch is very narrowly focused and a more complete fix would be best but @tiennou said, its complex.
