### ISSUE TITLE
Add --fix-up-the-mess to fix up Offending key warnings for the user in one quick step!

### ISSUE THREAD

**Issue by jidanni** [libssh2/libssh2#300]
We are all familiar with the old routine,

```
$ ssh ...
Warning: the ECDSA host key for 'ssh.example.org' differs from the key for the IP address '164.190.144.253'
Offending key for IP in /home/jidanni/.ssh/known_hosts:20
Matching host key in /home/jidanni/.ssh/known_hosts:30

$ ed  /home/jidanni/.ssh/known_hosts
11098
20d
w
10656
q

$ ssh ...
Warning: Permanently added the ECDSA host key for IP address '64.90.44.253' to the list of known hosts.
```

Well I have a new idea!

At the end of the initial warning just add
"... or if you are really sure, just use --fix-up-the-mess to fix up the mess"
and then all the user would need to do is one
$ ssh --fix-up-the-mess ...
and voila, the mess is all fixed up! Even no one-time "Permanently added..." message!

(Of course please choose a better name than --fix-up-the-mess.) Thanks!

**Comment by jidanni** [comment]
Yes, I hope --fix-up-the-mess would:
1. do the ed(1) step for the user.
2. do the second run or whatever to Permanently add that line.

Thanks!

**Comment by bagder** [comment]
You seem to be talking about the ssh tool (from openssh?) that isn't related to this project!

**Comment by jidanni** [comment]
OK, created https://bugzilla.mindrot.org/show_bug.cgi?id=2983 .
