### ISSUE TITLE
_libssh2_openssl_crypto_init() fails on Libressl

### ISSUE THREAD

**Issue by jeremyhu** [libssh2/libssh2#302]
_libssh2_openssl_crypto_init() goes down an OpenSSL > 1.1.0 codepath when using Libressl because Libressl defines OPENSSL_VERSION_NUMBER as 0x20000000L, but it should go down the other codepath.

Please use:

    #if (OPENSSL_VERSION_NUMBER >= 0x10100000L && !defined(LIBSSH2_LIBRESSL))

**Comment by willco007** [comment]
Should be fixed with 3c2ff8a.

**Comment by kulkarniamit** [comment]
> Should be fixed with 3c2ff8a.

Minor typo : Fixed with 3c1ff8a

**Comment by jeremyhu** [comment]
Yep, thanks.
