### ISSUE TITLE
connection ssh server with parameters

### ISSUE THREAD

**Issue by 0611wl** [libssh2/libssh2#306]
How to connect to the ssh server with parameters, for example: "ssh admin@192.168.0.1 -p 830 -E logFile
-F configFile"

**Comment by willco007** [comment]
Please look at the example project `ssh2` to see how to connect to servers. `libssh2_trace_sethandler` is used to implement logging. Lastly, SSH configuration files aren't natively supported so you'll need to parse the ssh config file manually if you'd like to use the parameters specified there.

**Comment by 0611wl** [comment]
This is just an example. Our NetConf server uses a custom login command(ssh admin@127.0.0.1 -p 830 -s netconf), so the normal login method is not supported. I need to modify the login command. Can I do this? Thank you
