### ISSUE TITLE
bad defines in public header!

### ISSUE THREAD

**Issue by bagder** [libssh2/libssh2#319]
@willco007,

In commit dc109a7f518757 you introduced two defines in`include/libssh2.h` that are outside the libssh2 name space and clearly risk colliding with other headers:

https://github.com/libssh2/libssh2/blob/10098f9d4efc5d9e60164a362910ad7ecd03a03d/include/libssh2.h#L157-L167

If they need to be publicly defined - do they? - then I would suggest they get the proper prefix `LIBSSH2_`.

**Comment by willco007** [comment]
We did this out of a desire to support legacy build systems which may not define these types natively (old Windows). All modern standard libraries support these types so this code _may_ not be needed at all. Thoughts?

**Comment by bagder** [comment]
Sure, but why would they need to be in the public header? Surely applications can do those for themselves and we can do private ones for internal use?

**Comment by willco007** [comment]
Good point; we'll move it into the private header.  There are other types defined in the public header which would also be candidates to move into the private header.

**Comment by bagder** [comment]
> candidates to move

Agreed. I just figured that those who already are there are known by now and we've learned to live with them, but you're right, we should limit what we throw onto the world outside.

**Comment by willco007** [comment]
#256

**Comment by willco007** [comment]
Max sizes are moved with PR #317.
