### ISSUE TITLE
1.8.1: test suiite is failing

### ISSUE THREAD

**Issue by kloczek** [libssh2/libssh2#325]
<pre>+ /usr/bin/make -O -j4 -C tests check
/usr/bin/make  simple
make[1]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/libssh2-1.8.1/tests&apos;
gcc -DHAVE_CONFIG_H -I. -I../src -I../example  -I../src -I../include -I../src   -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto -c -o simple.o simple.c
make[1]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/libssh2-1.8.1/tests&apos;
make[1]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/libssh2-1.8.1/tests&apos;
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto  -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto -fuse-linker-plugin -o simple simple.o ../src/libssh2.la 
libtool: link: gcc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto -Wl,-z -Wl,relro -Wl,--as-needed -Wl,-z -Wl,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto -fuse-linker-plugin -o .libs/simple simple.o  ../src/.libs/libssh2.so -L/usr/lib64 -lssl -lcrypto -lz
make[1]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/libssh2-1.8.1/tests&apos;
/usr/bin/make  check-TESTS
make[2]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/libssh2-1.8.1/tests&apos;
PASS: simple
make[2]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/libssh2-1.8.1/tests&apos;
make[2]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/libssh2-1.8.1/tests&apos;
FAIL: ssh2.sh
make[2]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/libssh2-1.8.1/tests&apos;
make[2]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/libssh2-1.8.1/tests&apos;
PASS: mansyntax.sh
make[2]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/libssh2-1.8.1/tests&apos;
make[2]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/libssh2-1.8.1/tests&apos;
============================================================================
Testsuite summary for libssh2 -
============================================================================
# TOTAL: 3
# PASS:  2
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See tests/test-suite.log
Please report to libssh2-devel@cool.haxx.se
============================================================================
make[2]: *** [Makefile:730: test-suite.log] Error 1
</pre>
Content of the test-suite.log
<pre>=====================================
   libssh2 -: tests/test-suite.log
=====================================

# TOTAL: 3
# PASS:  2
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: ssh2.sh
=============

command-line line 0: Deprecated option UsePrivilegeSeparation
command-line line 0: Deprecated option UsePrivilegeSeparation
Fingerprint: 86 AD B2 21 33 60 65 3D 9A 29 86 DE 22 99 DA 18 CC BA D3 AC 
Authentication methods: publickey,password,keyboard-interactive
	Authentication by public key failed!
FAIL ssh2.sh (exit status: 1)
</pre>

**Comment by willco007** [comment]
fixed with #327.
