### ISSUE TITLE
Uploaded release tarballs missing CMake build system

### ISSUE THREAD

**Issue by havoc-io** [libssh2/libssh2#34]
For some reason the [manually-uploaded release tarball](https://github.com/libssh2/libssh2/releases/download/libssh2-1.6.0/libssh2-1.6.0.tar.gz) doesn't contain the CMake build system advertised in version 1.6.0.

The auto-generated snapshots accompanying the release do contain the CMake files, so it's not really a show stopper, but I was wondering if there were more substantial differences between these archives to be aware of?

**Comment by bagder** [comment]
The cmake files are not added to the release tarballs because they're missing in Makefile.am which is what creates the contents... I'll appreciate a patch!

**Comment by kdudka** [comment]
@bagder I believe this is already fixed but there has been no release since then: d48d7c3a

**Comment by bagder** [comment]
oh yes, sorry, was looking in an older Makefile.am, thanks @kdudka !

**Comment by havoc-io** [comment]
Oh, cheers.  Sorry for the noise then.
