### ISSUE TITLE
Quoting path breaks ~ expansion on some servers

### ISSUE THREAD

**Issue by gnachman** [libssh2/libssh2#349]
**Describe the bug**
I received a bug report that my app using libssh2 failed to scp files that openssh's scp is able to fetch. The difference is in how the path is quoted. I'm not sure if this is a bug (since there is no spec for scp AFAIK) but it would be nice to be compatible with openssh.

**To Reproduce**
Download a file with a path including a tilde using the built-in scp server on macOS.

**Expected behavior**
The download should succeed.

**Version (please complete the following information):**
 - OS: macOS 10.14
 - libssh2 version 1.8.0

**Additional context**
Here's a log snippet showing the quoting:

https://gist.github.com/gnachman/352da57d455cb0943f5e06607511bda8

The relevant line is
```
[libssh2] 1.110646 Conn: starting request(exec) on channel 0/0, message=scp -f '~/test.txt'
```

I built a modified version of libssh2 that does not use the single quotes and the download succeeded. OpenSSH does not use single quotes. The tradeoff seems to be that OpenSSH requires extra backslashes to escape whitespace. It seems to me the best behavior would be to omit the quotes and add backslash escaping as needed so you could get tilde expansion as well as properly interpreted whitespace.

**Comment by willco007** [comment]
Seems reasonable, could you submit a PR with your fix?

**Comment by willco007** [comment]
Not stale, anyone testing this care to comment?
