### ISSUE TITLE
libssh2_channel_direct_tcpip_ex: Channel open failure (connect failed)

### ISSUE THREAD

**Issue by wolverin-a** [libssh2/libssh2#351]
When I try to create a channel as
`channel = libssh2_channel_direct_tcpip_ex(session, host_ip, host_port, listen_host, listen_port)`

on some servers, all work, the other falls with an error
> Channel open failure (connect failed)

on servers everywhere Debian 8, in a log
> sshd[]: error: connect_to host_ip port host_port: failed

the only difference is that on servers where there is no forwarding of port there are incoming routers, BUT the client
`ssh -f -N -L listen_port:localhost:host_port host_ip`
forwarding the port with no problems, while authentication in the libssh2 is, the various parameters to tunel in sshd_config do not solve the problem
> AllowAgentForwarding yes
> AllowTcpForwarding yes
> GatewayPorts yes
> PermitTunnel yes
> PermitOpen any

 - OS: Debian 8
 - libssh2 version 1.8.2

**Comment by wolverin-a** [comment]
my debug
`
[libssh2] 0.400282 Conn: Requesting direct-tcpip session to from .... to ....
[libssh2] 0.400346 Conn: Allocated new channel ID#0
[libssh2] 0.400362 Conn: Opening Channel - win 2097152 pack 32768
=> libssh2_transport_write plain (29 bytes)
0000: 5A 00 00 00 0C 64 69 72  65 63 74 2D 74 63 70 69 : Z....direct-tcpi
0010: 70 00 00 00 00 00 20 00  00 00 00 80 00          : p..... ......
=> libssh2_transport_write plain2 (37 bytes)
0000: 
0010: 
0020: 
[libssh2] 0.400489 Socket: Sent 112/112 bytes at 0x1a92ae0
=> libssh2_transport_write send() (112 bytes)
0000: 72 7B C6 25 8A BA 6D EE  C4 8B 5F 8A 66 06 05 40 : r{.%..m..._.f..@
0010: 2C A8 C3 9B F0 0B A8 62  B3 EB 82 9F FD A1 9A 1C : ,......b........
0020: 23 16 CE 65 03 68 D5 B5  12 32 64 AA 57 1A 99 85 : #..e.h...2d.W...
0030: 64 BB 5C 27 0D E6 55 D3  C0 6B 3C B7 AA F8 AE 7A : d.\'..U..k<....z
0040: ED A6 67 98 23 0B 97 03  53 8F 64 B7 B3 EA 6B D0 : ..g.#...S.d...k.
0050: CA 93 1E E5 E3 8A D3 42  F0 CE A3 8B 49 9A 80 CF : .......B....I...
0060: 40 B1 98 EE 28 A6 C9 9F  38 2D 3C 43 CA FB CE 29 : @...(...8-<C...)
[libssh2] 0.400583 Transport: Looking for packet of type: 91
[libssh2] 0.400593 Transport: Looking for packet of type: 92
[libssh2] 0.400606 Failure Event: -37 - Would block
[libssh2] 0.448730 Transport: Looking for packet of type: 91
[libssh2] 0.448754 Transport: Looking for packet of type: 92
[libssh2] 0.448770 Socket: Recved 80/16384 bytes to 0x1a8eaa0+0
=> libssh2_transport_read() raw (80 bytes)
0000: 06 58 6C 3F D1 16 E4 8C  48 A7 A0 41 F2 5B DA 24 : .Xl?....H..A.[.$
0010: CE 96 02 83 AC C3 FE EE  C5 28 B0 29 F2 6B 41 BF : .........(.).kA.
0020: 44 4D C6 6D 0F 7B 52 A4  57 13 08 15 1A 61 15 5A : DM.m.{R.W....a.Z
0030: 3C 59 BD FB 87 6F 68 82  4A 74 03 A2 F5 19 57 33 : <Y...oh.Jt....W3
0040: BB 49 CF BE 91 E9 38 13  E7 DB 2F 5D 29 09 3B DF : .I....8.../]).;.
=> libssh2_transport_read() plain (35 bytes)
0000: 5C 00 00 00 00 00 00 00  02 00 00 00 12 43 6F 6E : \............Con
0010: 6E 65 63 74 69 6F 6E 20  72 65 66 75 73 65 64 00 : nection refused.
0020: 00 00 00                                         : ...
[libssh2] 0.448892 Transport: Packet type 92 received, length=35
[libssh2] 0.448908 Transport: Looking for packet of type: 91
[libssh2] 0.448917 Transport: Looking for packet of type: 92
[libssh2] 0.448927 Failure Event: -21 - Channel open failure (connect failed)
[libssh2] 0.448937 Transport: Looking for packet of type: 94
[libssh2] 0.448946 Transport: Looking for packet of type: 95
Client disconnecting before port forwarding, libssh2: 1.8.2 RC: -1 Channel open failure (connect failed)
[libssh2] 0.449050 Transport: Disconnecting: reason=11, desc=Client disconnecting before port forwarding, libssh2: 1.8.2, lang=
=> libssh2_transport_write plain (72 bytes)
0000: 01 00 00 00 0B 00 00 00  3B 43 6C 69 65 6E 74 20 : ........;Client
0010: 64 69 73 63 6F 6E 6E 65  63 74 69 6E 67 20 62 65 : disconnecting be
0020: 66 6F 72 65 20 70 6F 72  74 20 66 6F 72 77 61 72 : fore port forwar
0030: 64 69 6E 67 2C 20 6C 69  62 73 73 68 32 3A 20 31 : ding, libssh2: 1
0040: 2E 38 2E 32 00 00 00 00                          : .8.2....
=> libssh2_transport_write plain2 (0 bytes)
[libssh2] 0.449199 Socket: Sent 128/128 bytes at 0x1a92ae0
=> libssh2_transport_write send() (128 bytes)
0000: C6 9C 6B 56 0B AB 18 44  3E BC 45 5A 3B 45 3A 1E : ..kV...D>.EZ;E:.
0010: 19 C3 97 45 91 47 A3 47  B5 A9 D0 58 D6 DB 7F 80 : ...E.G.G...X....
0020: C8 EA 57 44 6D 81 5D DB  F0 98 27 9C 2E A9 39 9F : ..WDm.]...'...9.
0030: BB 08 A6 22 6A 36 AB DC  2D 29 64 FA BE 1A D8 A9 : ..."j6..-)d.....
0040: A9 D8 DC 30 97 97 58 9B  E8 DF 76 64 A1 77 59 18 : ...0..X...vd.wY.
0050: DF E4 E5 F0 F0 85 C1 DC  F7 7D ED 23 2F BF 61 3C : .........}.#/.a<
0060: F0 4D 12 7C 34 1C 7E A2  A5 27 54 A0 00 FF 20 D5 : .M.|4.~..'T... .
0070: 64 0A BB 94 11 D6 0D E2  8B 49 B2 F5 44 B9 48 79 : d........I..D.Hy
[libssh2] 0.449299 Transport: Freeing session resource
[libssh2] 0.449323 Transport: Extra packets left 0
`

**Comment by wolverin-a** [comment]
part of the debug
`[libssh2] 0.400583 Transport: Looking for packet of type: 91
[libssh2] 0.400593 Transport: Looking for packet of type: 92
[libssh2] 0.400606 Failure Event: -37 - Would block
[libssh2] 0.448730 Transport: Looking for packet of type: 91
[libssh2] 0.448754 Transport: Looking for packet of type: 92
[libssh2] 0.448770 Socket: Recved 80/16384 bytes to 0x1a8eaa0+0
`

**Comment by wolverin-a** [comment]
the project died?

**Comment by bagder** [comment]
It's not quite dead yet, but there's basically no people around doing any work here.

**Comment by wolverin-a** [comment]
My bug )
> `channel = libssh2_channel_direct_tcpip_ex(session, host_ip, host_port, listen_host, listen_port)`
correctly
> `channel = libssh2_channel_direct_tcpip_ex(session, listen_host, host_port, listen_host, listen_port)`
listen_host = localhost
