### ISSUE TITLE
Key passphrase problem again

### ISSUE THREAD

**Issue by kaztost** [libssh2/libssh2#352]
Why you closed this issue before the release.
https://github.com/libssh2/libssh2/issues/68#issuecomment-443459800

I had this problem with the realease build 1.8.0 and still have it with the current 1.8.2. The problem is solved in snapshots 1.8.1-DEV and 1.9.0-DEV.

The snapshots code have extra files blf.h, blowfish.c etc... Why they do not go to releases? I guess the problem is there.

**Comment by bagder** [comment]
because the 1.8.1 and 1.8.2 releases were branch off from 1.8.0, thus based on much older code from before those source files were added

**Comment by willco007** [comment]
This will be included in the 1.9 feature release which is based on master; 1.8.x releases are bug fix only releases.
