### ISSUE TITLE
 LIBSSH2_VERSION  states it's version 1.7   on 1.8 branch/builds

### ISSUE THREAD

**Issue by musm** [libssh2/libssh2#353]
https://github.com/libssh2/libssh2/blob/1.8.x/include/libssh2.h#L49

**Comment by kdudka** [comment]
This was previously reported on the libssh2-devel mailing list:

https://www.libssh2.org/mail/libssh2-devel-archive-2018-11/0000.shtml

**Comment by bagder** [comment]
Releases are *generated* into tarballs and then released. The releases have the files correct.
