### ISSUE TITLE
Configure: libgcrypt is enabled with --without-libgcrypt configure option

### ISSUE THREAD

**Issue by PTamis** [libssh2/libssh2#354]
**Describe the bug**
I am using yocto recipes to configure libssh2.
Yocto is executing the following configuration:

`../libssh2-1.8.2/configure  --build=x86_64-linux            --host=powerpc-atos-linux-gnuspe                --target=powerpc-atos-linux-gnuspe              --prefix=/usr                   --exec_prefix=/usr              --bindir=/usr/bin               --sbindir=/usr/sbin             --libexecdir=/usr/libexec               --datadir=/usr/share            --sysconfdir=/etc               --sharedstatedir=/com                   --localstatedir=/var            --libdir=/usr/lib               --includedir=/usr/include               --oldincludedir=/usr/include            --infodir=/usr/share/info               --mandir=/usr/share/man                 --disable-silent-rules                  --disable-dependency-tracking                   --with-libtool-sysroot=/home/tamis/build_oe/tmp/sysroots/qoriq                   --with-libz                  --with-libz-prefix=/home/tamis/build_oe/tmp/sysroots/qoriq/usr/lib                  --disable-static  --without-libgcrypt --with-openssl --with-libssl-prefix=/home/tamis/build_oe/tmp/sysroots/qoriq/usr/lib`

In configure the --without-libgcrypt is used explicitly.
But at the end:
...
checking for libgcrypt... yes
checking how to link with libgcrypt... -lgcrypt
...

Crypto library:   libgcrypt

Openssl is also available but it is not selected!

**To Reproduce**
If you configure libssh2 with --without-libgcrypt --with-openssl then libgcrypt is selected

If you configure libssh2 with --with-openssl then correct libopenssl is selected

**Expected behavior**
when I use --without-libgcrypt this should be respected by the configure.

**Version (please complete the following information):**
 - OS: [linux Ubuntu 16.04]
 - libssh2 version tested 1.8.0 and 1.8.2

**Additional context**
Tested with 1.7.0 version the exact same configuration and it works fine.
--without-libgcrypt --with-openssl
selects Openssl

Crypto library:   OpenSSL (AES-CTR: yes)

**Comment by doorsdown** [comment]
So I was looking at the configure script and noticed that --without-libgcrypt is not a valid option but --without-libgcrypt-prefix is. That being said I downloaded a fresh copy of 1.8.2 and tried to reproduce your result and was not able to.

>$ ./configure --without-libgcrypt --with-openssl 2>&1 |grep "Crypto library"
  Crypto library:   OpenSSL (AES-CTR: yes)
$ ./configure --with-openssl 2>&1 |grep "Crypto library"
  Crypto library:   OpenSSL (AES-CTR: yes)

**Comment by PTamis** [comment]
`--without-libgcrypt` is the option used by the yocto libssh2 bb file in order to disable the libgcrypt library. It comes from the PACKAGECONFIG configuration.
This might need to be corrected also. In newer yocto releases sysroot is per recipe and build system does not populate libraries not required. So libssh2 is configured correctly eg sumo branch.

But in older releases (morty branch) sysroot is common for all recipes so multiple libraries might exist there.

That being said, I also simplified your test in an x86_64 machine Ubuntu 18.04.
Installed packages for reproduction:
sudo apt install libssl-dev libgcrypt11-dev

Both libraries have to exist, libgcrypt along with openssl.

Tested version libssh2: 1.8.2

>./configure --without-libgcrypt --with-openssl 2>&1 | grep "Crypto library"
>Crypto library:   libgcrypt
>./configure --with-openssl 2>&1 | grep "Crypto library"
> Crypto library:   OpenSSL (AES-CTR: yes)

**Comment by doorsdown** [comment]
Okay I have confirmed the issue now, my issue before was not having libgcrypt-devel package installed on my centos box. I'll go from here to see what is needed to fix the configure script to behave

**Comment by doorsdown** [comment]
I'm not sure what change fixed this glitch but the current master branch shows this as being fixed and should be resolved for you when 1.9.0 is release in the near future.

>  libssh2-1.8.2]$ ./configure --without-libgcrypt --with-openssl 2>&1 | grep "Crypto library"
  Crypto library:   libgcrypt
libssh2-1.8.2]$ ./configure --with-openssl 2>&1 | grep "Crypto library"
  Crypto library:   OpenSSL (AES-CTR: yes)
libssh2-1.9.0_DEV]$ ./configure --without-libgcrypt --with-openssl 2>&1 | grep "Crypto library"
  Crypto library:   OpenSSL (AES-CTR: yes)
libssh2-1.9.0_DEV]$ ./configure --with-openssl 2>&1 | grep "Crypto library"
  Crypto library:   OpenSSL (AES-CTR: yes)
