### ISSUE TITLE
Plan for Release That Works with OpenSSL with No Engine Support

### ISSUE THREAD

**Issue by DavidRusso** [libssh2/libssh2#355]
This is not an issue, just a question. On the platform I'm working on (IBM i PASE), the latest version of OpenSSL is built w/o engine support. The current libssh2 release 1.8.2 doesn't work when OpenSSL doesn't have engine support. I see that this has been fixed and merged into 'master' already. I'm wondering if there is a plan to incorporate this fix into a release sometime soon, and if it's possible to get an idea when it might be released?

**Comment by doorsdown** [comment]
A version 1.9.0 is/has been discussed on the mailing list and the hope was to have it out last Thursday the 11th but that clearly has not happened. I would say it close to happening just taking some time due to low amount of time people have to contribute to finalizing the release.

**Comment by DavidRusso** [comment]
Thanks for your response. I'll keep an eye out for 1.9.0.
