### ISSUE TITLE
fails: SFTP with 1GB files on Windows using Tectia Server

### ISSUE THREAD

**Issue by ivankitov** [libssh2/libssh2#37]
We recently having a problem with uploading a large file (around 1 GB)  to Tectia Server using a libssh2 client. The file transfer is hanging,  expecting few bytes which never arrives in the client side. We strongly believe this issue is due to a protocol mismatch between the client and the server. Going through the logs,  we found that libsh2 client is expecting a packet type 101  and while the server is keep on sending  packet type 200.

**Comment by alamaison** [comment]
We need to see the libssh2 debug log output to be able to debug this.

**Comment by bagder** [comment]
No response.
