### ISSUE TITLE
libssh2 1.8.2 LIBSSH2_HOSTKEY_HASH_SHA256

### ISSUE THREAD

**Issue by jmbents** [libssh2/libssh2#376]
**Describe the bug**
`LIBSSH2_HOSTKEY_HASH_SHA256` appears to be missing in version 1.8.2 and the 1.8.x branch but is still available on master

Is there a reason it was not included in 1.8.2?  It was previously available for use before jumping to 1.8.2.

**Expected behavior**
To be able to use `LIBSSH2_HOSTKEY_HASH_SHA256`

**Version (please complete the following information):**
 - libssh2 version 1.8.2

**Comment by willco007** [comment]
1.8.2 was a bug fix release only on the 1.8 release, master is the feature release branch.
