### ISSUE TITLE
ssh2_exec .c example code does not work in libssh2 1.8.2

### ISSUE THREAD

**Issue by NallasivanK** [libssh2/libssh2#377]
I tried to execute ssh command through libssh2_channel_exec API , but i am not able to read the response through libssh2_channel_read API. even  ssh2_exec .c example code does not work in libssh2 1.8.2. please let me if there is any issue or i am wrong.

**Comment by willco007** [comment]
Have you tried the latest master branch code? `ssh2_exec` example app works here in master.
