### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION in module libssh2.dll at 000000008000C180, _libssh2_ntohu32

### ISSUE THREAD

**Issue by muton85** [libssh2/libssh2#378]
***.exe caused an EXCEPTION_ACCESS_VIOLATION in module libssh2.dll at 000000008000C180, _libssh2_ntohu32 , ***\libssh2\src\misc.c, line 0186

Stack:
0x000000018000C180(0x00000007498103B0 0x00000000000001B7 0x0000000705D5FE00 0x00000006CE5EA5D0) libssh2.dll, _libssh2_ntohu32, ***\libssh2\src\misc.c, line 0186
0x000000018000575E(0x0000000705D53120 0x0000000000000000 0x00000006CE5EA5D0 0x0000000705D5FE00) libssh2.dll, hostkey_method_ssh_dss_init()+00000190 byte(s), ***\libssh2\src\hostkey.c, line 0328
0x000000018000696E(0x0000000705D5FDE8 0x0000000705D5FDD0 0x0000000705D53120 0x0000000710690428) libssh2.dll, diffie_hellman_sha1()+00000974 byte(s), ***\libssh2\src\kex.c, line 0316+00000037 byte(s)
0x0000000180005DA8(0x0000000705D53120 0x00000000000000DE 0x0000000705D5FDD0 0x000000071069043E) libssh2.dll, kex_method_diffie_hellman_group1_sha1_key_exchange()+00000152 byte(s), ***\libssh2\src\kex.c, line 1378+00000064 byte(s)
0x0000000180006529(0x0000000000000000 0x0000000705D53120 0x00000000073F5324 0x0000000000000000) libssh2.dll, _libssh2_kex_exchange()+00000473 byte(s), ***\libssh2\src\kex.c, line 2539
0x0000000180013AA4(0x01D52618A7F64562 0x0000000705D53120 0x0000000705D53120 0x00000000073F5324) libssh2.dll, session_startup()+00000292 byte(s), ***\libssh2\src\session.c, line 0711
0x0000000180012F7B(0x000000000000003B 0x000000000455E330 0x000000000455E330 0x0000000000000000) libssh2.dll, libssh2_session_handshake()+00000043 byte(s), ***\libssh2\src\session.c, line 0788+00000020 byte(s)

Os Windows 10, 64 bit
libssh latests vesion, 64 bit build.

Seems the problem that libssh2 doesn't check array bounary

**Comment by tiennou** [comment]
Can you provide the actual version/commit hash, for clarity? Your line numbers don't match what's in `master` (and if you can check `master` itself, that would also help: there has been many changes around those bound checks).

I'd be interested to know if #369 fixes it — it's supposed to error out if the crypto layer initialization fails, and this looks like the `hostkey_data` has been freed, or somehow not large enough. Not sure that's what you're seeing though, so YMMV.

**Comment by willco007** [comment]
As @tiennou notes, this isn't the latest release, 1.9.0, which I believe resolves this issue already. Could you check this issue on the 1.9 codebase? Thanks!

**Comment by bencoman** [comment]
@muton85  Can you advise you Windows version? i.e....   C:\> ver
