### ISSUE TITLE
SSH Forward Agent getting -39 on libssh2_agent_connect function.

### ISSUE THREAD

**Issue by ios3Dev** [libssh2/libssh2#38]
I am trying in mobile application to agent forward same like this way in link. http://www.libssh2.org/examples/ssh2_agent.html

I am getting agent too with this 
agent = libssh2_agent_init(session)

But when I go on next statement 
libssh2_agent_connect(agent), I am getting here error -39 (LIBSSH2_ERROR_BAD_USE).

I am trying on Mac Osx machine, I checked in mac terminal there is agent anf identity too with that agent.

Can any one suggest me that is there any issue in code or there can be issue with agent forward settings?

Thanks

**Comment by ios3Dev** [comment]
can any one reply please?

**Comment by salva** [comment]
check if the return value of libssh2_agent_init is valid.

**Comment by ios3Dev** [comment]
Thanks for reply.
Yes, It's valid value. I mean getting proper address for that. But getting issue in connect libssh2_agent_connect(agent)

**Comment by salva** [comment]
Then write a proper bug report including your source code, the expected behavior and what you are getting instead. The output of running the test program with libssh2 debugging enabled would also help.

**Comment by ios3Dev** [comment]
okay sure I will. can you guide me how to enable debugging? Should I create new build of libssh2? 

In my libssh2.h file there is statement like
 /* NOTE NOTE NOTE
     libssh2_trace() has no function in builds that aren't built with debug
     enabled
     */

Can you please guide me how can I?

**Comment by salva** [comment]
Yes. `configure` has an option to enable it. Just run `./configure --help` and you will find.

IIRC, you will have to perform a `make clean` before too, in order to get everything recompiled.

**Comment by salva** [comment]
Looking at the source, it seems that the bad usage error indicates that the environment variable `SSH_AUTH_SOCK` is not set.
