### ISSUE TITLE
Failed SCP transfer reported as success with Solarwinds SCP/SFTP Server

### ISSUE THREAD

**Issue by lsabouri74** [libssh2/libssh2#382]
**Describe the bug**
I am using example scp_write.exe to upload a file to Solarwinds SCP/SFTP Server, and the sample reports a success but file is not uploaded. I can upload with success with native scp clients on Windows and Linux.

**To Reproduce**
1. Install Solarwinds SCP/SFTP Server (free for testing)
2. upload a file using scp_write.exe example

**Expected behavior**
I would expect a successful upload or at least a report of failure if the upload failed if for some reason the SCP server has issues.

**Version:**
 - OS: Windows 10 Enterprise 1903 10.0.18362.175 Client
 - libssh2 version 1.9.0

**Additional context**
I noticed this issue by using curl, and tried with libssh2 example and found out the issue is still happening with just libssh2 and curl out of the picture.

**Comment by rajeshwaran** [comment]
We are also facing the same issue. Please update the thread if a fix has been published for the same.

**Comment by willco007** [comment]
We'll take PRs on this issue.

**Comment by rajeshwaran** [comment]
Can we reopen this issue and update if any fix available?

**Comment by willco007** [comment]
@rajeshwaran This issue is closed due to inactivity. If there is no interest in fixing the bug the issue will be closed automatically. Unfortunately there appears to be little interest in fixing SCP bugs in the community.
