### ISSUE TITLE
Potential typecast error for `_libssh2_ecdsa_key_get_curve_type`

### ISSUE THREAD

**Issue by katzer** [libssh2/libssh2#383]
**Describe the bug**

There's a potential typecast error for `_libssh2_ecdsa_key_get_curve_type`.

In [crypto.h](https://github.com/libssh2/libssh2/blob/53ff2e6da450ac1801704b35b3360c9488161342/src/crypto.h#L173) it's defined as follows:

```c
libssh2_curve_type
_libssh2_ecdsa_key_get_curve_type(_libssh2_ec_key *key);
```

And in [hostkey.c](https://github.com/libssh2/libssh2/blob/53ff2e6da450ac1801704b35b3360c9488161342/src/hostkey.c#L712) it's called with the context instead of the key.

```c
_libssh2_ecdsa_key_get_curve_type((libssh2_ecdsa_ctx *) (*abstract));
```

That only works because for [OpenSSL](https://github.com/libssh2/libssh2/blob/53ff2e6da450ac1801704b35b3360c9488161342/src/openssl.h#L312) they are equal:

```c
#define libssh2_ecdsa_ctx EC_KEY
#define _libssh2_ec_key EC_KEY
```

**Expected behavior**

Either change signature to:

```c
libssh2_curve_type
_libssh2_ecdsa_key_get_curve_type(libssh2_ecdsa_ctx *ec_ctx);
```

Or invoke the function with the key and not the context.

**Version**
 - libssh2 1.9.0

**Comment by willco007** [comment]
`_libssh2_ecdsa_key_get_curve_type() ` should take the `libssh2_ecdsa_ctx` which is the private key.  Thanks for the report; if you'd like to submit a PR that'd be great too! :)

**Comment by katzer** [comment]
@willco007 See my PR
