### ISSUE TITLE
Login to ssh server fails using wincng

### ISSUE THREAD

**Issue by steffenb7333** [libssh2/libssh2#388]
**Describe the bug**
Since the May'19 update of Windows (1903) a login to remote SSH servers using WinCNG is not possible anymore. All my servers, running different versions of OpenSSH reject login attempts with:
- Disconnecting: Protocol error: expected packet type 32, got 5 [preauth]

Before the Windows update, there weren't any issues. I confirmed the cause by preparing a fresh Win10 installation (then working) and then applying the update.

**To Reproduce**
Apply may'19 update to existing Windows10 Installation. Use libssh2 with WinCNG. Try login to remote ssh server.

**Expected behavior**
Login to remote ssh server possible. No protocol violation.

**Version (please complete the following information):**
Windows 10, May 2019 update (10.0.18362.207)
libssh2 1.9.0, compiled using VS2019

**Comment by wez** [comment]
I've been tracing through this same problem today; in my case I'm trying to connect from windows to an ubuntu host.  I've traced it to this call failing with NTSTATUS STATUS_UNSUCCESSFUL:

https://github.com/libssh2/libssh2/blob/master/src/wincng.c#L1982

```
    ret = BCryptImportKeyPair(_libssh2_wincng.hAlgRSA, NULL,
                              BCRYPT_RSAPUBLIC_BLOB, &hKey, key, keylen,
                              BCRYPT_NO_KEY_VALIDATION);
```

**Comment by sbredahl** [comment]
It sounds like the same wincng bug has been found in the TotalCommander sftp plugin, specific to the Windows 10 1903 version: According to its author _"The problem is a bug in the Windows function BCryptImportKeyPair: It fails to import an RSA key where the public key exponent is as large as the modulus. It works with a small 3 byte modulus 65537."_  (Have not verified it that is also the case with libssh2 however.)  https://www.ghisler.ch/board/viewtopic.php?t=52563.

**Comment by wez** [comment]
I figured out an alternative solution (#397) that should work on Windows 8.1 and up, although I can only test it on my Windows 10 1903 system.

**Comment by GupTk** [comment]
Hi thanks for your fork.
As my libssh2 1.7.0 is crashing on Windows 1903 and the 1.9.0 is failing ot cannot, I just tried your fork.The other end is an embedded linux (OpenSSH 5.8 - protocol 2.0).

Your fork cannot connect and I get a SSH_MSG_DISCONNECT error with the msg

Protocol error: expected packet type 32, got 5

Any idea?
I do not want to rule out that I am doing something wrong, as I am neiter a Linux nor a SSH specialist.

Thanks

**Comment by wez** [comment]
> Your fork cannot connect and I get a SSH_MSG_DISCONNECT error with the msg
> Protocol error: expected packet type 32, got 5

It sounds like the changes from my fork are not taking effect; the code in my fork will only use the new DH functions if certain symbols are defined, so my guess is that you either are building with mingw/cygwin (which doesn't have those symbols yet), or with an older version of the windows SDK.

**Comment by GupTk** [comment]
Hi Wez,
thanks for your prompt reply. Yes - you were right - using an uptodate SDK gave me a version that works again on Windows 10 (1903 and 1803)
But as your code chooses the API during compile time, I would assume that my binaries will not work on Windows 7 anymore.
(Next week I will grab a Win7 box and verify this).

Thanks again.

**Comment by GupTk** [comment]
Hi Wez,
my assumptions are correct. Your fork works fine on Windows 10 but crashes on Windows 7, as the 
`BCryptDeriveKey(...,BCRYPT_KDF_RAW_SECRET,...)`
fails with error code (0xc00000bb - STATUS_NOT_SUPPORTED).

As you do not evaluate the return code of
`libssh2_dh_secret`
the application crashes in `_libssh2_wincng_bignum_bits`

Thanks

**Comment by wez** [comment]
@GupTk thanks for trying it out!  Do you happen to have a windows 8 or 8.1 machine available to test this on too?  I'm considering adding a windows version check for this to handle it at runtime and I'm wondering if it only works on 10 or later.  The comments in the SDK imply that it should work on 8.1 and later, but some threads on stackoverflow have contradicting information.

**Comment by GupTk** [comment]
Hi Wez,
unfortunately (fortunately?) no one in our office is using 8.1 anymore.
I think it should be safe to switch to new newer API for all versions of Windows 10.
Windows 8.1 should continue to work with the old API, as Windows 10/1803 does.
In my tests the new API works both with 1803 und 1903.
I would not expect, that MS ships a security fix to 8.1 breaking many SSH tools.

Best regards

**Comment by sbredahl** [comment]
Why not just call BCryptDeriveKey(...,BCRYPT_KDF_RAW_SECRET,...) and see if it returns STATUS_NOT_SUPPORTED?

**Comment by GupTk** [comment]
> Why not just call BCryptDeriveKey(...,BCRYPT_KDF_RAW_SECRET,...) and see if it returns STATUS_NOT_SUPPORTED?

The problem is, that a lot of initialisation is performed before you can call the problematic function
So you would have perform all previous steps first and - in case the BCryptDeriveKey fails - rollback everything and go the other way.
For me this seems to be quite complicated.
As I am in a hurry I made a version that just duplicates the DH API.
I am quite sure that this will break the compatibility with other operating systems so this cannot be the final solution.

[workaround.zip](https://github.com/libssh2/libssh2/files/3505116/workaround.zip)

**Comment by wez** [comment]
I've updated my fork to add a runtime check for win10 and later, so this should improve the compatibility situation.

**Comment by sbredahl** [comment]
Thanks! However, `isWindows10OrGreater()` has its own problems. According to https://docs.microsoft.com/en-us/windows/win32/api/versionhelpers/nf-versionhelpers-iswindows10orgreater:  "Applications not manifested for Windows 10 return false, even if the current operating system version is Windows 10". 

This is problematic if the developer forgets (= is not aware) of this manifest issue. An alternative is to use `RtlGetVersion()`(https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-rtlgetversion) which does not return false results. However, it must be manually linked afaik.

**Comment by nojb** [comment]
For the record I think I am experiencing the same issue (curl + libssh2 + WinCNG suddently stopped working, mbedTLS works), but the fork does not seem to solve the problem. I am using libssh2 1.9.0. Any suggestions how to proceed?

**Comment by nojb** [comment]
Just to follow-up, I had made a mistake and the fork actually fixes the issue in my case. Thanks! Are there plans to integrate this?
