### ISSUE TITLE
heap-buffer-overflow in libssh2_userauth_publickey_fromfile_ex

### ISSUE THREAD

**Issue by jeroen** [libssh2/libssh2#390]
This issue has appeared in the context of libgit2 but it looks like it may be a bug in libssh2. See [upstream issue](https://github.com/libgit2/libgit2/issues/5162).

Basically ASAN is reporting a heap-buffer-overflow in libssh2_userauth_publickey_fromfile_ex which seems to appear when reading an ssh pubkey string that does not have an id at the end. Probably somewhere here: 

https://github.com/libssh2/libssh2/blob/1b3cbaff518f32e5b70650d4b7b52361b1410d37/src/userauth.c#L634-L637

A link to a reproducible example and stack trace is here: https://github.com/libgit2/libgit2/issues/5162#issuecomment-511442044

**Comment by willco007** [comment]
I believe this is the same issue as PR #386

**Comment by jeroen** [comment]
Oh yes that looks very similar. Sorry I had not noticed that PR yet.

**Comment by willco007** [comment]
Fixed with PR #386.
