### ISSUE TITLE
cannot build with custom libcrypto.a and libssl.a

### ISSUE THREAD

**Issue by eaigner** [libssh2/libssh2#391]
I can't find a way to build libssh2 with a custom OpenSSL build. I require a specific build and cannot use an installed version. The documentation for these flags is also non existent.

I have 2 archive files from my own OpenSSL build in the current folder under

- `${PWD}/lib/libcrypto.a`
- and `${PWD}/lib/libssl.a`

Now I tried building with regular `make` using 

    ./configure --with-crypto=openssl --with-libssl-prefix="${PWD}/lib"
    make

to no avail. It just doesn't find my own built libs.
`cmake` doesn not recognize those args at all.

**Comment by eaigner** [comment]
Ok, apparently just the 2 libs are not enough. What exactly is required so it detects OpenSSL? Libs + Headers?

**Comment by tiennou** [comment]
Does `cmake` work better by chance (I'm not good at autotools) ?

IIRC on macOS CMake-land, you need something like this to "fix" all underlying variables used by CMake's OpenSSL modules :

```
cmake -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl@1.1/include -DOPENSSL_CRYPTO_LIBRARY=/usr/local/opt/openssl@1.1/lib/libcrypto.dylib -DOPENSSL_SSL_LIBRARY=/usr/local/opt/openssl@1.1/lib/libssl.dylib .
```

YMMV tough, as I haven't tried static builds.

**Comment by eaigner** [comment]
@tiennou I got it to work, I just built the whole thing and pointed `--with-libssl-prefix` at it
