### ISSUE TITLE
libssh2_crypto_exit()

### ISSUE THREAD

**Issue by seba30** [libssh2/libssh2#394]
Hey,

Should [libssh2_crypto_exit()](https://github.com/libssh2/libssh2/blob/482055695011fabb55f3cb7598356d47a0429068/src/global.c#L66) only be called, if _libssh2_initialized equals to zero (like it is handled in the [libssh2_init()](https://github.com/libssh2/libssh2/blob/482055695011fabb55f3cb7598356d47a0429068/src/global.c#L47))?

Best regards,
Sebastian

**Comment by willco007** [comment]
Looking at the code, it seems a possible better fix would be to wrap the `_libssh2_initialized++` in a `if(_libssh2_initialized == 0)` check. There seems to be no need to keep incrementing this value past one.

**Comment by willco007** [comment]
Thinking about it a touch more, it seems like that change could break existing code bases that expect to be able to call init more than once. Testing the value against zero in exit would ensure less breakage.

**Comment by willco007** [comment]
Fixed with PR #396. Thanks for the report!

**Comment by seba30** [comment]
Thank you!
