### ISSUE TITLE
Not able to close hanging session on abrupt cose of remote side

### ISSUE THREAD

**Issue by NallasivanK** [libssh2/libssh2#395]
SSH connection established between client and server. Now if client triggers reboot command to server, then closing the channel, session hangs.

1. Create SSH connection between client and server
2. Send command which reboots server.
3. Try to close the old session then it hangs

Expectation is clean close of old session and should succeed on next session open

 - OS: windows 10
 - libssh2 version 1.8.2

**Comment by willco007** [comment]
Are you using blocking mode?

**Comment by NallasivanK** [comment]
Hi,

Thanks for your reply. I am using non- blocking mode. But multi threaded
with mutex locked and libssh2_init, session , handle and all libssh2
calls.i see this issue once the remote device restarts and our client
trying to connect with new session.

1. Restart command send from client to device
2. Device restats but it takes 4 mins to come up
3. Meanwhile our client switch to blocking mode and set timeout of 2
minutes.
4. Then try to close channel. If timedout then socket closed.
5. Then session disconnected and freed.
6. Now client trying to connect to device every 1min.
7.finally socket gets connected to device in 5 min
8. But session handshake always fail here with error code -1

I need one more clarification. Currently I am handling multiple requests
asynchronously.so when write is in progress, *will there be a chance of
interleaving other writes or reads.?*

**Comment by NallasivanK** [comment]
Hi will , any update on this?
