### ISSUE TITLE
Problem with `libssh2_knownhost_check`

### ISSUE THREAD

**Issue by jakob** [libssh2/libssh2#42]
I've just discovered an issue with `libssh2_knownhost_check`.

The problem is that the typemask parameter is poorly documented.

To search for RSA or DSS keys, you need to provide either `LIBSSH2_KNOWNHOST_KEY_SSHRSA` or `LIBSSH2_KNOWNHOST_KEY_SSHDSS`. If you forget to provide one of these flags, libssh2 will compare any key types. This works if your known_hosts files contains the same key types you use, but fails if you use a different key type.

For example, many SSH servers now support elliptic curve cryptography. But libssh2 doesn't support EC. So if you connect to your server first with OpenSSH, it will put the EC host key into the known_hosts file. When you later try to connect with libssh2, it will fail, because it will compare the EC key to the RSA key, which of course fails.

Therefore it is necessary to always provide the correct typemask argument. If you forget the typemask argument, it is most likely an error.

I suggest that we change libssh2_knownhost_check to return an error when you don't provide a correct typemask parameter, as comparisons that don't take key type into account will lead to unexpected behaviour.

What do you think? If you think this is a good idea, I can volunteer to create a patch and send a pull request.

(Another note: I stumbled across this problem occurred because I provided the `keytype` value from `libssh2_session_hostkey`, which is a `LIBSSH2_HOSTKEY_*` constant, instead of providing a `LIBSSH2_KNOWNHOST_*` constant. It's confusing that there are different constants that mean similar things.)

**Comment by alamaison** [comment]
This sounds like a good idea.  PR welcome
