### ISSUE TITLE
sftp down file error, in 16k  postion(default cache size) data offset 1 byte

### ISSUE THREAD

**Issue by HelloWangFF** [libssh2/libssh2#424]
**Describe the bug**
sftp down file error, in 16k  postion(default cache size) data offset 1 byte

**To Reproduce**
1.build curl suport sftp protocol
2. use sftp servieice SSH_FXP_DATA have  end-of-file flag
 SFTP SERVICE refer to  https://tools.ietf.org/html/draft-ietf-secsh-filexfer-13#section-9.3
    byte   SSH_FXP_DATA
   uint32 request-id
   string data
   bool   end-of-file [optional]

**Expected behavior**
my test data is all ascii '1' expect download is same
but download not same  in end of file it is 0x00 not  equation '1'

**Version (please complete the following information):**
 - OS: Ubuntu 16.04.4 LTS
 - libssh2 version 1.9.0

**Additional context**

my fix  src/sftp.c read when read packet last content, postion add offset end-of-file flag
```
1390a1391,1400
>                       /* old code is memcpy(buffer, &filep->data[ filep->data_len - filep->data_left], copy);
>                       when have bool   end-of-file [optional], memcpy start postion is error
>
>                       size 9 ref https://tools.ietf.org/html/draft-ietf-secsh-filexfer-13
>                       when  SSH_FXP_DATA ( 1) uint32 request-id ( 4) string data ( prefix 4) sum is 9
>                       filep->data_len is ssl pack len  stringDataLen is SSH_FXP_DATA use string data
>                       optionalSize is  end-of-file [optional], maybe itis 1 or 0
>                       */
>                       size_t stringDataLen;
>                       size_t optionalSize;
1392,1393c1402,1405
<
<             memcpy(buffer, &filep->data[ filep->data_len - filep->data_left],
---
>                       stringDataLen=_libssh2_ntohu32(filep->data + 5);
>                       optionalSize=filep->data_len-stringDataLen - 9;
>
>             memcpy(buffer, &filep->data[ filep->data_len - filep->data_left - optionalSize],
```

**Comment by willco007** [comment]
What server are you testing with that uses the end-of-file flag?

**Comment by HelloWangFF** [comment]
> What server are you testing with that uses the end-of-file flag?

sftp server use apache ssh-core-0.14.0.jar that created  by my  Off-site colleagues
