### ISSUE TITLE
Compile on IBM i (AS400) 

### ISSUE THREAD

**Issue by hjindra** [libssh2/libssh2#426]
I would like to compile libssh2 on IBM i (known as AS400).
There is error issued during compilation on IBM i:
CZM1003: /libssh2-1.9.0/src/libssh2_priv.h, 286.5: CZM0046(30) Syntax error.

 - OS: IBM i i5/OS V7R3M0
 - libssh2 version 1.9.0
 - cryptography back-end: OS/400 Qc3

Thank you for help.
I have had open issue #298, but it has been stalled due to my inactivity, I am sorry for it. 
I would be very glad if the compilation on AS400 would be succeed and we could use the libssh2 on this platform.

**Comment by hjindra** [comment]
Hello,
is there anybody, who have a working libssh2 on AS400?
Thank you.

**Comment by zs6jce** [comment]
Any feedback on this issue?

**Comment by hjindra** [comment]
Unfortunately, I still don't have any positive information. I am still not able to compile libssh2 on OS/400.
So, if anybody have any experience with it, I will appreciate any positive information to this topic.

**Comment by bagder** [comment]
The port to OS/400 was done by @monnerat who doesn't has access nor work with such machines anymore. My advice: stop waiting around, roll up your sleeves, fix the issues and submit pull requests.
Or pay someone to do it for you.

**Comment by willco007** [comment]
As I noted in #298, it looks like this is an OpenSSL configuration issue with the static lib you're linking against. You should be able to sort this out by rebuilding OpenSSL and targeting the correct headers/static lib when building libssh2.

**Comment by monnerat** [comment]
My port to OS/400 and QC3 was anterior to elliptical curve support in libssh2, and I was out of IBM i business when the EC was implemented, leaving me no chance to work on it.
From what I can see from the current source state is: commit https://github.com/libssh2/libssh2/commit/aba34f5f56890563e6f0147ad8bc0e36aa966f49 implemented EC for all backends but QC3. In addition, this commit does not update the docs/HACKING.CRYPTO file accordingly, leaving no implementation guidelines for EC.
I'm sorry but you'll have to deal with it by yourself: either implement EC support for QC3 or comment it out in the regular source files or use an old version.
An update of docs/HACKING.CRYPTO would surely be precious for properly porting libssh2 to other/future crypto backends.
From what I can see in https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_73/apis/qc3crtkx.htm, EC support is present in QC3.
I have no experience at all in using openssl on OS/400 (not PASE), if ever possible.

**Comment by willco007** [comment]
I can update `hacking.crypto` with the EC API. In short, the API is a continuation of the existing style and is straight forward (as straight forward as a crypto backend can be). 

Looking at this issue closer, the QC3 backend is not set up like the other backends so when I stubbed out the EC data types, the type `_libssh2_ec_key` it never got stubbed out in the QC3 backend. I believe that is why the build is failing. The simple fix is, in a global libssh2 QC3 specific header add the following code `#define _libssh2_ec_key void`. That should allow you to build. If you look for that define you can see how it's stubbed out in the other backends.

**Comment by willco007** [comment]
I found where the defines are located, I'll submit a PR to fix this build issue.

**Comment by monnerat** [comment]
> ... as straight forward as a crypto backend can be.

!!!
This is why I wrote this file: designing a new crypto backend was not that evident for someone who did not write one already, and I spent a lot of time reverse-engineering the other backends to find these hints. That's why I think it is valuable to keep this file up to date, even if the project does not receive a new crypto backend every day :-).
Thanks for your hints on QC3: they have to be applied and tested by @hjindra, as I can't do it myself.

**Comment by willco007** [comment]
@hjindra I've pushed the fixes which should allow the AS400 port to build again, please give it a try.

**Comment by hjindra** [comment]
Hello,
I have tried it and it looks much better now.
But there are few data type mixing issue, which I am fighting with now.

There are in these 2 modules:
CZM1003:  kex.c, 443.33: CZM0280(30) Function argument assignment between types "unsigned char*" and "const unsigned char*" is not allowed.
CZM1003:  kex.c, 599.13: CZM0280(30) Function argument assignment between types "unsigned char*" and "const unsigned char*" is not allowed.
CZM1003:  kex.c, 608.13: CZM0280(30) Function argument assignment between types "unsigned char*" and "const unsigned char*" is not allowed.
CZM1003:  kex.c, 651.13: CZM0280(30) Function argument assignment between types "unsigned char*" and "const unsigned char*" is not allowed.
CZM1003:  kex.c, 660.13: CZM0280(30) Function argument assignment between types "unsigned char*" and "const unsigned char*" is not allowed.
CZM1003:  kex.c, 701.13: CZM0280(30) Function argument assignment between types "unsigned char*" and "const unsigned char*" is not allowed.
CZM1003:  kex.c, 729.13: CZM0280(30) Function argument assignment between types "unsigned char*" and "const unsigned char*" is not allowed.
CZM1003:  kex.c, 1133.35: CZM0280(30) Function argument assignment between types "unsigned char*" and "const unsigned char*" is not allowed.
CZM1003:  kex.c, 1292.13: CZM0280(30) Function argument assignment between types "unsigned char*" and "const unsigned char*" is not allowed.
CZM1003:  kex.c, 1300.13: CZM0280(30) Function argument assignment between types "unsigned char*" and "const unsigned char*" is not allowed.
CZM1003:  kex.c, 1342.13: CZM0280(30) Function argument assignment between types "unsigned char*" and "const unsigned char*" is not allowed.
CZM1003:  kex.c, 1350.13: CZM0280(30) Function argument assignment between types "unsigned char*" and "const unsigned char*" is not allowed.
CZM1003:  kex.c, 1390.13: CZM0280(30) Function argument assignment between types "unsigned char*" and "const unsigned char*" is not allowed.
CZM1003:  kex.c, 1417.13: CZM0280(30) Function argument assignment between types "unsigned char*" and "const unsigned char*" is not allowed.

CZM1003:  pem.c, 221.45: CZM0280(30) Function argument assignment between types "unsigned char*" and "const unsigned char*" is not allowed.
CZM1003:  pem.c, 231.49: CZM0280(30) Function argument assignment between types "unsigned char*" and "const unsigned char*" is not allowed. 

And one module has some syntax error or whatever:
CZM1003:  bcrypt_pbkdf.c, 116.24: CZM0275(30) Unexpected text ctx encountered.
CZM1003:  bcrypt_pbkdf.c, 116.5: CZM0045(30) Undeclared identifier libssh2_sha512_ctx.
CZM1003:  bcrypt_pbkdf.c, 133.26: CZM0045(30) Undeclared identifier ctx.
CZM1001:  bcrypt_pbkdf.c, 133.5: CZM0304(10) No function prototype given for "libssh2_sha512_init".
CZM1001:  bcrypt_pbkdf.c, 134.5: CZM0304(10) No function prototype given for "libssh2_sha512_update".
CZM1001:  bcrypt_pbkdf.c, 135.5: CZM0304(10) No function prototype given for "libssh2_sha512_final".
CZM1001:  bcrypt_pbkdf.c, 145.9: CZM0304(10) No function prototype given for "libssh2_sha512_init".
CZM1001:  bcrypt_pbkdf.c, 146.9: CZM0304(10) No function prototype given for "libssh2_sha512_update".
CZM1001:  bcrypt_pbkdf.c, 147.9: CZM0304(10) No function prototype given for "libssh2_sha512_final".
CZM1001:  bcrypt_pbkdf.c, 154.13: CZM0304(10) No function prototype given for "libssh2_sha512_init".
CZM1001:  bcrypt_pbkdf.c, 155.13: CZM0304(10) No function prototype given for "libssh2_sha512_update".
CZM1001:  bcrypt_pbkdf.c, 156.13: CZM0304(10) No function prototype given for "libssh2_sha512_final". 

For module kex.c helps the change "(const unsigned char *)" to "(unsigned char *)" on every reported line. But I am not successful in rest two.
Can you help with it also, please?

Thank you.

**Comment by willco007** [comment]
defined sha512 macros in PR #465

**Comment by monnerat** [comment]
@hjindra: it seems you're the only one who tried compiling on IBM i for 2.5 years ! I've blindly attempted to fix your problems in my own fork at https://github.com/monnerat/libssh2/tree/issue426.
Can you try from branch `issue426` from it? I tried a small fix for parameter type, but AFAICR, the IBM compiler is very picky about it and this fix may have the inverse effect in the worst case.
Please report here with error log. Thanks.
And sorry to ask you for tests: I have no alternative.

**Comment by monnerat** [comment]
@hjindra : anything new on this ?

**Comment by hjindra** [comment]
Hello,
I am sorry for late reply, I didn't have time...
I have compiled the sources from your branch with success! There was no issue, so I have the working binaries on AS400 now.

Now I am working on library test. I have a problem with libssh2_session_handshake which fails with "Scalar operand contains a value that is not valid." error. But I think that I have some typo in variables definition. I will debug it and I will return with results,.

Thank you very much for help.

**Comment by monnerat** [comment]
Thanks for the feedback. I'll then submit a PR with it.

> I have a problem with libssh2_session_handshake which fails with "Scalar operand contains a value that is not valid." error.

This does not seem related to the current issue and the fixes here can hardly introduce such a problem, IMHO. If you think it comes from a libssh2 bug, please open a new issue.
