### ISSUE TITLE
Please add UNIX socket forwarding support

### ISSUE THREAD

**Issue by Red-M** [libssh2/libssh2#428]
**Describe the bug**
Currently libssh2 does not implement any method of UNIX socket forwarding over an SSH connection.

**To Reproduce**
N/A

A recipe or example code that reproduces the problem? A stack trace from a crash

**Expected behavior**
libssh2 to support UNIX socket forwarding.

**Version (please complete the following information):**
 - OS: Any
 - libssh2 version any

**Additional context**
This feature was offered in #216 but the stale bot closed it.

**Comment by Red-M** [comment]
Can #216 please be progressed?

**Comment by DanielTUK** [comment]
I also would love to see #216 merged.

**Comment by Red-M** [comment]
Still wanting this merged.

**Comment by Red-M** [comment]
.

**Comment by Red-M** [comment]
.

**Comment by Red-M** [comment]
This still needs to be tracked
