### ISSUE TITLE
cannot locate symbol “EVP_cast5_cbc” on Android

### ISSUE THREAD

**Issue by alexgarret** [libssh2/libssh2#430]
I recently built libssh2 for Android using OpenSSL as a crypto backend, I also built libcrypto.so and libssl.so myself using the NDK. In my build process I generate a final libcustom.so linked with libssh2.a.

Google said "If you tried to use your own copy of OpenSSL but forgot to bundle it with your app's APK, the app may run normally on versions of Android platform that includes libcrypto.so. However, the app could crash on later versions of Android that do not include this library (such as, Android 6.0 and later)." that's why I package libcrypto.so, libssl.so and libcustom.so into my APK.

When running an Android app that loads the libcustom.so, my app crashes with the following error: failed: dlopen failed: cannot locate symbol "EVP_cast5_cbc" referenced by "libcustom.so"... **ONLY ON ANDROID 5**. It works well on Android 6 and above.

The symbol **EVP_cast5_cbc** is undefined but referenced in libssh2.a, but well defined in libcrypto.so.

I don't understand why it runs correctly on Android 6 and above and not on Android 5.

I thought that on Android 5, the libcrypto.so used was not the one I embed in the APK but the one from /system/lib ; so I tried to rename the libcrypto.so and build libssh2.a using the libcrypto renamed, but I am facing the same issue.

Does anybody have an idea ?

Thank's in advance.

 - OS: Android 5
 - libssh2 version 1.8.0

**Additional context**
This works well on Android 6 and above.

**Comment by dfandrich** [comment]
On Thu, Nov 07, 2019 at 01:37:52AM -0800, Alexandre Garret wrote:
> When running an Android app that loads the libcustom.so, my app crashes with
> the following error: failed: dlopen failed: cannot locate symbol
> "EVP_cast5_cbc" referenced by "libcustom.so"... ONLY ON ANDROID 5. It works
> well on Android 6 and above.

Are you testing exactly the same APK in all Android versions? What NDK are you
using and what Android version are you targeting?

> The symbol EVP_cast5_cbc is undefined but referenced in libssh2.a, but well
> defined in libcrypto.so.

If it's the same APK, then this is definitely weird. I can't think of why that
symbol would be considered undefined on only one version of Android and found
on another. Is there something in the ELF file that affects only that symbol?
Like symbol versioning or something?

> I thought that on Android 5, the libcrypto.so used was not the one I embed in
> the APK but the one from /system/lib ; so I tried to rename the libcrypto.so
> and build libssh2.a using the libcrypto renamed, but I am facing the same
> issue.

That was what I was thinking, too, but your tests should have eliminated that
possibility.

> Does anybody have an idea ?

Android 5 market share is dropping fast, so if you can't find a solution in a
few months, you can just drop support :-)

**Comment by alexgarret** [comment]
Yep, same APK is working well on Android 6 and above.
Target SDK is 28.
NDK used is 18.

However I just discover something interesting, when I run the version where I renamed the libcrypto.so by libcrypto_custom.so, on Android 5 I still have the same issue, but on other Android versions I have the following error: **dlopen failed: library "libcrypto.so" not found**. It looks like libcrypto.so is still requested while I built libssh2 using -DOPENSSL_CRYPTO_LIBRARY=<path/to>libcrypto_custom.so
In my APK, libcrypto.so has been replaced by libcrypto_custom.so

Am I missing something on the cross-compilation of libssh2 using a libcrypto with a custom name ?

**Comment by alexgarret** [comment]
Ok guys I found the problem... Using readelf on my libcrypto_custom.so I found that it was still linked to libcrypto.so, so my guess was right, it was still using the libcrypto.so from the system. 
What I did is patched the android.conf file on the openssl build system to add a variant: 
```
 "mycustom-android-arm" => {
        inherit_from     => [ "android-arm"],
        shlib_variant => ".custom",
    },
```

Now the lib is well generated and do not used the one in the system !

Thank you

**Comment by willco007** [comment]
I'm going to go ahead and close this since it looks like you have it sorted out.
