### ISSUE TITLE
libssh2_session_handshake error

### ISSUE THREAD

**Issue by cherevon** [libssh2/libssh2#433]
Example provided in this repository is not working for me. On the call to libssh2_session_handshake I'm always getting a timeout. Trying to connect to my OpenSSH service on localhost (127.0.0.1), WinSCP connects successfully.
Can't find the solution on the web =(

**Comment by sbredahl** [comment]
If you are using the latest Windows 10 release, you have to apply this patch https://github.com/libssh2/libssh2/pull/397 (or alternatively link with mbedtls which I assume you don't already)
