### ISSUE TITLE
libssh2_session_handshake return -43

### ISSUE THREAD

**Issue by sculida** [libssh2/libssh2#434]
Here was a ssh server at My Windows 10, than When I ran the demo named example-ssh2 builded by visual studio 2017 from libssh2 1.90. I saw the tcp socket was ESTABLISHED.

`session = libssh2_session_init()`

was successed.But

`libssh2_session_handshake(session, sock)`

 always return -43.

Could you help me?

**Comment by sbredahl** [comment]
If you are linking with wincng and use the latest Windows 10 build, you must apply this patch: https://github.com/libssh2/libssh2/pull/397

**Comment by sculida** [comment]
> If you are linking with wincng and use the latest Windows 10 build, you must apply this patch: #397

great!Thank you very much!
But what's the meaning of wincng?

**Comment by sbredahl** [comment]
> > If you are linking with wincng and use the latest Windows 10 build, you must apply this patch: #397
> 
> great!Thank you very much!
> But what's the meaning of wincng?

It is the Windows crypto backend. Alternatively you can link against mbedtls or openssl but then you need to compile those libraries also (which would also fix this issue since the bug is in WinCNG).
