### ISSUE TITLE
publickey authentification disable ssh-rsa

### ISSUE THREAD

**Issue by mickae1** [libssh2/libssh2#450]
Hi,

Openssh 8.2p1 has been released and they say the we should not use SHA1.

I would like to know how to disable host key algorithme ssh-rsa ? and use rsa-sha2-256 ?

**Comment by willco007** [comment]
You can disable sha1 this using the `libssh2_session_method_pref` API with `LIBSSH2_METHOD_HOSTKEY` and passing in values you wish to support.
