### ISSUE TITLE
Problem connecting to OpenTrons OT2 robot 

### ISSUE THREAD

**Issue by VincentBressler** [libssh2/libssh2#455]
**Describe the bug**
Unable to connect to OT2 robot after recent upgrade from OpenTrons. Previously was able to connect via password, now the only option is publickey, which does not work.

**To Reproduce**

This code:

`status = libssh2_userauth_publickey_fromfile_ex
(
	m_ssh, publickey_username, strlen(publickey_username),
	publickey_file, privatekey_file,
	passphrase
);`

returns status = -18 : LIBSSH2_ERROR_AUTHENTICATION_FAILED

Previously (earlier version of OT2 software) I was able to successfully connect using this the following:

`status = libssh2_userauth_password(m_ssh, user, pwd);`

This code below also returns status = -18

`status = libssh2_userauth_publickey_frommemory(m_ssh, publickey_username, strlen(publickey_username), publickey_filedata, publickey_filedata_len, privatekey_filedata, privatekey_filedata_len, passphrase);`

**Expected behavior**
Successful authentication.

libssh2 does not seem to be able to authenticate an ssh connection with the latest version of OT2 software. This incompatibility may be associated with avahi, which is being used by the latest version of the OT2 software to facilitate SSH. 

**Version (please complete the following information):**
My windows program is running in Windows 10.

 - libssh2 version "1.9.0_DEV"

**Additional context**
The OT2 robot is using avahi to facilitate ssh in the latest version. Not sure what they were using in earlier versions.

**Comment by willco007** [comment]
Does PR #397 happen to fix your issue?

**Comment by VincentBressler** [comment]
I am able to connect to the OT2 robot via ssh -i ot2_ssh_key root@ipaddress when using the same Windows 10 computer which will not connect via my program using libssh2.

I think that this rules out PR #397, please confirm.

**Comment by willco007** [comment]
Not exactly, what backend are you using with libssh2; openssl or wincng?

**Comment by VincentBressler** [comment]
Not sure what you are saying, the keys are generated using the following command from Windows Powershell:   `ssh-keygen -f ot2_ssh_key`

**Comment by willco007** [comment]
When you built the libssh2 library, which backend crypto library did you build it against? Openssl or wincng?

**Comment by VincentBressler** [comment]
These are the Additional Library Dependencies for that project: `bcrypt.lib;crypt32.lib;ws2_32.lib;kernel32.lib;user32.lib;gdi32.lib;winspool.lib;shell32.lib;ole32.lib;oleaut32.lib;uuid.lib;comdlg32.lib;advapi32.lib`

**Comment by VincentBressler** [comment]
Looks like wincng.

**Comment by willco007** [comment]
Please try the PR above and let us know if that works for you.
