### ISSUE TITLE
Add support for RFC8258 key exchanges

### ISSUE THREAD

**Issue by sldr** [libssh2/libssh2#457]
Add support the following key exchanges:
diffie-hellman-group14-sha256
diffie-hellman-group15-sha512
diffie-hellman-group16-sha512
diffie-hellman-group17-sha512
diffie-hellman-group18-sha512

**Comment by TDi-jonesds** [comment]
since more implementations are defaulting to it, at least please add diffie-hellman-group14-sha256

**Comment by willco007** [comment]
I'm finishing up work on group16 and group18 to bring us to the defaults OpenSSH uses which seems adequate.

**Comment by asvc** [comment]
@willco007 , any update on releasing a version with this and maybe https://github.com/libssh2/libssh2/pull/493?

**Comment by willco007** [comment]
This work is sitting on PR #468. I've been busing with other things, but hopefully I can loop back around and land it before too long. As for a release, someone (again, me most likely) still needs to address the missing key test files which are skipped by the release script.

**Comment by willco007** [comment]
Support landed with #468, closing.
