### ISSUE TITLE
Add ed25519 support using WinCNG

### ISSUE THREAD

**Issue by rustyx** [libssh2/libssh2#460]
It would have been great to improve parity with libssh and add EC support, and specifically ed25519.

**Comment by willco007** [comment]
ECDSA and ED25519 keys are both fully supported when using OpenSSL 1.1.1+.  ECDSA support using the mbed TLS backend is waiting a code review. What backend are you looking to have support for?

**Comment by rustyx** [comment]
Ahh, using WinCNG. Can that be supported too?

**Comment by willco007** [comment]
Someone who uses that backend and wants support would need to submit a PR. But the foundational legwork is there for any interested party to implement.
