### ISSUE TITLE
can't use camke build for android arm64-v8a 

### ISSUE THREAD

**Issue by KevinLoveGitHub** [libssh2/libssh2#471]
**Version (please complete the following information):**
 - OS: macOS
 - libssh2 version: 1.9.0

It is normal to compile armeabi-v7a with cmake of the same configuration

**logs**
system: darwin-x86_64
-- Check for working C compiler: /Users/Kevin/Library/Android/sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang
-- Check for working C compiler: /Users/Kevin/Library/Android/sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found OpenSSL: /Users/Kevin/Workspaces/Compile/autotools-build/openssl/arm64-v8a/lib/libcrypto.so (found version "1.1.1h")  
-- Looking for EVP_aes_128_ctr
-- Looking for EVP_aes_128_ctr - found
-- Found ZLIB: /Users/Kevin/Library/Android/sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/lib/aarch64-linux-android/libz.a (found version "1.2.7") 
[ 22%] Linking C shared library libssh2.so
[ 22%] Built target libssh2
Scanning dependencies of target copy_example_dependencies
[ 22%] Built target copy_example_dependencies
Scanning dependencies of target example-subsystem_netconf
[ 23%] Building C object example/CMakeFiles/example-subsystem_netconf.dir/subsystem_netconf.c.o
[ 24%] Linking C executable example-subsystem_netconf
/Users/Kevin/Library/Android/sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/darwin-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libssl.so.1.1, needed by ../src/libssh2.so, not found (try using -rpath or -rpath-link)
/Users/Kevin/Library/Android/sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/darwin-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libcrypto.so.1.1, needed by ../src/libssh2.so, not found (try using -rpath or -rpath-link)
../src/libssh2.so: undefined reference to `DSA_set0_pqg@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `BN_div@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_md5@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `BN_clear_free@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `ECDH_compute_key@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_sha256@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `RSA_get0_key@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `DSA_new@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `RSA_set0_factors@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `BN_sub@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `BN_rand@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY_get_raw_public_key@OPENSSL_1_1_1'
../src/libssh2.so: undefined reference to `EVP_PKEY_free@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_sha512@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `PEM_read_bio_DSAPrivateKey@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_des_ede3_cbc@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `RSA_free@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_DigestFinal@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `HMAC_Final@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `HMAC_CTX_new@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `RAND_bytes@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_MD_CTX_new@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EC_KEY_generate_key@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY_new@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EC_POINT_new@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_aes_256_cbc@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `PKCS8_PRIV_KEY_INFO_free@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `ASN1_STRING_get0_data@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY2PKCS8@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY_get1_EC_KEY@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EC_KEY_set_private_key@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_DigestInit@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `BIO_new_mem_buf@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `ECDSA_do_sign@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_DigestVerify@OPENSSL_1_1_1'
../src/libssh2.so: undefined reference to `EVP_PKEY_CTX_free@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EC_GROUP_get_curve_name@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_DigestSignInit@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_bf_cbc@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `X509_PUBKEY_get0_param@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY_derive_set_peer@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `BIO_free@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `X509_PUBKEY_set@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `BN_mod_exp@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_Cipher@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EC_POINT_point2oct@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY_derive@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `ECDSA_SIG_get0@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_DigestSign@OPENSSL_1_1_1'
../src/libssh2.so: undefined reference to `BIO_ctrl@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `BIO_new_file@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_aes_192_cbc@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `X509_PUBKEY_new@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_CIPHER_CTX_new@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY_keygen_init@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `ENGINE_register_all_complete@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY_new_raw_private_key@OPENSSL_1_1_1'
../src/libssh2.so: undefined reference to `DSA_SIG_new@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `PKCS8_pkey_get0@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `RSA_set0_key@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY_CTX_new@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY_derive_init@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `BN_bin2bn@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY_CTX_new_id@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_DigestVerifyInit@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY_set1_DSA@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `RSA_size@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_get_digestbyname@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `HMAC_Init_ex@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `BN_CTX_new@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_aes_192_ctr@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_aes_128_ctr@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `DSA_do_sign@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `ECDSA_SIG_set0@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_sha1@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `RSA_new@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY_new_raw_public_key@OPENSSL_1_1_1'
../src/libssh2.so: undefined reference to `EVP_aes_128_cbc@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_CipherInit@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `DSA_do_verify@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY_set1_EC_KEY@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `ECDSA_SIG_new@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `BN_new@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `PEM_read_bio_RSAPrivateKey@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `DSA_SIG_get0@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY_get1_RSA@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `DSA_get0_key@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `X509_PUBKEY_free@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_MD_CTX_free@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `DSA_get0_pqg@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `d2i_ASN1_OCTET_STRING@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `ASN1_OCTET_STRING_free@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `ASN1_STRING_length@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `DSA_SIG_free@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_rc4@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EC_KEY_get0_group@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `ENGINE_load_builtin_engines@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `ECDSA_SIG_free@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `PEM_read_bio_PrivateKey@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EC_KEY_new_by_curve_name@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `BN_bn2bin@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `RSA_sign@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EC_KEY_set_public_key@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY_id@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EC_GROUP_get_degree@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EC_KEY_get0_public_key@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `DSA_SIG_set0@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `RSA_verify@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY_keygen@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `BN_value_one@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `DSA_set0_key@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `RSA_get0_factors@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY_set1_RSA@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EC_KEY_free@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `PEM_read_bio_ECPrivateKey@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_cast5_cbc@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_DigestUpdate@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_aes_256_ctr@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_CIPHER_CTX_free@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EC_POINT_oct2point@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `HMAC_CTX_free@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `BN_num_bits@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `BN_CTX_free@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `RSA_set0_crt_params@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `BN_set_word@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `ECDSA_do_verify@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EC_POINT_free@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `HMAC_Update@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY_get1_DSA@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `DSA_free@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_ripemd160@OPENSSL_1_1_0'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [example/example-subsystem_netconf] Error 1
make[1]: *** [example/CMakeFiles/example-subsystem_netconf.dir/all] Error 2
make: *** [all] Error 2
[ 22%] Built target libssh2
[ 22%] Built target copy_example_dependencies
[ 23%] Linking C executable example-subsystem_netconf
/Users/Kevin/Library/Android/sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/darwin-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libssl.so.1.1, needed by ../src/libssh2.so, not found (try using -rpath or -rpath-link)
/Users/Kevin/Library/Android/sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/darwin-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libcrypto.so.1.1, needed by ../src/libssh2.so, not found (try using -rpath or -rpath-link)
../src/libssh2.so: undefined reference to `DSA_set0_pqg@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `BN_div@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_md5@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `BN_clear_free@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `ECDH_compute_key@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_sha256@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `RSA_get0_key@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `DSA_new@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `RSA_set0_factors@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `BN_sub@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `BN_rand@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY_get_raw_public_key@OPENSSL_1_1_1'
../src/libssh2.so: undefined reference to `EVP_PKEY_free@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_sha512@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `PEM_read_bio_DSAPrivateKey@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_des_ede3_cbc@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `RSA_free@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_DigestFinal@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `HMAC_Final@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `HMAC_CTX_new@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `RAND_bytes@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_MD_CTX_new@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EC_KEY_generate_key@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY_new@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EC_POINT_new@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_aes_256_cbc@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `PKCS8_PRIV_KEY_INFO_free@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `ASN1_STRING_get0_data@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY2PKCS8@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY_get1_EC_KEY@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EC_KEY_set_private_key@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_DigestInit@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `BIO_new_mem_buf@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `ECDSA_do_sign@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_DigestVerify@OPENSSL_1_1_1'
../src/libssh2.so: undefined reference to `EVP_PKEY_CTX_free@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EC_GROUP_get_curve_name@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_DigestSignInit@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_bf_cbc@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `X509_PUBKEY_get0_param@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY_derive_set_peer@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `BIO_free@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `X509_PUBKEY_set@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `BN_mod_exp@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_Cipher@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EC_POINT_point2oct@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY_derive@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `ECDSA_SIG_get0@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_DigestSign@OPENSSL_1_1_1'
../src/libssh2.so: undefined reference to `BIO_ctrl@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `BIO_new_file@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_aes_192_cbc@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `X509_PUBKEY_new@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_CIPHER_CTX_new@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY_keygen_init@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `ENGINE_register_all_complete@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY_new_raw_private_key@OPENSSL_1_1_1'
../src/libssh2.so: undefined reference to `DSA_SIG_new@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `PKCS8_pkey_get0@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `RSA_set0_key@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY_CTX_new@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY_derive_init@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `BN_bin2bn@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY_CTX_new_id@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_DigestVerifyInit@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY_set1_DSA@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `RSA_size@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_get_digestbyname@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `HMAC_Init_ex@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `BN_CTX_new@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_aes_192_ctr@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_aes_128_ctr@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `DSA_do_sign@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `ECDSA_SIG_set0@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_sha1@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `RSA_new@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY_new_raw_public_key@OPENSSL_1_1_1'
../src/libssh2.so: undefined reference to `EVP_aes_128_cbc@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_CipherInit@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `DSA_do_verify@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY_set1_EC_KEY@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `ECDSA_SIG_new@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `BN_new@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `PEM_read_bio_RSAPrivateKey@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `DSA_SIG_get0@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY_get1_RSA@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `DSA_get0_key@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `X509_PUBKEY_free@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_MD_CTX_free@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `DSA_get0_pqg@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `d2i_ASN1_OCTET_STRING@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `ASN1_OCTET_STRING_free@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `ASN1_STRING_length@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `DSA_SIG_free@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_rc4@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EC_KEY_get0_group@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `ENGINE_load_builtin_engines@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `ECDSA_SIG_free@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `PEM_read_bio_PrivateKey@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EC_KEY_new_by_curve_name@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `BN_bn2bin@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `RSA_sign@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EC_KEY_set_public_key@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY_id@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EC_GROUP_get_degree@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EC_KEY_get0_public_key@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `DSA_SIG_set0@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `RSA_verify@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY_keygen@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `BN_value_one@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `DSA_set0_key@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `RSA_get0_factors@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY_set1_RSA@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EC_KEY_free@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `PEM_read_bio_ECPrivateKey@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_cast5_cbc@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_DigestUpdate@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_aes_256_ctr@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_CIPHER_CTX_free@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EC_POINT_oct2point@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `HMAC_CTX_free@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `BN_num_bits@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `BN_CTX_free@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `RSA_set0_crt_params@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `BN_set_word@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `ECDSA_do_verify@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EC_POINT_free@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `HMAC_Update@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_PKEY_get1_DSA@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `DSA_free@OPENSSL_1_1_0'
../src/libssh2.so: undefined reference to `EVP_ripemd160@OPENSSL_1_1_0'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [example/example-subsystem_netconf] Error 1
make[1]: *** [example/CMakeFiles/example-subsystem_netconf.dir/all] Error 2
make: *** [all] Error 2

**Comment by willco007** [comment]
Without more information on your setup it's hard to tell where the error is, but looking at the logs it looks like you need to specify your OpenSSL path as an argument since it can't be found.

**Comment by KevinLoveGitHub** [comment]
openssl path is valid, library also exists

ANDROID_ABI="arm64-v8a"
rm -rf *
cmake ../ \
      -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
      -DANDROID_ABI=$ANDROID_ABI \
      -DANDROID_NATIVE_API_LEVEL=$MIN_SDK_VERSION \
      -DCMAKE_BUILD_TYPE=Release \
      -DENABLE_ZLIB_COMPRESSION=ON \
      -DCRYPTO_BACKEND=OpenSSL \
      -DBUILD_SHARED_LIBS=$BUILD_SHARED_LIBS \
      -DOPENSSL_INCLUDE_DIR="$OPENSSL_ROOT_DIR/$ANDROID_ABI/include" \
      -DOPENSSL_SSL_LIBRARY="$OPENSSL_ROOT_DIR/$ANDROID_ABI/lib/libssl.so" \
      -DOPENSSL_CRYPTO_LIBRARY="$OPENSSL_ROOT_DIR/$ANDROID_ABI/lib/libcrypto.so" \
      -DCMAKE_INSTALL_PREFIX=$OUTPUT_PATH/$ANDROID_ABI

cmake --build . --config Release
make install
make clean

**Comment by willco007** [comment]
Your build log says it was not found:

`
/Users/Kevin/Library/Android/sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/darwin-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libssl.so.1.1, needed by ../src/libssh2.so, not found (try using -rpath or -rpath-link)
`

**Comment by KevinLoveGitHub** [comment]
Thanks
There are `libssl.so` and `libssl.so.1.1` in the libssl lib folder
`libssl.so` is a soft link to `libssl.so.1.1`
Setting `OPENSSL_SSL_LIBRARY` to `libssl.so.1.1` solved the problem
