### ISSUE TITLE
1.9.0 can not build with openssl1.0.2

### ISSUE THREAD

**Issue by darkgirl** [libssh2/libssh2#472]
hi,
I was using cmake build, I am sure it found openssl, but it can not link to openssl, 
is there any other configure I need to do? or which version of openssl I need for 1.9.0?

![捕获](https://user-images.githubusercontent.com/28688741/82719759-1197f480-9ce0-11ea-8ace-ece0ff8cdba1.PNG)

I found a strange information.

` Found OpenSSL: C:/OpenSSL-Win64/lib/libcrypto.lib (found version "1.0.2g")`

this is not right, openssl1.0.2 does not have /libcrypto.lib, this is from openssl1.1

**Comment by lud0v1c** [comment]
Same here, tried with several OpenSSL libs, from 1.1.1g to d.
Had to go back to libssh2-1.8.2, unfortunately.

**Comment by willco007** [comment]
If it's not finding the version you'd like to use, use these flags `-DOPENSSL_INCLUDE_DIR`, `-DOPENSSL_CRYPTO_LIBRARY` and `-DOPENSSL_SSL_LIBRARY` to point `cmake` to the correct libraries/headers.

**Comment by lud0v1c** [comment]
@willco007 It's perfectly finding the versions, it just seems to not find certain test files, even though they are present

**Comment by willco007** [comment]
This is being tracked here #379.
