### ISSUE TITLE
use-of-uninitialized-value in _libssh2_packet_add

### ISSUE THREAD

**Issue by ltx2018** [libssh2/libssh2#477]
i found use-of-uninitialized-value in _libssh2_packet_add by fuzzing libssh2-master:
![image](https://user-images.githubusercontent.com/50396812/83088157-8c3c8780-a0c5-11ea-9bfe-445ee3b8dee6.png)

it may caused by malloc(0) in _libssh2_transport_read:
![image](https://user-images.githubusercontent.com/50396812/83088485-66fc4900-a0c6-11ea-85bc-b246672d07c1.png)
total_num is zero, p->payload is a wild ptr(NOT NULL)

OS: ubuntu 16.04

**Comment by ltx2018** [comment]
#476   may be a way to fix

**Comment by willco007** [comment]
Committed #476, thanks for the report.
