### ISSUE TITLE
Missing trailing null byte with scp upload

### ISSUE THREAD

**Issue by dansebcar** [libssh2/libssh2#482]
**Describe the bug**
I originally created an issue with libcurl, but I was asked to move it here https://github.com/curl/curl/issues/5507

When I upload a file using libssh2, the server spawns an scp process which receives a header line (including the content length) followed by the uploaded content. This scp process exits with code 1, even though the file does successfully get uploaded.

If I instead upload the file using scp on the client, the server side scp process receives almost the same content but with a null byte added at the end. In this case, the server side scp process exits with code 0.

This exit code is discarded. I stumbled across it using a `ForceCommand` wrapper in my sshd config, so I'm not able to determine in my wrapper if there was a problem with the upload or not.

**To Reproduce**
Run the scp_write example, you'll see the output `Conn: Exit status 1 received for channel 0/0`.

**Expected behavior**
I was expecting similar behaviour between client side scp and libssh2, ie that libssh2 will also include a trailing null byte, causing the server side scp to exit successfully.

**Version (please complete the following information):**
 - OS: debian buster
 - libssh2 version 1.8.0-2.1

**Additional context**
[I made a reproduction repo which demonstrates this discrepancy using libssh2 via curl](https://github.com/dansebcar/curl-scp)

**Comment by willco007** [comment]
Have you tried reproducing this with either libssh2 1.9.0 or master?

**Comment by bagder** [comment]
I did with libssh2 master, and the logs from `scp_write` against a current openssh shows the exit 1 code in the logs I posted in the [curl issue](https://github.com/curl/curl/issues/5507#issuecomment-638220203).

**Comment by virgoparna** [comment]
One of the side-effects is, that mtime is not set correctly currently when using libssh2_scp_send64 to copy file. 
Simply writing additional 1 byte with value 0 with libssh2_channel_write does not seem to be working  consistently. It works with small file, but has no effect in larger fails.

**Comment by kamyuentse** [comment]
+1 I use the [ssh2-rs](https://github.com/alexcrichton/ssh2-rs)

**Comment by kamyuentse** [comment]
@virgoparna sending additional `0x00`, and then wait and read "ack" work for me, I tested with ~3GB file.

**Comment by virgoparna** [comment]
Ok, my attempt was via calling libssh2_channel_write with 1 byte buffer that contains zero. And  that only seems to work on small files. Modifying libssh2 itself is not something I'm up to right now.
