### ISSUE TITLE
Can not able to download all file present in remote directory using SFTP

### ISSUE THREAD

**Issue by koratshail** [libssh2/libssh2#486]
I am not able to download all files present in a remote directory using SFTP.

I am using the SFTP protocol to download a file from a remote server.
I do not know how many and what names contain the files in a remote server. 

I am able to get success in the reading directory from a remote server using below APIs:
**libssh2_sftp_readdir_ex();**
This APIs just gives information in string format. 
How can I download each file present by reading directory API?
Is it possible using the **lib_ssh2** library?
I want to download all files present in the remote directory at once using the SFTP protocol.

@Daniel Stenberg, @bagder Do you know how to do this?

**Comment by willco007** [comment]
The SFTP protocol doesn't download folders, you must enumerate them and download the files individually and create the local directory structure yourself.
