### ISSUE TITLE
Incompatibilty with memory leak detectors

### ISSUE THREAD

**Issue by marcstern** [libssh2/libssh2#491]
Most memory leak detectors redefine "alloc", "realloc" and "free" (and others).
In struct _LIBSSH2_SESSION, we have fields with these names. This breaks the syntax when using such a memory leak detector.
Could you rename these fields (like "alloc_func")?
Thanks

**Comment by tsengjun** [comment]
Leakage detector should have the ability to detect leakage without source code change, if the detector is too weak and relay on source code change, how can they detect leakage inside a pre-compiled library?

Thanks!

**Comment by bagder** [comment]
I agree with @tsengjun. We've tracked memory leaks for a long time already so I don't see why we need to change code. valgrind and memory sanitizers work fine already.

**Comment by marcstern** [comment]
I understand that I didn't explain the whole issue.
When working with Visual Studio on a solution with several dozens projects, if you need to track a memeory leak, you need to include your debugging code in all libs in order to understand where an not deallocated block comes from. That can be done in 30 seconds. If you need to do it for every single project but libssh2, it's very long and cannot be undone easily.
So I understand _you_ do not need this, but it would help your users in some situations and it's such a trivial change without any drawback ... that I hope you will accept it.
Thanks a lot for your time

**Comment by marcstern** [comment]
Any chance to make this trivial change?
Thanks a lot

**Comment by marcstern** [comment]
Could anyone look at this?
Thanks a lot

**Comment by willco007** [comment]
@marcstern I still don't fully understand why your leak detector needs to re-write alloc/free, etc.  Feel free to submit a PR with your changes, but we're not likely to make these changes since it works as-is with most leak detectors.

**Comment by vszakats** [comment]
As @willco007 said, if this is resolved by renaming a few internal symbols, I think we're ready to accept a PR for this.
