### ISSUE TITLE
Instructions to compile a 32bits dll on Windows

### ISSUE THREAD

**Issue by brunobuzzi** [libssh2/libssh2#492]
I successfully compiled libssh2.dll on Windows but is 64bits dll.
Create documentation to compile a 32bit version.

PS: followed steps to compile a 64bits version:
1.	Install the free VS2019 Community Edition on your machine with the "Desktop development with C++" workload
1.1.	Be sure that Language Pack for English is installed on Visual Studio (if not there's gonna be trouble in next steps)
2.	Install cmake for windows (https://cmake.org/download/)
3.	On Windows Command Prompt (cmd):
3.1.	cd yourPreferedFolderForGitProjects
3.2.	git clone https://github.com/libssh2/libssh2.git
3.3.	cd libssh2
3.4.	mkdir dll
3.5.	cmake -DCRYPTO_BACKEND=WinCNG -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=./dll --build .
3.6.	cmake --build . --target install

**Comment by mback2k** [comment]
You need to manually specify the project build file generator used by cmake. Otherwise it will select one automatically. The -G parameter allows you to do that.

**Comment by brunobuzzi** [comment]
@mback2k thank you for the answer, the following did the trick:
```
cmake -G "Visual Studio 16 2019" -A Win32 -DCRYPTO_BACKEND=WinCNG -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=./dll32 --build .
cmake --build . --target install
```
