### ISSUE TITLE
Using libssh2 to create an SSH server?

### ISSUE THREAD

**Issue by randolf** [libssh2/libssh2#495]
I'm wondering if there are plans to implement server-side API support for creating an SSH server daemon using libssh2.  Thanks.

**Comment by willco007** [comment]
Not at this time. I think most people here would suggest using OpenSSH. 




Cheers,


Will




On Sat, Jul 4, 2020 at 11:13 AM -0700, "Randolf Richardson" <notifications@github.com> wrote:















I'm wondering if there are plans to implement server-side API support for creating an SSH server daemon using libssh2.  Thanks.

**Comment by randolf** [comment]
Oh?  Does OpenSSH provide this functionality for embedding a customized SSH server in one's own projects?

**Comment by bozimmerman** [comment]
I'd also love this feature.  OpenSSH is not really an option due to its license.

**Comment by dfandrich** [comment]
There are other, more liberally-licensed servers available, like Dropbear.
