### ISSUE TITLE
libssh2_session_handshake returns -13 after Windows 10 security update KB4560959

### ISSUE THREAD

**Issue by Larry1064** [libssh2/libssh2#498]
The library was communicating fine until Windows updates were in stalled. I believe it was security update KB4560959. I was unable to uninstall this update to prove it was the true cause. Windows 10 Enterprise Version 1909 OS Build 18363.900.
libssh2 version 1.9.0
I have provided a partial init function up to the point of the failure.

long Unit_init( char const *ip_address, long *session_handle )
{
	WSADATA		wsadata;
	int			err ;
	int			rc ;
	int			socky ;

	char const *fingerprint ;

	char		*userauthlist ;

	char const	*username = "root" ;

	//Super secret password, avert thine eyes
	char const	*secret_password = "xyz*zyx" ;

	//LIBSSH2_CHANNEL *channel ;
	LIBSSH2_SESSION *session ;

	struct		sockaddr_in sin;

	err = WSAStartup(  MAKEWORD( 2, 0 ), &wsadata ) ;  //Gimme version 2.0

	if( err != 0 )
		return ERR_SOCKET_LIB_INIT ;

	rc = libssh2_init( 0 ) ;  //0 means initialize normally
	
	socky = socket( AF_INET, SOCK_STREAM, 0 ) ;  //AF_INET means UDP, TCP, ect

	if( rc != 0 )
		return ERR_SOCKET_LIB_INIT ;

	sin.sin_family = AF_INET ;
	sin.sin_port = htons(22) ;  //htons converts an IP port number in hose byte order to the IP port unmber in network byte order.
	sin.sin_addr.s_addr = inet_addr( ip_address ) ;

	err = connect( socky, (struct sockaddr *) &sin, sizeof( struct sockaddr_in )) ;

	if( err != 0 )
		return ERR_SSH_LIB_INIT ;

	session = libssh2_session_init() ;

	libssh2_session_set_blocking(session, 0);

	err = libssh2_session_handshake( session, socky ) ;

	while( err == LIBSSH2_ERROR_EAGAIN )
	{
		err = libssh2_session_handshake( session, socky ) ;
	}	
// fails here libssh2_session_handshake returns -13 and the following function fail.
	fingerprint = libssh2_hostkey_hash( session, LIBSSH2_HOSTKEY_HASH_SHA1 ) ;

	userauthlist = libssh2_userauth_list( session, username, strlen(username)) ;
...
}

**Comment by willco007** [comment]
This is likely this issue: #388

**Comment by Larry1064** [comment]
Do you intend to put out a new version to resolve this issue?

**Comment by Larry1064** [comment]
I downloaded the latest snapshot and created a new lib. The latest seems to work fine.
Thanks

**Comment by willco007** [comment]
Duplicate of #388, I'm going to close. The next release will have the official fix.
