### ISSUE TITLE
libssh2_sftp_read returns negative size_t in rhel7

### ISSUE THREAD

**Issue by nbuddepu** [libssh2/libssh2#522]
Hi, we are trying to use the libssh2 library to perform sftp operations on our RHEL7 linux instance. the libssh2 version available is 1.8.0-3.el7        @rhel-7-server-eus-rpms/7.7. when the libssh2_sftp_read is executed against a file, at times it is returning a negative value where it is supposed to return an unsigned integer. any idea why this happens?

**Comment by sbredahl** [comment]
libssh2_sftp_read returns ssize_t not size_t. 

Negative values are error codes (#defined in include/libssh2.h).
