### ISSUE TITLE
libssh2_channel_free, libssh2_session_free... etc should set pointer to NULL

### ISSUE THREAD

**Issue by GopherJ** [libssh2/libssh2#524]
Hi, first I need to say that I'm new to C, so if it's an intended design, please just close this issue.

I think `*_free` functions should set pointer to NULL, because uses may use:

```
if (channel)
  libssh2_channel_free(channel)
```

if `libssh2_channel_free` don't set channel pointer to NULL, then probably users will free two times which may cause a crash

**Comment by bagder** [comment]
No it shouldn't and it can't.
