### ISSUE TITLE
LIBSSH2_ERROR_KEX_FAILURE : ssh-rsa -> ssh-ed25519

### ISSUE THREAD

**Issue by mickae1** [libssh2/libssh2#526]
Hi,

In the known host file, I've an old hostkey type : 
ssh-rsa ................

But my device is using a new hostkey type: ssh-ed25519

Why did I got the error :

 LIBSSH2_ERROR_KEX_FAILURE

I would like to have : CURLKHMATCH_MISMATCH in return to this function

If I delete the file known_host file, it work.

**Comment by willco007** [comment]
This report is missing a lot of information about how you are connecting and when you're testing the known host value; but the flow should be something like this:

1) create the libssh2 session and connect
2) call libssh2_session_hostkey()
3) call libssh2_knownhost_init()
4) call libssh2_knownhost_readfile()
5) call libssh2_knownhost_check()

This will return LIBSSH2_KNOWNHOST_CHECK_MISMATCH if the keys don't match.  The KEX_FAILURE usually means the server and your client couldn't agree on a key exchange algorithm and doesn't directly relate to the known hosts file. If you step through your code with the debugger you should be able to pretty quickly figure out where the error is being generated from.
