### ISSUE TITLE
libssh_channel_free is not thread safe

### ISSUE THREAD

**Issue by GopherJ** [libssh2/libssh2#531]
While using libssh2 in production, I found that sometimes when I close multiple channels (use the same underlying session) at the same time.

My application crashes with a segment fault error, it happens frequently on openwrt mips arch devices but not on x86_64

**Comment by GopherJ** [comment]
I saw similar issue: https://github.com/libssh2/libssh2/issues/367 but it was closed

**Comment by GopherJ** [comment]
Multiple channels access to the same session:

https://github.com/libssh2/libssh2/blob/6c7769dcc422250d14af1b06fce378b6ee009440/src/channel.c#L2717

So if these channels are in different threads, there maybe a pb. Any one has an idea on this?

**Comment by willco007** [comment]
I'm not super familiar with the channel code, however, I think the general guidance is one session per thread for thread safety.

**Comment by GopherJ** [comment]
@willco007 then we need to do handshake & auth in every thread. I don't really think this is a good solution and I'm also not sure if it'll work for `tcp forward` case because the server will already be listening on a port

**Comment by GopherJ** [comment]
@willco007 if you see the rust wrapper:

https://docs.rs/ssh2/0.8.2/src/ssh2/session.rs.html#141

The underlying session is wrapped into a mutex which make it secure to access, but it's not the case of `libssh2`

**Comment by ismail-yilmaz** [comment]
@GopherJ 
> @willco007 then we need to do handshake & auth in every thread. I don't really think this is a good solution and I'm also not sure if it'll work for `tcp forward` case because the server will already be listening on a port

No, not really, you don't. For example we are using in [Ultimate++](https://github.com/ultimatepp/ultimatepp) a mutex-based simple locking mechanism that works pretty well with the underlying libssh2 code. Single session-multiple channels (on worker threads) approach works fine with libssh2. You have to design the code carefully and mark the critical sections well, that's all. (In fact we have a single critical section where we execute libssh2 code (via callbacks and lambdas)

**Comment by willco007** [comment]
There is no built-in mutex support, so if you're going to attempt using one session across threads you're going to have to design it on the client side as @ismail-yilmaz noted.

**Comment by GopherJ** [comment]
@ismail-yilmaz Hi, would you mind giving some snippet to show how should it solve the pb?
