### ISSUE TITLE
Clarification | "Failed getting banner" during connection, because of empty line in banner

### ISSUE THREAD

**Issue by bensbox** [libssh2/libssh2#538]
**Describe the bug**
Hi everybody - i like to clarify if this is currently a bug or a RFC conform behaviour.

After connecting to a SFTP server, the server is presenting the following banner:

> Welcome to FooBar Services FTP site.\n
> \n
> Please close the session after the transfer is complete.\r\n
> SSH-2.0-FooBarServices\r\n

This is being read line by line by [banner_receive()](https://github.com/libssh2/libssh2/blob/libssh2-1.8.0/src/session.c#L97) during [session_startup()](https://github.com/libssh2/libssh2/blob/libssh2-1.8.0/src/session.c#L716).

**The problem is the empty line**, which will influence the lines [159-170 (v1.8.0)](https://github.com/libssh2/libssh2/blob/libssh2-1.8.0/src/session.c#L159):

```
while (banner_len &&
       ((session->banner_TxRx_banner[banner_len - 1] == '\n') ||
        (session->banner_TxRx_banner[banner_len - 1] == '\r'))) {
    banner_len--;
}

....

if (!banner_len)
    return LIBSSH2_ERROR_BANNER_RECV;
```
The while() part is reducing the banner_len by the newline character and after that it is 0 and the function will return LIBSSH2_ERROR_BANNER_RECV, which results into an [_libssh2_error() in session_startup()](https://github.com/libssh2/libssh2/blob/libssh2-1.8.0/src/session.c#L718)

According to the [RFC4253](https://tools.ietf.org/html/rfc4253#section-4.2):
> The server MAY send other lines of data before sending the version string

But i can't see if empty lines are actually not allowed anywhere. Granted the server is not using "\r\n" but only "\n" during the banner, but i guess this can be handled nicely (which libssh2 does)

When i let the code skip the if, then i am able to connect to the server just fine.

The question is - is this a bug or a RFC conform behaviour. Please clarify where this is defined in the RFC, in case the current behaviour is fine

**To Reproduce**
Use the code from master or v1.8.0 and use the banner posted above.

**Expected behavior**
Login is successful regardless how the banner looks like as long as it is fine for the RFC

**Version (please complete the following information):**
- Ubuntu 18.04 or 20.04
- libssh2 version master or 1.8.0

Thanks!

**Comment by willco007** [comment]
What is the banner text that is being read into `banner_TxRx_banner`? It seems the subtracting the `\r\n` off the end of the banner wouldn't be causing this issue directly if the entire banner was read. Is it being truncated due to the unix line endings?
