### ISSUE TITLE
CMake files missing in version 1.6.0 tar ball

### ISSUE THREAD

**Issue by hwaterfall** [libssh2/libssh2#54]
libssh2-1.6.0

CMakeLists.txt and the cmake folder are not included in the libssh2-1.6.0.tar.gz available from www.libssh2.org.

It is included in the .zip file that can be downloaded from github here:
https://github.com/libssh2/libssh2/tree/libssh2-1.6.0

**Comment by bagder** [comment]
Fixed in commit d48d7c3a87c
