### ISSUE TITLE
Write Permission for Group and Others is not getting set for file created on remote host

### ISSUE THREAD

**Issue by rookierook** [libssh2/libssh2#540]
**Describe the bug**
In case of files created using following API write permission for Group and Others is not getting set for file created on remote host.
LIBSSH2_SFTP_HANDLE *
libssh2_sftp_open_ex(LIBSSH2_SFTP *sftp, const char *filename,
                     unsigned int filename_len, unsigned long flags,
                     long mode, int open_type);

**To Reproduce**
Create a file using API: libssh2_sftp_open_ex and pass mode as 0777, the file is created with 0755 i.e. write permission for groups and others are discarded in all cases, above mentioned case is just an example.

**Expected behavior**
File should be created with the permissions passed as the "mode" argument i.e. if 0777 is passed then it should assign the file permission for 0777 and not 0755(Write permission discarded for group and others).

If this is expected and is done for security reasons for giving write permission explicitly to owner only. Then this could be documented and if it is then could someone please guide me to that updated document.
I am working with following documentation:
https://www.libssh2.org/

**Version (please complete the following information):**
 - OS: RHEL 7.3
 - libssh2 1.9.0

**Comment by willco007** [comment]
Assuming you've passing the correct flags, servers can and will ignore or change the passed in permissions. Are you sure your server isn't set up to modify them on file creation? If you look at `sftp_open` you can see libssh2 doesn't modify the values being passed in before sending them along.

**Comment by rookierook** [comment]
I went through sftp_open but the actual culprit was umask 0022.
Thanks @willco007
