### ISSUE TITLE
Leveraging Security.framework on OSX

### ISSUE THREAD

**Issue by alexcrichton** [libssh2/libssh2#55]
I found [an old thread on this](http://www.libssh2.org/mail/libssh2-devel-archive-2014-12/0001.shtml) but it looks like not much came of it, so I was wondering if there are plans to not use OpenSSL on OSX and instead leverage Security.framework and other components?

Currently libssh2 doesn't compile on OSX 10.11 by default (as el capitan removed OpenSSL headers), but if Security.framework were used it should in theory work just fine!

**Comment by bagder** [comment]
We don't really "plan" things. Those who want to work on implementing something just go ahead and do that! We appreciate and we will merge patches that make libssh2 work with other crypto backends, assuming the patches are good.

**Comment by alexcrichton** [comment]
Aha ok, thanks for the info! I'll close this in that case and perhaps if I've got some spare time I can revive that old patch :)
