### ISSUE TITLE
aes ctr supported or not?

### ISSUE THREAD

**Issue by fingolfin** [libssh2/libssh2#56]
The list of supported ciphers on http://www.libssh2.org/ does not list aes256-ctr, aes128-ctr, aes192-ctr. But they do seem to be present in the source code, and a quick test seems to indicate they work.

So, is this just an omission on the website?

**Comment by bagder** [comment]
It seems so! Care to send us a pull request? The web site is in the www repo next to the code repo...

**Comment by fingolfin** [comment]
Seems @bk2204 beat me to it -- and that already on Sep 13 :). He also added the missing arcfour128 and some missing HMACs, but it seems the change never went to the website. Perhaps that is so because he also added hmac-sha2-256, which is not in 1.6.0, but is in the master branch...

Anyway, I wanted to know this to verify my page here is correct:
  http://ssh-comparison.quendi.de/impls/libssh2.html
Seems it is... ;-)

**Comment by bagder** [comment]
Ah then the fault was all mine as I hadn't updated the web page accordingly! :-/ Fixed now. Thanks for reporting!
