### ISSUE TITLE
cross compile of **libssh** :::::::::: implicit declaration of function ‘AES_ctr128_encrypt’

### ISSUE THREAD

**Issue by rohitkathuria102** [libssh2/libssh2#564]
I am trying to cross compile libssh on x86 for 32 bit-ARM board. i am able to compile and build openssl but libssh compilation is giving some errors::

while running **cmake ..** command i am facing this error::

/home/labadmin/32bit/libssh-0.9.1/src/libcrypto.c: In function ‘aes_ctr_encrypt’:
/home/labadmin/32bit/libssh-0.9.1/src/libcrypto.c:706:3: error: implicit declaration of function ‘AES_ctr128_encrypt’; did you mean ‘AES_cfb128_encrypt’? [-Werror=implicit-function-declaration]
   AES_ctr128_encrypt(in, out, len, &cipher->aes_key->key, cipher->aes_key->IV, tmp_buffer, &num);
   ^~~~~~~~~~~~~~~~~~
   AES_cfb128_encrypt
cc1: some warnings being treated as errors
src/CMakeFiles/ssh_shared.dir/build.make:1334: recipe for target 'src/CMakeFiles/ssh_shared.dir/libcrypto.c.o' failed
make[2]: *** [src/CMakeFiles/ssh_shared.dir/libcrypto.c.o] Error 1
CMakeFiles/Makefile2:203: recipe for target 'src/CMakeFiles/ssh_shared.dir/all' failed
make[1]: *** [src/CMakeFiles/ssh_shared.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by dfandrich** [comment]
It looks like you're trying to compile libssh, not libssh2, in which case
this is the wrong place to ask for help.

**Comment by willco007** [comment]
Indeed, this looks like libssh, not libssh2. Closing.
