### ISSUE TITLE
Add support for ECDSA signatures with MbedTLS backend

### ISSUE THREAD

**Issue by staticfloat** [libssh2/libssh2#573]
It appears that libssh2 has had support for ECDSA signatures since https://github.com/libssh2/libssh2/pull/206 was landed.  Although OpenSSL is the default backend, there are large users (such as the Julia Language project) that default to the MbedTLS backend, and it would be very useful to have these more modern signatures (which many modern SSH builds prefer to use) supported on the MbedTLS backends as well.

What are the steps needed in order to enable MbedTLS-backed ECDSA key handling?

**Comment by willco007** [comment]
In short, the ECDSA API endpoints in `crypto.h` need to be implemented in the mbed backend. You can look at the OpenSSL implementation for guidance, but it will be a bit of work.

**Comment by sbredahl** [comment]
This was added in #385.

**Comment by willco007** [comment]
Hey, I totally forgot about this. :) Thanks! Closing this issue.

**Comment by staticfloat** [comment]
Ah, that's great news!  I see that there is already a request for a new version (https://github.com/libssh2/libssh2/issues/572) so I'll just gratefully request a new release soon so that we can get this capability shipped out to our users! :)
