### ISSUE TITLE
Implement AES-GCM algorithms

### ISSUE THREAD

**Issue by bk2204** [libssh2/libssh2#583]
**Describe the bug**
libssh2 does not implement `aes128-gcm@openssh.com` or `aes256-gcm@openssh.com`.

**To Reproduce**
Attempt to connect to a server which offers only the AES-GCM cipher suites, and verify that it doesn't connect.

**Expected behavior**
libssh2 should connect to servers which support only the OpenSSH GCM cipher suites.

**Version (please complete the following information):**
Should be all systems on the latest `master`.  `git grep` shows no instances of the text `gcm` in the codebase.

**Additional context**
Assuming hardware support, `aes128-gcm@openssh.com` is the fastest possible algorithms on modern hardware.  We use it internally to minimize transfer times.  The 256-bit version is almost as fast.

As mentioned in #582, I know of an implementation which supports only `aes256-gcm@openssh.com` and `aes256-ctr` with the HMAC-SHA-2 EtM suites, and libssh2 cannot connect to it.  This impedes using libgit2 to transfer data to this implementation.

**Comment by ianhattendorf** [comment]
We have users that would appreciate this functionality.

**Comment by digikal** [comment]
We have also received many requests for this.

**Comment by ta32** [comment]
Its implemented here ChaCha20-Poly1305 and AES256-GCM
https://github.com/jedisct1/libsodium

hope it helps

**Comment by lvandal** [comment]
I have a user that reported an issue related to this when trying to use keys generated via the Termius app. It seems like that app uses aes[128|256]-gcm@openssh.com, which libssh2 doesn't yet support.

I could reproduce the issue from my Mac as well using `ssh-keygen -t ed25519 -a 100 -Z aes256-gcm@openssh.com`

Would be nice to add this feature. Thanks!

**Comment by palmin** [comment]
The importance of having `aes128-gcm@openssh.com` and `aes256-gcm@openssh.com` support in libssh2 is growing but I have difficulty carving out the time.

I'm offering a **$2000 USD** bounty for anyone adding support in the form of a pull request towards libssh2 as well as a pull request towards the `shellfish` branch in https://github.com/palmin/libssh2 that is my slightly modified fork with encrypt-then-mac support.

You will find contact information in my GitHub profile.

**Comment by palmin** [comment]
There is now a pull request solving this issue: https://github.com/libssh2/libssh2/pull/797

The equivalent changes against my encode-then-mac [fork](https://github.com/palmin/libssh2/tree/shellfish) is being beta tested by a few hundred users with no sign of instability or crashing the first 5 days.

**Comment by vszakats** [comment]
This has landed in 3c953c05d67eb1ebcfd3316f279f12c4b1d600b4.
