### ISSUE TITLE
win32\libssh2.dsp is missing from git repo

### ISSUE THREAD

**Issue by hwaterfall** [libssh2/libssh2#59]
libssh2-1.6.0

Somewhat related to bug #54.

CMakeLists.txt and the cmake folder are included in the .zip file that can be downloaded from github here:
https://github.com/libssh2/libssh2/tree/libssh2-1.6.0

however, Visual Studio 2013 reports that the project is corrupted if you try to open win32\libssh2.dsw likely because libssh2.dsp is missing.

**Comment by bagder** [comment]
getting a zip from github only packs up what's in git, that file is not in git but it is present in our release tarballs. I don't consider this a bug.

**Comment by hwaterfall** [comment]
Not worth arguing over I guess, but I think it's reasonable to expect that a project pulled from git will build. Obviously that's not possible with libssh2.dsp missing. Furthermore, it's quite odd that libssh2.dsw and tests.dsp are included in the git repo, but libssh2.dsp is not. If the intention is not to support Windows in git, why not drop the win32 folder altogether? If on the other hand, Windows is being supported, it only makes sense to keep all the project files under source control. MHO of course!

**Comment by bagder** [comment]
For all I know, we support building on windows, even when code is straight from git. If not, we should fix it and make sure we do. The solution is however **not** to commit files that are automatically generated by other scripts/tools. We will welcome help and fixes.

I'm pretty sure the cmake build scripts work even for Windows and thus avoids the problem you refer to.

(Personally I don't develop nor build on Windows so I'm not the guy to do this.)

**Comment by alamaison** [comment]
I'm closing this as wontfix. Please use the CMake projects to generate working builds on Windows.
