### ISSUE TITLE
Implement additional key exchange algorithm(s)

### ISSUE THREAD

**Issue by otovalek** [libssh2/libssh2#590]
**Describe the bug**
The current list of supported key exchange algorithms:

`diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group-exchange-sha256`

prevents libssh2 from connecting to a server, which doesn't support any of them.
E.g. the dropbear server (since version 2018.76) supports these algorithms:

`curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group14-sha256,kexguess2@matt.ucc.asn.au`

(the sha1 algorithms were disabled in 2018.76 as too weak).

**To Reproduce**
Try to connect to dropbear server (>=2018.76).
The connection fails and server logs "dropbear[4869]: Exit before auth: No matching algo kex"

**Expected behavior**
libssh2 is able to connect.

**Version:**
 - OS: Debian 4.19.181-1 x86_64
 - libssh2 version: 1.8.0, but issue is likely present in latest 1.9.0 as well

**Additional context**
Implementing diffie-hellman-group14-sha256 should be the easiest as similar diffie-hellman algorithms are already supported.

**Comment by otovalek** [comment]
Thanks for clarification. I was checking just the changelog and "Capabilities and Features" section at https://www.libssh2.org/ website, not the source code.

The https://www.libssh2.org/ needs an update then.

**Comment by willco007** [comment]
Logged issue against for the [website to be updated](https://github.com/libssh2/www/issues/14).
