### ISSUE TITLE
libssh2 user authentication fails with pubic key

### ISSUE THREAD

**Issue by Gayunivi** [libssh2/libssh2#593]
I am trying to establish sftp communication, I can able to establish connection when I use libssh2_userauth_password. 
If I use, libssh2_userauth_publickey_fromfile as well as _frommemory it is failing with return code -18 (LIBSSH2_ERROR_AUTHENTICATION_FAILED ).
I generated RSA key in server side and copied the file in local system and giving the file path as parameter to the function.
I have referred related issues, but i can't able to solve the issue.
Can anyone please help solving this issue!

**Comment by willco007** [comment]
Public Key auth works in the library, I would suggest reaching out to the dev email list for assistance if you're continuing to have an issue. Since this isn't a bug report but more of a support request I'm going to close this issue, thanks.
