### ISSUE TITLE
Compiling a dynamic library on Windows does not create an import lib

### ISSUE THREAD

**Issue by ribtoks** [libssh2/libssh2#595]
**Describe the bug**
When building on Windows like this:

```
cmake .. -G "NMake Makefiles"^
 -DCMAKE_INSTALL_PREFIX=./release/libs/^
 -DCMAKE_PREFIX_PATH=./release/libs/^
 -DCMAKE_BUILD_TYPE=release^
 -DBUILD_SHARED_LIBS=ON^
 -DCRYPTO_BACKEND=OpenSSL^
 -DBUILD_EXAMPLES=OFF^
 -DBUILD_TESTING=OFF^
 -DENABLE_ZLIB_COMPRESSION=ON

nmake.exe /f Makefile
nmake.exe install
```

only a `libssh2.dll` file is produced without an accompanying import library `libssh2.lib` that should be used when linking with dynamic library.

**To Reproduce**

(included in the beginning)

**Expected behavior**

I would expect a `.lib` produced like from, say, libcurl build.

**Version (please complete the following information):**

 - OS: Windows 10
 - libssh2 version 1.9.0, 1.8.2

**Comment by ribtoks** [comment]
It works, however, if using another generator `-G "Visual Studio 16 2019"`

**Comment by lifegpc** [comment]
use `ninja` generator has same issue.

**Comment by ribtoks** [comment]
Not stale

**Comment by vszakats** [comment]
We believe this is fixed in current master. Please reopen, if still relevant.
