### ISSUE TITLE
configure.ac Cygwin build patch adoption

### ISSUE THREAD

**Issue by BrianInglis** [libssh2/libssh2#598]
**Describe the bug**
Cygwin has been patching libssh2 configure.ac for 10+ years to allow Cygwin builds to work

**To Reproduce**
Cygwin builds fail because libssh2 configure(.ac) assumes Cygwin is like Win32 ather than POSIX/Linux 

**Expected behavior**
Cygwin libssh2 builds work without custom Cygwin patches

**Version (please complete the following information):**
 - OS: Cygwin 1.7+/WinNT+...10
 - libssh2 version 1.2.7+

**Additional context**
Please apply attached patch to your configure.ac (added .txt as .patch/.diff not recognized/allowed by MS github) which removes custom Cygwin definition and uses POSIX/Linux default
[cygwin-configure-ac.patch.txt](https://github.com/libssh2/libssh2/files/6482033/cygwin-configure-ac.patch.txt)

**Comment by BrianInglis** [comment]
Would you prefer this configure.ac fix be submitted as a PR? 
It affects only Cygwin builds by treating them like default POSIX systems not Windows.

**Comment by willco007** [comment]
PRs are great! Otherwise I'll put it into my other outstanding .ac file change tomorrow.

**Comment by BrianInglis** [comment]
Thanks, that would be great if you could do so without PR. 
I am working on releasing updated Mingw libssh2 and Cygwin and Mingw 32 & 64 bit curl including the updated libssh2 1.9.0 to address a user issue unable to use ed25519 ciphers with our current releases. 
But given that Mingw libssh2 1.9.0 currently does not cross-build with WinCNG only OpenSSL, I may have to reconfigure Mingw libcurl, or may have difficulties building using incompatible SSL libraries.

**Comment by willco007** [comment]
This has been committed, closing this issue.
