### ISSUE TITLE
Install to non-default location not working, CMAKE_INSTALL_PREFIX is not defined

### ISSUE THREAD

**Issue by hwaterfall** [libssh2/libssh2#60]
libssh2-1.6.0
Windows 10

I'm able to successfully build libssh2 on Windows but I cannot install it. docs\INSTALL_MAKE indicates: 

**If you are not using CMake for your own project, install libssh2**

   **cmake <libssh2 source location>**
   **cmake --build .**
   **cmake --build . --target install**
**or**
   **cmake --build . --target INSTALL**

**and then specify the install location to your project in the normal**
**way for your build environment.  If you don't like the default install**
**location, add `-DCMAKE_INSTALL_PREFIX=<chosen prefix>` when initially**
**configuring the project.**

however, when I run:
cmake -DCMAKE_INSTALL_PREFIX="myssh2\install\location" -DZLIB_LIBRARY="my\zlib\lib\location" -DZLIB_INCLUDE_DIR="my\zlib\include\location" -DENABLE_ZLIB_COMPRESSION=ON -DCRYPTO_BACKEND=OpenSSL -DOPENSSL_ROOT_DIR="my\openssl\root"

These two work:
cmake --build .
cmake --build . --target RUN_TESTS

However "myssh2\install\location" remains empty after running this:
cmake --build . --target INSTALL

I've searched all the files in both libssh2-1.6.0.tar.gz from libssh2.org and libssh2-libssh2-1.6.0.zip from github, but CMAKE_INSTALL_PREFIX seems to only appear in  docs\INSTALL_MAKE.

**Comment by alamaison** [comment]
On 3 Nov 2015 4:14 am, "hwaterfall" <notifications@github.com> wrote:
>
> libssh2-1.6.0
> Windows 10
>
> I'm able to successfully build libssh2 on Windows but I cannot install
it. docs\INSTALL_MAKE indicates:
>
>
> If you are not using CMake for your own project, install libssh2
>
> cmake
> cmake --build .
> cmake --build . --target install
> or
> cmake --build . --target INSTALL
>
> and then specify the install location to your project in the normal
> way for your build environment. If you don't like the default install
> location, add -DCMAKE_INSTALL_PREFIX=<chosen prefix> when initially
> configuring the project.
> <\snip>
>
> however, when I run:
> cmake -DCMAKE_INSTALL_PREFIX= -DZLIB_LIBRARY= -DZLIB_INCLUDE_DIR=
-DENABLE_ZLIB_COMPRESSION=ON -DCRYPTO_BACKEND=OpenSSL -DOPENSSL_ROOT_DIR=
>
> These two work:
> cmake --build .
> cmake --build . --target RUN_TESTS
>
> However remains empty after running this:
> cmake --build . --target INSTALL

I'm not sure I understand the problem. What were you expecting to see after
`cmake --build . --target INSTALL`, and how does that differ from what you
see?

> I've searched all the files in both libssh2-1.6.0.tar.gz from libssh2.org
and libssh2-libssh2-1.6.0.zip from github, but CMAKE_INSTALL_PREFIX seems
to only appear in docs\INSTALL_MAKE.

`CMAKE_INSTALL_PREFIX` is built-in CMake functionality. You can read more
about it in their docs:
https://cmake.org/cmake/help/v3.0/variable/CMAKE_INSTALL_PREFIX.html

**Comment by hwaterfall** [comment]
>I'm not sure I understand the problem. What were you expecting to see after
>`cmake --build . --target INSTALL`, and how does that differ from what you
>see?

According to the comments I pasted from docs\INSTALL_MAKE, adding **DCMAKE_INSTALL_PREFIX="chosen\prefix"** will cause libssh2 to be installed into **chosen\prefix** when **cmake --build . --target INSTALL** is run, but that's not what I observed.

I ran:
cmake -DCMAKE_INSTALL_PREFIX="myssh2\install\location" -DZLIB_LIBRARY="my\zlib\lib\location" -DZLIB_INCLUDE_DIR="my\zlib\include\location" -DENABLE_ZLIB_COMPRESSION=ON -DCRYPTO_BACKEND=OpenSSL -DOPENSSL_ROOT_DIR="my\openssl\root"

After building and testing I ran:
cmake --build . --target INSTALL

I expect to have libssh2 installed into **my\zlib\lib\location** however, I found that it was empty. When I couldn't find CMAKE_INSTALL_PREFIX defined anywhere, I figured that was the problem.

I tried it again tonight though while writing this posted and it worked as expected **blush**. Sorry for the false alarm.

Thanks for the pointer to the cmake documentation!
