### ISSUE TITLE
Mingw WinCNG build fails during `libssh2.la` load with multiple definitions of `_libssh2_wincng`

### ISSUE THREAD

**Issue by BrianInglis** [libssh2/libssh2#600]
**Describe the bug**
Cygwin cross-build of libssh2 with mingw 32/64 bit cross compilers and `--with-crypto=wincng` configured fail during `libssh2.la` cross-load with multiple definitions of _libssh2_wincng: see [libssh2-wincng-mingw-cygwin-cross-build-fail.log](https://github.com/libssh2/libssh2/files/6490135/libssh2-wincng-mingw-cygwin-cross-build-fail.log)
Build works with --with-crypto=openssl configured using Cygwin cross-mingw. 

**To Reproduce**
`$ cygport mingw64-x86_64-libssh2.cygport download all`
using: 
[mingw64-x86_64-libssh2.cygport](https://github.com/libssh2/libssh2/files/6490165/mingw64-x86_64-libssh2.cygport.txt)
which requires:
[cygwin-configure-ac.patch](https://github.com/libssh2/libssh2/files/6490149/cygwin-configure-ac.patch.txt)

**Expected behavior**
Cygwin cross-build of libssh2 with mingw 32/64 bit cross compilers and `--with-crypto=wincng` configured should succeed as does the same build  `--with-crypto=openssl` configured.

**Version (please complete the following information):**
 - OS: Cygwin 3.2/Win10 2020H2
 - libssh2 version 1.9.0

**Additional context**
Fedora also cross builds mingw 32/64 [libssh2](https://src.fedoraproject.org/rpms/mingw-libssh2/blob/rawhide/f/mingw-libssh2.spec) but using only openssl.

**Comment by mback2k** [comment]
Habe you tried current master? My 4 buildbots cross-building Libssh2 with MinGW all work fine using WinCNG backend.

**Comment by BrianInglis** [comment]
No, I have not tried building from git, as we try to maintain synced Cygwin & Mingw releases with "official" upstream versions. 
Thanks for the suggestion - I will try repo and snapshot sources to see if they work - and if there could be any issues with 1.9.1. 
I tried snapshots for main Cygwin release, just to check if there might be any Cygwin/32/64 bit build issues when 1.9.1 is released, if that was soon enough to skip releasing 1.9.0, and to avoid adding the last CVE patch from Fedora locally, included in the snapshots. 
[As Cygwin volunteer project leads and some package maintainers work for RedHat and use Fedora, also may work as Fedora package maintainers, and Fedora supports cross-building Cygwin and Mingw, so some package maintainers are also Fedora users, so many packages use Fedora patches, prior to them being pulled upstream. Some of us also check for and use more recent patches from OpenSuSE and Debian.]

**Comment by willco007** [comment]
If you could test master that'd be great; we're down to this and one other blocking issue for release and it'd be great to get this cleared up.

**Comment by BrianInglis** [comment]
Cygwin Mingw libssh2 cross-builds of latest snapshot or git repo are successful.

Couple of places where problematic printf formats are used:
Mingw can use either MS or GNU printf formats.
If `HAVE_INTTYPES_H` is defined, can use `PRId64`/`PRIu64`, else use current conditionals.
All format instances should use identical conditionals e.g.
```
#ifdef HAVE_INTTYPES_H
#define LIBSSH2_INT64_T_FORMAT PRId64
#elif defined(__BORLANDC__) || defined(_MSC_VER) || defined(WIN32)
#define LIBSSH2_INT64_T_FORMAT "I64d"
#else
#define LIBSSH2_INT64_T_FORMAT "lld"
#endif
```
```
#ifdef HAVE_INTTYPES_H
#define __FILESIZE PRIu64
#elif defined(__BORLANDC__) || defined(_MSC_VER) || defined(WIN32)
#define __FILESIZE "I64"
#else
#define __FILESIZE "llu"
#endif
```

compile.log:
```
...
  CC       scp.lo
src/libssh2-1.9.0-20210518/src/scp.c: In function ‘scp_send’:
src/libssh2-1.9.0-20210518/src/scp.c:1018:51: warning: format ‘%d’ expects argument of type ‘int’, but argument 5 has type ‘libssh2_int64_t’ {aka ‘long long int’} [-Wformat=]
 1018 |                      LIBSSH2_SCP_RESPONSE_BUFLEN, "C0%o %"
      |                                                   ^~~~~~~~
 1019 |                      LIBSSH2_INT64_T_FORMAT " %s\n", mode,
 1020 |                      size, base);
      |                      ~~~~                          
      |                      |
      |                      libssh2_int64_t {aka long long int}
In file included from src/libssh2-1.9.0-20210518/src/scp.c:39:
src/libssh2-1.9.0-20210518/src/libssh2_priv.h:1126:36: note: format string is defined here
 1126 | #define LIBSSH2_INT64_T_FORMAT "I64d"
...
CC       sftpdir.o
src/libssh2-1.9.0-20210518/example/sftpdir.c: In function ‘main’:
src/libssh2-1.9.0-20210518/example/sftpdir.c:275:28: warning: unknown conversion type character ‘I’ in format [-Wformat=]
  275 |                     printf("%8" __FILESIZE " ", attrs.filesize);
      |                            ^~~~
src/libssh2-1.9.0-20210518/example/sftpdir.c:40:21: note: format string is defined here
   40 | #define __FILESIZE "I64"
      |                     ^
src/libssh2-1.9.0-20210518/example/sftpdir.c:275:28: warning: too many arguments for format [-Wformat-extra-args]
  275 |                     printf("%8" __FILESIZE " ", attrs.filesize);
      |                            ^~~~
  CC       sftpdir_nonblock.o
  CC       ssh2_exec.o
  CC       ssh2_agent.o
  CC       ssh2_agent_forwarding.o
  CC       ssh2_echo.o
src/libssh2-1.9.0-20210518/example/sftpdir_nonblock.c: In function ‘main’:
src/libssh2-1.9.0-20210518/example/sftpdir_nonblock.c:216:24: warning: unknown conversion type character ‘I’ in format [-Wformat=]
  216 |                 printf("%8" __FILESIZE " ", attrs.filesize);
      |                        ^~~~
src/libssh2-1.9.0-20210518/example/sftpdir_nonblock.c:40:21: note: format string is defined here
   40 | #define __FILESIZE "I64"
      |                     ^
src/libssh2-1.9.0-20210518/example/sftpdir_nonblock.c:216:24: warning: too many arguments for format [-Wformat-extra-args]
  216 |                 printf("%8" __FILESIZE " ", attrs.filesize);
      |                        ^~~~
...
```

src/libssh2-1.9.0-20210518/src/libssh2_priv.h:
```
...
#ifdef HAVE_INTTYPES_H
#include <inttypes.h>
#endif

...

/* define to output the libssh2_int64_t type in a *printf() */
#if defined(__BORLANDC__) || defined(_MSC_VER) || defined(__MINGW32__)
#define LIBSSH2_INT64_T_FORMAT "I64d"
#else
#define LIBSSH2_INT64_T_FORMAT "lld"
#endif

...
```

src/libssh2-1.9.0-20210518/example/sftpdir.c:
```
...
#ifdef HAVE_INTTYPES_H
# include <inttypes.h>
#endif

#include <sys/types.h>
#include <fcntl.h>
#include <errno.h>
#include <stdio.h>
#include <ctype.h>

#ifdef WIN32
#define __FILESIZE "I64"
#else
#define __FILESIZE "llu"
#endif

...
```

src/libssh2-1.9.0-20210518/example/sftpdir_nonblock.c:
```
...
#ifdef HAVE_INTTYPES_H
# include <inttypes.h>
#endif

#include <sys/types.h>
#include <fcntl.h>
#include <errno.h>
#include <stdio.h>
#include <ctype.h>

#ifdef WIN32
#define __FILESIZE "I64"
#else
#define __FILESIZE "llu"
#endif

...
```

**Comment by BrianInglis** [comment]
Mingw WinCNG builds work with snapshots and git master

**Comment by willco007** [comment]
@BrianInglis If you have time, PRs for these type warnings would be great!
