### ISSUE TITLE
Add ecdsa-sk and ed25519-sk key support (FIDO/U2F)

### ISSUE THREAD

**Issue by ianhattendorf** [libssh2/libssh2#606]
**Describe the bug**
libssh2 does not support the `ecdsa-sk` or `ed25519-sk` key types.

**To Reproduce**
Attempt to connect to a server using one of these key types.

**Expected behavior**
Allow connecting to servers with one of these key types.

**Version (please complete the following information):**
 - OS: all
 - libssh2 version [e.g. 1.8.0]: master

**Additional context**
Support for using FIDO/U2F keys was added to OpenSSH in version 8.2 (https://www.openssh.com/txt/release-8.2, `FIDO/U2F Support`). It would be great to be able to support these key types via libssh2.

**Comment by artoj** [comment]
This is still an issue, please do not close this as stale.

**Comment by willco007** [comment]
This PR adds FIDO support https://github.com/libssh2/libssh2/pull/698 If you'd like to look it over that'd be great.
