### ISSUE TITLE
overlapping memcpy

### ISSUE THREAD

**Issue by fourierules** [libssh2/libssh2#611]
https://github.com/libssh2/libssh2/blob/a88a727c2a1840f979b34f12bcce3d55dcd7ea6e/src/kex.c#L4000
I noticed this the other day when the libasan started kicking out errors when sending in MACs preferences  that were not supported yet. I didn't study the head all that closely but I had to make 2 changes in my version from RHEL libssh2 1.8.0
change the memcpy to a memove and added a continue statement so that the last assignment to s = p+1 is skipped.
I think the continue may not be needed in the recent updates but I could be wrong.

**Comment by willco007** [comment]
I believe a `memmove` should be all that is needed here on main.
