### ISSUE TITLE
Clarify status of hmac-sha2-256 support

### ISSUE THREAD

**Issue by fingolfin** [libssh2/libssh2#62]
According to your website, libssh2 supports `hmac-sha2-256` but this seems only to hold for the current development version, *not* for the latest released version.

One way to fix that would be to update the website. But it would of course be even nicer if there actually *was* a release supporting `hmac-sha2-256`. I had a look at your mailing list archive, and saw that in the past two months, there were at least two discussions on making a release, but both seem to have faded away again with no action.

As it is, libssh2 is one of the few remaining popular SSH2 implementations which does not support `hmac-sha2-256` -- you can see that nicely on the comparision page I made at http://ssh-comparison.quendi.de/comparison.html

More specifically, there are seven implementations not supporting `hmac-sha2-256` of these, three are based on libssh2 (in addition to libssh2 itself), and two are inactive, and one has unknown status.

**Comment by bagder** [comment]
I don't think anyone can object to that. We should make a release, but there's just not very much activity in making that actually happen

**Comment by jdzapata** [comment]
You have my upvote for a release that includes hmac-sha2-256. I really need libssh2 to have it.

**Comment by bagder** [comment]
This is released
