### ISSUE TITLE
Disable strict filename checking libssh2_scp_recv 

### ISSUE THREAD

**Issue by vladlukianov** [libssh2/libssh2#622]
**Describe the bug**
I call libssh2_scp_recv function and get error -28 ( LIBSSH2_ERROR_SCP_PROTOCOL, Failed to recv file ).

**To Reproduce**
For example:
scp rpcmadmin@host:config ./  <--- not work
But:
scp -T rpcmadmin@host:config ./   <--- work
I get a file not named "config", but named xxxx.cfg

According to the documentation scp -T arg - Disable strict filename checking.

**Expected behavior**
When the function is called ( e.x. libssh2_scp_recv ), I am guaranteed to get the file

**Version (please complete the following information):**
 - OS: Oracle linux 8/ Rhel 8/ Centos 8
 - libssh2 version 1.8.0-1.9.0[_DEV]

**Comment by willco007** [comment]
The client app should handle this fuzzy logic matching, not libssh2. `libssh2_scp_recv` is designed to download a specific file at the given path.
