### ISSUE TITLE
Incorrect trace message for ssh key from memory

### ISSUE THREAD

**Issue by volund** [libssh2/libssh2#636]
**Describe the bug**
If an ssh key is created from memory but initialization of the ssh key data fails, an incorrect trace message is printed that says `Unable to initialize private key from file`. However there is no key file involved, it should probably say something like `Unable to initialize private key from memory`.

**To Reproduce**
The problem is visible directly [in the code](https://github.com/libssh2/libssh2/blob/master/src/userauth.c#L690):

    static int
    memory_read_privatekey(LIBSSH2_SESSION * session,
                           const LIBSSH2_HOSTKEY_METHOD ** hostkey_method,
                           void **hostkey_abstract,
                           const unsigned char *method, int method_len,
                           const char *privkeyfiledata, size_t privkeyfiledata_len,
                           const char *passphrase)
    {
        ...
        
        if((*hostkey_method)->
            initPEMFromMemory(session, privkeyfiledata, privkeyfiledata_len,
                              (unsigned char *) passphrase,
                              hostkey_abstract)) {
            return _libssh2_error(session, LIBSSH2_ERROR_FILE,
                                  "Unable to initialize private key from file");
        }
    
        return 0;
    }

Specifically the error message:

                return _libssh2_error(session, LIBSSH2_ERROR_FILE,
                                  "Unable to initialize private key from file");

incorrectly references a file. 

**Expected behavior**

The error message should reference the key being loaded from memory, i.e.:

                return _libssh2_error(session, LIBSSH2_ERROR_FILE,
                                  "Unable to initialize private key from memory");

**Version (please complete the following information):**
 - OS: Seen on ubuntu 20.04, but problem is visible directly in the source code
 - libssh2 version - 1.9.0 and master (see for example: [src/userauth.c#L690](https://github.com/libssh2/libssh2/blob/3f9d505353d687db14d1486530abf9147bf08033/src/userauth.c#L690))

**Comment by willco007** [comment]
Thanks for the report, fixed with 69f3cf0.
