### ISSUE TITLE
Compiling with VS 2015

### ISSUE THREAD

**Issue by VahidN** [libssh2/libssh2#64]
When I want to compile this solution with Visual Studio 2015, it reports this error:

Error	C1189	#error:  Macro definition of snprintf conflicts with Standard Library function declaration	libssh2	c:\program files (x86)\windows kits\10\include\10.0.10150.0\ucrt\stdio.h	1927

Removing this line in `libssh2_config.h` file, fixed the issue:
`#define snprintf _snprintf`

`_MSC_VER` here is 1900.

**Comment by gvanem** [comment]
I had the same problem and did:
```
--- a/win32/libssh2_config.h  2016-01-07 14:41:46
+++ b/win32/libssh2_config.h  2016-01-07 14:35:50
@@ -24,7 +24,9 @@
 #define HAVE_SELECT

 #ifdef _MSC_VER
+#if _MSC_VER < 1900
 #define snprintf _snprintf
+#endif
 #if _MSC_VER < 1500
 #define vsnprintf _vsnprintf
 #endif
```

But I'm not sure this is *the right thing* to do. Is it not possible to use MSVC 2015 without the *Windows-Kit*? If so, there could be a test for e.g.:
```
#if !defined(WINDOWS_KIT_VER)
 #define snprintf _snprintf
#endif
```
but I failed to find any suitable such symbol in my Windows-Kit 10.0.10150.0. Anyone?

**Comment by alamaison** [comment]
This is fixed in git. Please try the latest from there

**Comment by gvanem** [comment]
> This is fixed in git. 

Not AFAICS. Do you see such a change for `libssh2_config.h` [here](https://github.com/libssh2/libssh2/blob/master/win32/libssh2_config.h?#L26-L30):

**Comment by alamaison** [comment]
Sorry, I didn't notice that you were using the old visual studio projects from the repo.  Please use CMake to generate of VS2015 project file.

**Comment by gvanem** [comment]
> Sorry, I didn't notice that you 

Me? I don't use "*visual studio*" at all. I hate it.

**Comment by alamaison** [comment]
I'm closing this as wontfix.  Please use the CMake projects to generate working builds on Windows.
