### ISSUE TITLE
build failure for arm64 iOS simulator on M1 chip macOS

### ISSUE THREAD

**Issue by atom2ueki** [libssh2/libssh2#647]
**Describe the bug**

trying to build for M1 arm64 simulator.
not sure how to switch the cross build sdk to simulator sdk path.

**To Reproduce**
Steps to reproduce the behavior.

```bash
cmake \
    -DIOS_PLATFORM=SIMULATOR \
    -DCMAKE_IOS_DEVELOPER_ROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer \
    -DCMAKE_IOS_SDK_ROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.0.sdk \
    -DCMAKE_INSTALL_PREFIX=/tmp/libssh2-arm-simulator \
    -DCRYPTO_BACKEND=OpenSSL \
    -DOPENSSL_ROOT_DIR=/Users/username/Documents/username/openssl-m1-xcf/simulator \
    -DOPENSSL_CRYPTO_LIBRARY=/Users/username/Documents/username/openssl-m1-xcf/simulator/lib/libcrypto.a \
    -DOPENSSL_SSL_LIBRARY=/Users/username/Documents/username/openssl-m1-xcf/simulator/lib/libssl.a \
    -DOPENSSL_INCLUDE_DIR=/Users/username/Documents/username/openssl-m1-xcf/simulator/include \
cmake --build . --target install
```

A recipe or example code that reproduces the problem? A stack trace from a crash

```bash
Consolidate compiler generated dependencies of target libssh2
[ 22%] Built target libssh2
Consolidate compiler generated dependencies of target example-direct_tcpip
[ 23%] Linking C executable example-direct_tcpip
ld: in /Users/username/Documents/username/openssl-m1-xcf/simulator/lib/libcrypto.a(libcrypto-lib-dsa_lib.o), building for macOS, but linking in object file built for iOS Simulator, for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [example/example-direct_tcpip] Error 1
make[1]: *** [example/CMakeFiles/example-direct_tcpip.dir/all] Error 2
make: *** [all] Error 2
```

**Expected behavior**

**Version (please complete the following information):**
 - OS: MacOS 12.0.1 (21A559) Apple Silicon 
 - libssh2 version: 1.10.0

**Additional context**

**Comment by willco007** [comment]
Honestly, it's easier to create a cross platform framework with the libssh2 source code than it is to try and maintain m1/arm specific dylibs and lipo them together.

**Comment by atom2ueki** [comment]
@willco007 any suggestion on how to do that? base on the error, its more like libssh2 select a wrong platform when build, because previously iOS simulator was x86, but now is arm64 on M1 chip

**Comment by willco007** [comment]
If you remove `-DIOS_PLATFORM=SIMULATOR` what arch does it build?

**Comment by atom2ueki** [comment]
I've forget the arch used if remove `-DIOS_PLATFORM=SIMULATOR`,
there are 2 main issues compile for M1 simulator, one is by default iOS simulator arch selection will be x86, 2nd it will looking for a wrong sdk by default.

I've resolved this by a manual selection last time
```bash
-DIOS_PLATFORM=SIMULATOR \
-DCMAKE_OSX_ARCHITECTURES=arm64 \
-DCMAKE_IOS_DEVELOPER_ROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer \
-DCMAKE_IOS_SDK_ROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk \
```

**Comment by lvandal** [comment]
I've been struggling for months to make this work. I'm not a CMAKE expert by all means so can anyone share an example of a script that worked for them? Thanks!

**Comment by lvandal** [comment]
So I found this project on GitHub and creates a .xcframework that also includes OpenSSL:

https://github.com/DimaRU/Libssh2Prebuild

So far it works on my end and I'm finally able to run libssh2 on the iOS Simulator on my M1 Mac.
