### ISSUE TITLE
The latest version is 1.10.0 why the so name still libssh2.so.1.0.1?

### ISSUE THREAD

**Issue by zuoxiaofeng** [libssh2/libssh2#648]
I just confuse why latest version is 1.10.0 but the so name still libssh2.so.1.0.1, is there are some reason or just forget to upgrade it  when version upgraded?

**Comment by ignita** [comment]
We also found this issue(src/CMakeLists.txt#L424). Could anyone explain whether it's intended as such?

**Comment by mback2k** [comment]
The so name is only bumped for ABI changes.

**Comment by zuoxiaofeng** [comment]
> The so name is only bumped for ABI changes.

Thanks for your explain.
