### ISSUE TITLE
Wrong pointer comparison is used userauth name 

### ISSUE THREAD

**Issue by xalopp** [libssh2/libssh2#653]
This is a follow up to #650 

**Describe the bug**

https://github.com/libssh2/libssh2/blob/552e20df38d443aa8ceb9c1c0cfa69121a1b2f37/src/userauth.c#L1797
uses `session->userauth_list_data_len` to check the memory boundary, but  `session->userauth_kybd_auth_name_len` must be
used as `s` is containing data that should be copied to `session->userauth_kybd_auth_name`.
Please refer to 
https://github.com/libssh2/libssh2/blob/552e20df38d443aa8ceb9c1c0cfa69121a1b2f37/src/userauth.c#L1837
where the same operation is done for `session->userauth_kybd_auth_instruction`

Depending on size of the list of authentication method received by the SSH server, the name will be copied correctly or not!
`publickey,password,keyboard-interactive` might fail, while `keyboard-interactive` would work.

**To Reproduce**

Connect with `example/ssh2` to a SSH Sever that sends userauth name information to the SSH client for Keyboard Interactive authentication method.

**Expected behavior**

`userauth_kybd_auth_name`  must be copied correctly

**Version (please complete the following information):**
 - libssh2 version 1.10.0

**Additional context**
Keyboard Interactive

**Comment by willco007** [comment]
Could you submit a PR with what you'd like to change here cause I'm not sure I'm 100% following.  As an aside, this code section does a bit too much pointer math and has had multiple bounds issues and should be refactored to use the modern API.

**Comment by xalopp** [comment]
@willco007 sure,  please have a look at https://github.com/libssh2/libssh2/pull/654

**Comment by xalopp** [comment]
>  As an aside, this code section does a bit too much pointer math and has had multiple bounds issues and should be refactored to use the modern API.

While browsing the code, I didn't find convenient function (e.g. in misc.c).  Could you point out where the "modern API"  is located?

**Comment by willco007** [comment]
@xalopp Anything that takes a `string_buf` type is the modern API found in misc.c. You assign the data buffer and length from the server to a `string_buf` struct and it takes care of bounds checking and walking the pointer while you read values from the data buffer.
