### ISSUE TITLE
Tag New version (1.10.1) with security patch?

### ISSUE THREAD

**Issue by jeremiahpslewis** [libssh2/libssh2#657]
Hey! Thank you for the library. I was wondering if you had a timeline for / would consider tagging a version 1.10.1 with the patch you released for https://github.com/libssh2/libssh2/issues/649? (For context, I'd love to provide it it in the latest [Yggdrasil](https://github.com/JuliaPackaging/Yggdrasil) binary).

Cheers,
Jeremiah

**Comment by willco007** [comment]
We are currently looking at doing a 1.11 release very soon which will include the fix for #649.

**Comment by mkitti** [comment]
I'm also very interested in seeing a release soon so we can include this before a feature freeze on Feb 15th. Thanks.

**Comment by DilumAluthge** [comment]
Hi @willco007, we were wondering if it would be possible to get a new release of libssh2 within the next week? We'd really like to include the new libssh2 release in Julia 1.8, and the feature freeze for Julia 1.8 will be in mid-February.

**Comment by mkitti** [comment]
> We are currently looking at doing a 1.11 release very soon which will include the fix for #649.

Since are you are planning a 1.11 release, does that mean there will not be a 1.10.1 release?

**Comment by DilumAluthge** [comment]
I think this issue is still open.

**Comment by zeha** [comment]
Whats the status of a new release? Someone elsewhere requested updated libssh2 packages, to allow connecting to current  OpenSSH servers.

**Comment by huanwangUvic** [comment]
Waiting for the new release too..

**Comment by kulkarniamit** [comment]
Are there any plans for 1.11 release before end of 2022?

**Comment by vszakats** [comment]
Closing this in favour of: #790
