### ISSUE TITLE
WinCNG. Access violation at address xxx in module 'libssh2.dll'. Read of address CCCCCCCC

### ISSUE THREAD

**Issue by dimmaq** [libssh2/libssh2#66]
Test address 188.123.192.46:22

https://github.com/libssh2/libssh2/blob/master/src/wincng.c#L1228
call BCryptImportKeyPair() fail

https://github.com/libssh2/libssh2/blob/master/src/hostkey.c#L309
_libssh2_dsa_new() return -1
"dsactx" is dirty == 0xCCCCCCCC

**Comment by mback2k** [comment]
Thanks for your report. To me it looks like the public DSA key of cannot be imported by BCryptImportKeyPair and hostkey_method_ssh_dss_init does not validate the return value of _libssh2_dsa_new/_libssh2_wincng_dsa_new. Can you confirm that the public DSA key is a valid DSA key and should be importable by WinCNG?

**Comment by dimmaq** [comment]
Host key is big.
Host key fingerprint is:
ssh-dss 2048 fb:b0:3d:28:09:d4:1d:32:64:e4:ec:f4:50:63:46:cf
https://msdn.microsoft.com/en-us/library/windows/desktop/aa375472(v=vs.85).aspx
BCRYPT_DSA_KEY_BLOB is used for key lengths from 512 to 1024 bits.

**Comment by mback2k** [comment]
So, the crash is fixed, but the WinCNG backend does not support DSS key length > 1024 bit yet.

**Comment by mback2k** [comment]
It seems like q is 21 bytes long and p (modulus) is 257 bytes long, because they are prefixed with a zero byte. Generator g and public y are both 256 bytes long and would fit the BCRYPT_DSA_KEY_BLOB structure. I will try to add support for BCRYPT_DSA_KEY_BLOB_V2.
