### ISSUE TITLE
Speed up CI pipelines by reusing the docker image libssh2/openssh_server

### ISSUE THREAD

**Issue by xalopp** [libssh2/libssh2#665]
**Describe the issue**
The matrix builds on AppVeyor / GitHub Actions all include the same step to build the docker image  `libssh2/openssh_server` which is used for the E2E-tests.
* https://github.com/libssh2/libssh2/blob/master/.github/workflows/ci.yml#L89
* https://github.com/libssh2/libssh2/blob/master/tests/openssh_fixture.c#L146-L151
* https://ci.appveyor.com/project/libssh2org/libssh2/builds/42248573/job/hletgww75y72imei#L983
This costs at least 16 minutes on AppVeyor :crying_cat_face: 

**To Reproduce**
Anything that trigger the AppVeyor / GitHub Action, like a creating or updating a pull request

**Expected behavior**
- Build  `libssh2/openssh_server` when needed, e.g. when changing the `Dockerfile`
- Push the image to a registry or save it
- Pull or load the  `libssh2/openssh_server` when needed, e.g. executing an  end2ent tests.

One possible solution could be to
1. create a new repository  `libssh2/openssh_server` containing all the the files from https://github.com/libssh2/libssh2/tree/master/tests/openssh_server
2. add a workflow to build the container and push the container a registry (https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry, https://docs.github.com/en/actions/publishing-packages/publishing-docker-images)
3. refactor libssh2 tests and CI pipelines to use the docker image (replace `docker build ...` with `docker pull ...`). Maybe having some ENV

**Version (please complete the following information):**

**Additional context**

Saving time / cpu / disk / energy is good and might save the planet :earth_africa: :deciduous_tree:

**Comment by mback2k** [comment]
We actually tried that, but downloading the image took the same amount of time. At least on GitHub Actions.

**Comment by xalopp** [comment]
@mback2k I see.
Do you mean the work related to #588 ? As far as I can see,  `tests/openssh_fixture.c` used `docker build ...` which might rebuild the image.

**Comment by mback2k** [comment]
One major problem was also the rate limiting enforced by Docker Hub, but I guess we could now just use GHCR instead. I will give that a try this week.

**Comment by mback2k** [comment]
I am thinking about and working on a solution that does not require splitting the Docker image into a separate repository as that would hinder joint development of the Dockerfile as part of the testsuite.
