### ISSUE TITLE
Authentication with two identity files

### ISSUE THREAD

**Issue by georgiy321** [libssh2/libssh2#668]
I know this is not so right place to ask, but I have no choice...
I am using libssh2 and connecting to the server with pem cert file, it works fine.
But now I have a new requirement: I need to authorize with two identity file simultaneously. Two separate private keys.
Server requires from client to provide two different keys for auth.
If I would do this with console shh client, it would look like this: `ssh -i /keys/first.pem -i /keys/second.pem user@host`
Two keys, one user session. Does it even possible with libssh2? And if yes - how to do this?
And if not possible - can you give me any hints where and how I can implement it?

**Comment by willco007** [comment]
There is a libssh2 dev email list for questions like this, found at libssh2.org. As for your question, you'll receive multiple calls to the user auth callback where you can provide multiple pem files.
