### ISSUE TITLE
https://www.libssh2.org/snapshots gives 404

### ISSUE THREAD

**Issue by Zenju** [libssh2/libssh2#670]
Hi,
![404](https://user-images.githubusercontent.com/7656530/152854519-32bcc9c7-2beb-4e20-8242-b05e3088b91d.PNG)

is this a known issue? I'm asking because the alternative of downloading the snapshot on github is missing the "configure" files.

Best, Zenju

**Comment by bagder** [comment]
There are no such snapshots provided anymore. The link has been removed from the site.
