### ISSUE TITLE
Problem with linking OpenSSL-3.0.1 on Windows

### ISSUE THREAD

**Issue by LubinLew** [libssh2/libssh2#680]
## Env
- Windows 10 x64
- Cmake 3.21.4
- Visual Studio 2022 Community
- [OpenSSL-3.0.1](https://github.com/openssl/openssl/releases/tag/openssl-3.0.1) x64 (Compile and install according to the official [guide](https://github.com/openssl/openssl/blob/master/NOTES-WINDOWS.md#native-builds-using-visual-c))
   > ```bash
   > perl Configure VC-WIN64A
   > nmake 
   > nmake install
   > ```
   > ```bash
   > C:\Program Files\OpenSSL\
   >                     │─bin
   >                     │   ├─ libssl-3-x64.dll
   >                     │   └─ libcrypto-3-x64.dll
   >                     ├─include
   >                     │  └─openssl/...
   >                     └─lib
   >                         ├─ libssl.lib
   >                         ├─ libcrypto.lib
   >                         ├─engines-3/ ...
   >                         └─ossl-modules/ ...
   > ```
## Issue

Unable to find OpenSSL ssl (aka ssleay32) DLL, executables may not run

```bash
mkdir build
cd build
mkdir install
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install -DCRYPTO_BACKEND=OpenSSL -DBUILD_SHARED_LIBS=OFF ..

-- Building for: Visual Studio 17 2022
CMake Deprecation Warning at CMakeLists.txt:36 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.17763.
-- The C compiler identification is MSVC 19.30.30706.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found OpenSSL: C:/Program Files/OpenSSL/lib/libcrypto.lib (found version "1.1.1i")
CMake Warning at src/CMakeLists.txt:93 (message):
  Unable to find OpenSSL ssl (aka ssleay32) DLL, executables may not run
```

**Comment by willco007** [comment]
Looks like you may have built OpenSSL without outputting the expected dll the cmake file is looking. If you did build the dlls in an unexpected location you can point cmake to the right dlls using `DOPENSSL_CRYPTO_LIBRARY` and `DOPENSSL_SSL_LIBRARY` directives.

**Comment by LubinLew** [comment]
Hi @willco007

Thanks, these directives work.

```bash
-DOPENSSL_CRYPTO_LIBRARY:FILEPATH="C:\Program Files\OpenSSL\lib\libcrypto.lib" -DOPENSSL_SSL_LIBRARY:FILEPATH="C:\Program Files\OpenSSL\lib\libssl.lib" -DOPENSSL_INCLUDE_DIR="C:\Program Files\OpenSSL\include"
```
