### ISSUE TITLE
RSA keys cannot be used with GitHub when using MbedTLS backend due to lack of SHA-256 support

### ISSUE THREAD

**Issue by staticfloat** [libssh2/libssh2#687]
[GitHub recently made a change](https://github.blog/2021-09-01-improving-git-protocol-security-github/) to stop accepting RSA keys signed by SHA-1 signatures.  LibSSH2, when built against the MbedTLS backing crypto library, does not have support for using SHA-256.  This prevents usage of RSA keys with github now when using MbedTLS.

The [Julia ecosystem](https://github.com/JuliaLang/julia) uses libgit2/libssh2/mbedtls to do all git operations by default, so it would be great if we could simply ship an updated `libssh2` that allowed usage of RSA keys with github again.  Looking at https://github.com/libssh2/libssh2/commit/64a555d6f5aafed504a10e5b756e85c91b1d56ce it appears that the work needed is not large, someone just needs to hook up [the appropriate SHA-256 hashing functions that exist within mbedtls](https://tls.mbed.org/api/sha256_8h.html).

Is this on the roadmap, or do you need volunteers to submit PRs?  This is effecting a number of users in the Julia ecosystem, so I can probably find volunteers to make PRs, but they may not be as experienced in the coding style and conventions here, so I wanted to check with you all before directing Julia users to creating a PR here.

**Comment by willco007** [comment]
To my knowledge there is no active maintainer of the mbedtls backend. Any PRs would be great and I'd be happy to review them. This should be relatively straight forward to get working by porting the openssl backend logic.

**Comment by gbaraldi** [comment]
Hi, I think I'm the chosen volunteer. So basically implement that dispatch on hash lenght logic, but usint the mbedtls functions. Giving a quick look shouldn't be too hard since the mbedtls function is already algorithm agnostic it seems, just need to pass the correct value of the enum to `mbedtls_md` and friends
