### ISSUE TITLE
tests/mansyntax.sh is not portable

### ISSUE THREAD

**Issue by kbulgrien** [libssh2/libssh2#704]
**Describe the bug**
tests/mansyntax.sh contains a portability issue that prevents an error message from displaying.

**To Reproduce**

Use an old shell from an old operating system that libssh2 can compile on:

```
$ sh mansyntax.sh
mansyntax.sh: !: not found
mansyntax.sh: EXIT: bad number
```

From `man sh`:

```
Standards conformance

   sh is conformant with:

   ISO/IEC DIS 9945 - 2:1992, Information technology - Portable
   Operating System Interface (POSIX) - Part 2: Shell and Utilities
   (IEEE Std 1003.2 - 1992);
   AT&T SVID Issue 2;
   X/Open CAE Specification, Commands and Utilities, Issue 4, 1992.
```

**Expected behavior**

```
$ ksh mansyntax.sh
man: ERROR: Illegal option -- -
man: ERROR: Illegal option -- h
man version not suitable, skipping tests
```

-or-

```
$ bash mansyntax.sh
man: ERROR: Illegal option -- -
man: ERROR: Illegal option -- h
man version not suitable, skipping tests
```

**Version (please complete the following information):**

- OS and version:
  SCO Openserver 5.0.7

  $ uname -a
  SCO_SV sddemokb 3.2 5.0.7 i386

 - libssh2 version:
   1.10.0 and 1.10.1_DEV
 - crypto backend:
   OpenSSL 3.0.3

**Additional context**

The use of ! in this context is not portable:

```
if ! man --help | grep -q warnings; then
  echo "man version not suitable, skipping tests"
  exit 0
fi
```

See Also:  [Limitations-of-Builtins !](https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Limitations-of-Builtins.html#Limitations-of-Builtins) which states "The Unix version 7 shell did not support negating the exit status of commands with !, and this feature is still absent from some shells (e.g., Solaris /bin/sh). Other shells, such as FreeBSD /bin/sh or ash, have bugs when using !".

I am not an expert in portability, but, on this platform, I use structures like:

```
if { man --help | grep -q warnings; test ${?} -ne 0; } then
  echo "man version not suitable, skipping tests"
  exit 0
fi
```

A potential patch:

```
--- tests/mansyntax.sh.orig     2015-07-21 09:03:43.000000000 -0500
+++ tests/mansyntax.sh  2022-06-03 12:55:22.000000000 -0500
@@ -13,7 +13,7 @@
 #
 # Only test if suitable man is available
 #
-if ! man --help | grep -q warnings; then
+if { man --help | grep -q warnings; test ${?} -ne 0; } then
   echo "man version not suitable, skipping tests"
   exit 0
 fi
```

A test:

```
$ sh mansyntax.sh
man: ERROR: Illegal option -- -
man: ERROR: Illegal option -- h
man version not suitable, skipping tests
```

**Comment by vszakats** [comment]
@kbulgrien Does #935 fix it for you?
