### ISSUE TITLE
Unable to build libssh2 1.10.0 in AlmaLinux 9 container

### ISSUE THREAD

**Issue by inputvalidation** [libssh2/libssh2#705]
**Describe the bug**
I'm trying to build libssh2 1.10.0 (as downloaded from the site) in an AlmaLinux 9 container and the configure step fails with:

```
./configure: This script requires a shell more modern than all
./configure: the shells that I found on your system.
./configure: Please tell bug-autoconf@gnu.org and
./configure: libssh2-devel@cool.haxx.se about your system, including
./configure: any error possibly output before this message. Then
./configure: install a modern shell, or manually run the script
./configure: under such a shell if you do have one.
The command '/bin/sh -c ./configure' returned a non-zero code: 1
```

**To Reproduce**
I'm using the following Dockerfile:

```
FROM almalinux:9

RUN dnf upgrade --assumeyes
RUN dnf install --assumeyes gcc openssl-devel

COPY software/libssh2-1.10.0.tar.gz /docker/build/

WORKDIR /docker/build
RUN tar xfvz libssh2-1.10.0.tar.gz

WORKDIR /docker/build/libssh2-1.10.0
RUN ./configure
RUN make
RUN make install
```

**Expected behavior**
I expect all steps to succeed successfully.

**Version (please complete the following information):**
- Docker host is on CentOS 7 (64-bit)
- Container image is based on official almalinux:9
- libssh2 version is 1.10.0
- OpenSSL version is 3.0.1 14 Dec 2021 (Library: OpenSSL 3.0.1 14 Dec 2021)

**Additional context**
I have tried building it in an AlmaLinux 9 VM which succeeds without any issues. So I'm certain it's related to the container environment. But as the issue has a quite specific libssh2 error message I figured this would be the best place to report it (instead of in the AlmaLinux community).

**Comment by dfandrich** [comment]
I'm not able to reproduce this when running those commands manually in a plain
aarch64 almalinux:9 container. "/bin/sh --version" there reports

GNU bash, version 5.1.8(1)-release (aarch64-redhat-linux-gnu)

which is definitely a modern shell. What is /bin/sh in your container? Does
config.log provide any more clues as to what is happening?

**Comment by inputvalidation** [comment]
`/bin/sh --version` indicates:

`GNU bash, version 5.1.8(1)-release (x86_64-redhat-linux-gnu)`

I don't see a config.log file being created, should I run `./configure` with additional flags for that? Have also compared `printenv` between a CentOS 7 and the AlmaLinux 9 container but don't see any differences (apart from the SHLVL).

**Comment by inputvalidation** [comment]
It looks similar to https://github.com/actions/virtual-environments/issues/2658. Tried building the same Dockerfile on a recent Ubuntu installation and it works fine. Must be some interworking issue with CentOS 7, the Docker version and autoconf. Will migrate the host to a newer version.
