### ISSUE TITLE
Error during configure (ERROR: No openssl crypto library found!)

### ISSUE THREAD

**Issue by badbeef** [libssh2/libssh2#708]
**Describe the bug**
Seeing the following error during ./configure on Ubuntu 18

configure: ERROR: No openssl crypto library found!

I already have openssl, autoconf, automake and libtool installed.

**To Reproduce**
./configure --with-crypto=openssl

Seeing:
configure: ERROR: No openssl crypto library found!

Specify --with-crypto=$backend and/or the neccessary library search prefix.

Known crypto backends: auto, openssl, libgcrypt, mbedtls, wincng
configure: error: Required dependencies are missing!

**Expected behavior**
Expect ./configure to succeed 

**Version (please complete the following information):**
 - OS and version: Ubuntu 18
 - libssh2 version: 1.10.0 (latest)
 - crypto backend: OpenSSL installed with apt install openssl

**Additional context**
I am new with libssh2. Just want to compile and try out its examples. I am not sure what part of openssl libssh2 is looking for. I see my distribution has /usr/lib/x86_64-linux-gnu/libssl.so.1.1 . I tried adding --with-libssl-prefix=/usr/lib/x86_64-linux-gnu and that didn't work either.

**Comment by dfandrich** [comment]
On Fri, Jun 10, 2022 at 03:16:36PM -0700, badbeef wrote:
>   • crypto backend: OpenSSL installed with apt install openssl

You need to install the development libraries for openssl if you're compiling
against it, namely libssl-dev. "openssl" just contains some config files and
man pages.

**Comment by willco007** [comment]
closing as a configuration issue, but a bug.
