### ISSUE TITLE
libssh2_sftp_opendir does not return all files if LIBSSH2_ERROR_BUFFER_TOO_SMALL returned

### ISSUE THREAD

**Issue by harmic** [libssh2/libssh2#714]
**Describe the bug**

When reading a directory using libssh2_sftp_readdir_ex, LIBSSH2_ERROR_BUFFER_TOO_SMALL is returned if the buffer is too small to contain a returned directory entry. An application would then allocate a larger buffer and try again, however libssh2 then returns one less file than the directory actually contains.

**To Reproduce**

A simple reproduction can be found here: https://gist.github.com/harmic/459af38e7c0717c22e59a49c88109c08

Example - create a test directory 'tst' with a couple of files in it:

```
mkdir tst
touch tst/12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678
touch tst/foo
```

Run the test program on this directory, the output is:

```
1: .
2: ..
128: 12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678
```
Note, that the file `foo` is not listed.

**Expected behavior**

All directory entries should be returned, even if libssh2_sftp_readdir_ex returns LIBSSH2_ERROR_BUFFER_TOO_SMALL and the application calls again with a larger buffer.

**Version (please complete the following information):**
 - OS and version: Rocky Linux 8
 - libssh2 version: 1.10.0
 - crypto backend: OpenSSL

**Additional context**

Looking at the code, there are a large number of places where a buffer too small condition is detected and it goes to the label `end`.

Then at the label end:

```
end:

            if((--handle->u.dir.names_left) == 0)
                LIBSSH2_FREE(session, handle->u.dir.names_packet);

```
ie. even though there was an error reading this entry, it still decrements the number of names left.

Perhaps the `end` label should be below this statement so that when the function returns with an error, it does not update the `names_left`.

**Comment by doorsdown** [comment]
So if the handle decrement is removed and allows programs the ability to send a new request with a better(hopefully) buffer size then there is a real risk of a never ending loop for programs that do not expect that. That would not be ideal in my opinion .  When the calling program sends a new buffer they are in essence doing a realloc to make the buffer size work for the file in question. This leads me to say, if there is a fix here, that it is not allowing the calling program to call twice with two different buffers but rather to allow the original buffer to resized by the sftp_readdir fuction. To me this makes more sense as the calling program also does not know that the acceptable buffer size is as that information is overwritten when the return code LIBSSH2_ERROR_BUFFER_TOO_SMALL is set.

**Comment by harmic** [comment]
> So if the handle decrement is removed and allows programs the ability to send a new request with a better(hopefully) buffer size then there is a real risk of a never ending loop for programs that do not expect that. 

It would only be an infinite loop if the caller ignored the returned error code, right? The caller has a choice to either provide a bigger buffer or abandon the attempt - if they just keep calling without checking the error code then they have a bug IMHO. They would also be in an infinite loop if anything else went wrong.

> rather to allow the original buffer to resized by the sftp_readdir fuction

There's no guarantee that the pointer being passed as a buffer is at the beginning of a malloc'd area, or even allocated by malloc at all.

It could be a stack allocated array, or allocated from a different allocator altogether (eg. in the case of calling libssh2 via bindings from another language that has it's own allocator).

If sftp_readdir tried to realloc the buffer that would lead to a crash if it wasn't allocated by malloc to start with.
