### ISSUE TITLE
scp_nonblock requests a file from Windows systems

### ISSUE THREAD

**Issue by pohanlSUM** [libssh2/libssh2#716]
**Describe the bug**
I was trying to request a file from a remote host via SCP using example/scp_nonblock.c. When the remote host is a Linux system, it works perfectly. When the remote host is a Windows system, the last error shows "(-28) Unexpected channel close" during opening the SCP channel, and then the program goto shutdown and closes the session.

**To Reproduce**
Simply run the scp_nonblock.c example code. The scppath is set to "C:/Users/Administrator/Desktop/test.xml" (I tried / and \ path separator and both got the same results). To observe the behavior of opening the SCP channel, I print out the error code and message every time when the channel is nullptr.

```
    /* Request a file via SCP */
    fprintf(stderr, "libssh2_scp_recv2()!\n");
    do {
        channel = libssh2_scp_recv2(session, scppath, &fileinfo);

        if (!channel) {
            char* err_msg;
            int err = libssh2_session_last_error(session, &err_msg, NULL, 0);
            fprintf(stderr, "(%d) %s\n", err, err_msg);

            if (libssh2_session_last_errno(session) != LIBSSH2_ERROR_EAGAIN) {
                goto shutdown;
            }
            else {
                fprintf(stderr, "libssh2_scp_recv() spin\n");
                waitsocket(sock, session);
            }
        }
    } while (!channel);
    fprintf(stderr, "libssh2_scp_recv() is done, now receive data!\n");
```
Run the example code, the output is: 
```
scppath: C:/Users/Administrator/Desktop/test.txt
Fingerprint: F3 DA 17 25 2E BC A2 FC 34 A7 1C BE E4 BF 88 E7 77 3D BD A6 

libssh2_scp_recv2()!
(-37) Would block starting up channel
libssh2_scp_recv() spin
(-37) Would block starting up channel
libssh2_scp_recv() spin
(-37) Would block requesting SCP startup
libssh2_scp_recv() spin
(-37) Would block waiting for SCP response
libssh2_scp_recv() spin
(-28) Unexpected channel close
all done
```
After the last received error code (-28) is not (-37) LIBSSH2_ERROR_EAGAIN, the program goto shutdown and closes the session.

**Expected behavior**
Run the same code when the remote host switches to a Linux system, set scpfile as "/root/test.txt". It works perfectly and the file is properly received via SCP. The output is:
```
scppath: /root/test.xml
Fingerprint: 8F 8D D2 3C E3 D4 31 E5 23 B1 D0 C6 8E E8 22 97 68 49 BF 8F 

libssh2_scp_recv2()!
(-37) Would block starting up channel
libssh2_scp_recv() spin
(-37) Would block starting up channel
libssh2_scp_recv() spin
(-37) Would block requesting SCP startup
libssh2_scp_recv() spin
(-37) Would block waiting for SCP response
libssh2_scp_recv() spin
(-37) Would block waiting for SCP response
libssh2_scp_recv() spin
libssh2_scp_recv() is done, now receive data!
Got 7 bytes spin: 1
all done
```

**Version (please complete the following information):**
 - local OS and version: Ubuntu 20.04.4 LTS
 - remote host OS:  Microsoft Windoes Server 2019 Standard
 - libssh2 version: 1.10.0
 - crypto backend: OpenSSL

**Additional context**
Linux SCP command can request a file from remote Windows systems, so I expected libssh2 could work too.
`scp Administrator@192.168.0.1:C:/Users/Administrator/Desktop/test.txt ./test.txt`

**Comment by dfandrich** [comment]
On Thu, Jun 30, 2022 at 10:37:06PM -0700, pohanlSUM wrote:
> I was trying to request a file from a remote host via SCP using example/
> scp_nonblock.c. When the remote host is a Linux system, it works perfectly.
> When the remote host is a Windows system, the last error shows "(-28)
> Unexpected channel close" during opening the SCP channel, and then the program
> goto shutdown and closes the session.

Does your Windows ssh daemon even support scp? The protocol itself expects a
POSIX shell at the other end and starts commands on the remote machine to handle
the file transfer. This could be emulated by a Windows ssh daemon, but given
that there's been a better protocol (sftp) available for 25 years, and the most
popular scp implementation (OpenSSH) calls the protocol "outdated, inflexible,
and not really effective", maybe not. In fact, the most recent OpenSSH release
of scp no longer even uses scp—it emulates it using sftp. So, the fact that the
command works to get a Windows file when run on Linux doesn't actually prove
that the server supports scp (depending on the version you used to try).

**Comment by pohanlSUM** [comment]
> On Thu, Jun 30, 2022 at 10:37:06PM -0700, pohanlSUM wrote: I was trying to request a file from a remote host via SCP using example/ scp_nonblock.c. When the remote host is a Linux system, it works perfectly. When the remote host is a Windows system, the last error shows "(-28) Unexpected channel close" during opening the SCP channel, and then the program goto shutdown and closes the session.
> Does your Windows ssh daemon even support scp? The protocol itself expects a POSIX shell at the other end and starts commands on the remote machine to handle the file transfer. This could be emulated by a Windows ssh daemon, but given that there's been a better protocol (sftp) available for 25 years, and the most popular scp implementation (OpenSSH) calls the protocol "outdated, inflexible, and not really effective", maybe not. In fact, the most recent OpenSSH release of scp no longer even uses scp—it emulates it using sftp. So, the fact that the command works to get a Windows file when run on Linux doesn't actually prove that the server supports scp (depending on the version you used to try).

Thank you for the information.
sftp can work perfectly to get files from both Linux and Windows systems.
