### ISSUE TITLE
Can't build in arbitrary directory

### ISSUE THREAD

**Issue by xanadu-lee** [libssh2/libssh2#719]
**Describe the bug**
When I try to build libssh2 without the project directory, I get the error.

**To Reproduce**
Step 1. Switch to another directory
Step 2. Run ***/buildconf

**Expected behavior**
The file can be copied to the current directory normally and the build is successful.

**Version (please complete the following information):**
 - OS and version：linux
 - libssh2 version: 1.10.0
 - crypto backend: OpenSSL

**Additional context**
```
xanadu@X-ARM:~/svn/cxx/library/build/arm-linux/libssh2$ ../../../common/libssh2-libssh2-1.10.0/buildconf 
***
*** Do not use buildconf. Instead, just use: autoreconf -fi
*** Doing it for you now, but buildconf may disapear in the future.
***
autoreconf: 'configure.ac' or 'configure.in' is required
xanadu@X-ARM:~/svn/cxx/library/build/arm-linux/libssh2$ 
xanadu@X-ARM:~/svn/cxx/library/build/arm-linux/libssh2$ 
xanadu@X-ARM:~/svn/cxx/library/build/arm-linux/libssh2$ 
xanadu@X-ARM:~/svn/cxx/library/build/arm-linux/libssh2$ ls
xanadu@X-ARM:~/svn/cxx/library/build/arm-linux/libssh2$ ../../../common/libssh2-libssh2-1.10.0/configure --host=${ARCH} --prefix=${CXX_PREFIX}
bash: ../../../common/libssh2-libssh2-1.10.0/configure: 没有那个文件或目录
```

**Comment by vszakats** [comment]
`buildconf` is deprecated, and its a simple wrapper now calling `autoreconf -fi`. This tool requires to be run in the directory it's meant to process.
