### ISSUE TITLE
Windows: inconsistency of DLL names with cmake and autotools

### ISSUE THREAD

**Issue by vtorri** [libssh2/libssh2#723]
the autotools build libssh2-1.dll (1 being the major version). cmake builds libssh2.dll

is it possible to add this major version in the name when cmake and mingw are used ?

something like:
```cmake
if (MINGW)
  set_target_properties(libssh2 PROPERTIES SUFFIX -${LIBSSH2_VERSION_MAJOR}.dll)
endif()
```
also maybe something similar on UNIX.

**Comment by vszakats** [comment]
@vtorri: Have you tried the built-in CMake option `-DCMAKE_SHARED_LIBRARY_SUFFIX_C=-1.dll`. It will result in a `libssh2-1.dll`. It also works on UNIX.

**Comment by vszakats** [comment]
@vtorri: Did `-DCMAKE_SHARED_LIBRARY_SUFFIX_C=-1.dll` resolve the problem?

**Comment by vtorri** [comment]
$ cmake -DBUILD_SHARED_LIBS=ON -DBUILD_EXAMPLES=OFF  -DBUILD_TESTING=OFF -DCMAKE_SHARED_LIBRARY_SUFFIX_C=-1.dll -G "Unix Makefiles"

[100%] Linking C shared library libssh2-1.dll

so seems ok

note that there are plenty of warnings like 

 warning: conversion from 'size_t' {aka 'long long unsigned int'} to 'unsigned int' may change value [-Wconversion]

if you want i can paste the compiler output in another issue

**Comment by vszakats** [comment]
On Windows I find it's not universally desired or expected to append a SOVERSION to the DLL filename. I wouldn't make it the default. Setting this custom option is safe, even on the long run.
