### ISSUE TITLE
Windows and cmake: wrong import library name

### ISSUE THREAD

**Issue by vtorri** [libssh2/libssh2#724]
When compiling libssh2 on Windows, using cmake, the import lib is named liblibssh2.dll.a. It should be libssh2.dll.a

no idea how to fix this, I don't know enough cmake to provide a PR

**Comment by vszakats** [comment]
Can't see this happening by default with `-DBUILD_SHARED_LIBS=ON`. The implib is named `libssh2.dll.a`:
```
[...]
[ 36%] Linking C shared library libssh2.dll
cd ~/libssh2/bld/src && /usr/local/Cellar/cmake/3.25.2/bin/cmake -E cmake_link_script CMakeFiles/libssh2.dir/link.txt --verbose=1
/usr/local/Cellar/cmake/3.25.2/bin/cmake -E rm -f CMakeFiles/libssh2.dir/objects.a
/usr/local/opt/llvm/bin/llvm-ar qc CMakeFiles/libssh2.dir/objects.a @CMakeFiles/libssh2.dir/objects1
/usr/local/opt/llvm/bin/clang --target=x86_64-w64-mingw32 --sysroot=/usr/local/opt/mingw-w64/toolchain-x86_64 
-Wno-unused-command-line-argument -D_UCRT -fuse-ld=lld -Wl,-s -static-libgcc -lucrt -Wall -O3 -DNDEBUG 
-shared -o libssh2.dll -Wl,--out-implib,libssh2.dll.a 
-Wl,--major-image-version,1,--minor-image-version,0 
-Wl,--whole-archive CMakeFiles/libssh2.dir/objects.a -Wl,--no-whole-archive @CMakeFiles/libssh2.dir/linkLibs.rsp
[ 36%] Built target libssh2
[...]
```

What is your CMake config?

**Comment by Skywalker13** [comment]
Version 1.10.0

```
mkdir build
      && cd build
      && cmake -G "Unix Makefiles"
               -DCRYPTO_BACKEND=OpenSSL
               -DLINT=OFF
               -DBUILD_TESTING=OFF
               -DBUILD_EXAMPLES=OFF
               -DBUILD_SHARED_LIBS=ON
               -DENABLE_ZLIB_COMPRESSION=ON
               -DCMAKE_PREFIX_PATH=<SPECIAL_ROOT_DIR>/usr
               -DCMAKE_INSTALL_PREFIX=<SPECIAL_PREFIX_DIR>
               -DCMAKE_BUILD_TYPE=Release ..
```

And after `make install`, I use this hack:

```
mv "<SPECIAL_PREFIX_DIR>/lib/liblibssh2.dll.a" "<SPECIAL_PREFIX_DIR>/lib/libssh2.dll.a"
```

Where `<SPECIAL_ROOT_DIR>` and `<SPECIAL_PREFIX_DIR>` are specific to my toolchain.

**Comment by Skywalker13** [comment]
Both (Unix and MSYS) works fine in my toolchain. The problem stays the same.

```
[100%] Linking C shared library libssh2.dll
cd /D/xcraft/tmp/build/cache/data/libssh2-1.10.0/build/src && /D/windev/sysroot/xcraft/usr/bin/cmake.exe -E rm -f CMakeFiles/libssh2.dir/objects.a
cd /D/xcraft/tmp/build/cache/data/libssh2-1.10.0/build/src && /D/windev/sysroot/opt/msys64/mingw64/bin/ar.exe cr CMakeFiles/libssh2.dir/objects.a @CMakeFiles/libssh2.dir/objects1.rsp
cd /D/xcraft/tmp/build/cache/data/libssh2-1.10.0/build/src && /D/windev/sysroot/xcraft/var/devroot/mswindows-amd64/usr/local/bin/gcc.exe -O2 -g0 -fPIC -fdiagnostics-color -Wall -O3 -DNDEBUG -static-libgcc -static-libstdc++ -lws2_32 -shared -o libssh2.dll -Wl,--out-implib,liblibssh2.dll.a -Wl,--major-image-version,1,--minor-image-version,0 -Wl,--whole-archive CMakeFiles/libssh2.dir/objects.a -Wl,--no-whole-archive @CMakeFiles/libssh2.dir/linklibs.rsp
```

**Comment by vszakats** [comment]
When cross-compiling from Unix to Windows, what worked for me is dropping `-G` altogether, and adding `-DCMAKE_SYSTEM_NAME=Windows`. The gist of this config, for gcc:
```
cmake
  -DCMAKE_SYSTEM_NAME=Windows
  -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc
  -DBUILD_SHARED_LIBS=ON
  [...]
```

Does that help?

[ On native Windows builds `-G "MSYS Makefiles" used to be required, though it's been a while I tested that. ]

**Comment by vtorri** [comment]
> [ On native Windows builds `-G "MSYS Makefiles" used to be required, though it's been a while I tested that. ]

"MSYS Makefiles" does not provide native Windows builds, it provides binaries for the `msys` environment, that it, when you want to build tools/libs for msys2 itself

**Comment by vszakats** [comment]
@vtorri: Did you try it?

**Comment by vtorri** [comment]
@vszakats honestly, I hate cmake, really, so I prefer a small `mv` instead of loosing my time finding a possible solution.

add in github CI a build with cmake after the autotools one and see what is built

**Comment by Skywalker13** [comment]
> It'd be nice if you tried. If it's resolved, or don't want to pursue, I suggest closing this.

I tried with "MSYS Makefiles" too and the problem is exactly the same.

**Comment by vszakats** [comment]
@Skywalker13 Thanks for your tests and sorting that out.

Did you test the latest stable or latest master? The latter contains this fix ef292424bb5d136f888a2d2e92460de12c143ab4, which suspiciously looks like the solution to this issue. Can you give it a test?

**Comment by Skywalker13** [comment]
I tested the latest stable, I can test with master tomorrow.

**Comment by vszakats** [comment]
Possibly fixed by: #711

**Comment by Skywalker13** [comment]
It works as expected `-Wl,--out-implib,libssh2.dll.a`, you can close this issue.

Thanks

**Comment by vtorri** [comment]
thank you
