### ISSUE TITLE
add meson build system

### ISSUE THREAD

**Issue by vtorri** [libssh2/libssh2#725]
everything is in the title. Advantages : 
 * simpler syntax than cmake
 * a bit faster than cmake
 * it just works, no hacks like one can find in cmake
 * cross-compilation is easier to set up
 * options are clearly available in a separate file, no need to find them in all the CMakeLists.txt or in cmake/
 * you can you wrap feature to get dependencies like glig2 or gstreamer projects are doing

**Comment by ilsme** [comment]
#732

**Comment by vszakats** [comment]
After discussing it in #732, closing this as not planned.
