### ISSUE TITLE
ssh-rsa Key Upgrade Process doesn't happen when FIPS is on

### ISSUE THREAD

**Issue by jmuehlner** [libssh2/libssh2#744]
**Describe the bug**
The RSA key upgrade process (as implemented in https://github.com/libssh2/libssh2/commit/64a555d6f5aafed504a10e5b756e85c91b1d56ce), works correctly when FIPS mode is OFF, but does not occur at all when FIPS mode is ON.

**To Reproduce**
I'm using libssh2 1.10.0 (with https://github.com/libssh2/libssh2/commit/64a555d6f5aafed504a10e5b756e85c91b1d56ce cherry-picked on top) with [Apache Guacamole](https://github.com/apache/guacamole-server), on a RHEL 8 machine.

I create an SSH connection using [public key auth](https://github.com/apache/guacamole-server/blob/4d211e0c9e908e510f30f7206aaa27086b48f2ff/src/common-ssh/ssh.c#L318).

A connection to a target machine that does not support the ssh-rsa key type will be automatically upgraded as expected when FIPS mode is off:
```
sshd[2068]: debug2: userauth_pubkey: valid user ec2-user querying public key rsa-sha2-256 AAAAB3NzaC1yc2EAAAADAQABAAABgQCtZm6u2E7BtYEyvlaK72sZNsMfBfjMtnlzdmTcfYRDnQsy1Mvlyu5oLMNRVrelt0mA9ijUle1FY10x+zX/3W93Eo4lWNpOfsqrwdAG+78lSLTQkVwDCfja7ZZNuWAPa5v3akE5B2NNPlg7/DvlL4YH8IF0ES6ilLr2xk26dlD/Ebt8VFy6efvrmpIXkgUHgmnB27q5X2eaFSXeYNZpNHARFwkmdHJCkdNa8yzaPGfhMcylK6hRQk1/fs9KI/Oqn1t0IZ3trdizsxmAwaldsYkMH+mkhwyilMZCYZaBBzLJCtzw5wG2GOeWt7o/RPu6/qRsjYJ59xnU0JsctVKuz5uRmk7Vy+wCAVpp/r4DlD0vlXc0KHrNQxvMvuMXVCJWVVMRRWHN/R
sshd[2068]: debug1: userauth_pubkey: test pkalg rsa-sha2-256 pkblob RSA SHA256:qUtZq9AuwoA1jSJxoGgHdAutAXX37mwAG8Hd8VP0qAk [preauth]
```

However, when FIPS mode is ON, the key is NOT upgraded:

```
sshd[1859]: debug2: userauth_pubkey: valid user ec2-user querying public key ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCtZm6u2E7BtYEyvlaK72sZNsMfBfjMtnlzdmTcfYRDnQsy1Mvlyu5oLMNRVrelt0mA9ijUle1FY10x+zX/3W93Eo4lWNpOfsqrwdAG+78lSLTQkVwDCfja7ZZNuWAPa5v3akE5B2NNPlg7/DvlL4YH8IF0ES6ilLr2xk26dlD/Ebt8VFy6efvrmpIXkgUHgmnB27q5X2eaFSXeYNZpNHARFwkmdHJCkdNa8yzaPGfhMcylK6hRQk1/fs9KI/Oqn1t0IZ3trdizsxmAwaldsYkMH+mkhwyilMZCYZaBBzLJCtzw5wG2GOeWt7o/RPu6/qRsjYJ59xnU0JsctVKuz5uRmk7Vy+wCAVpp/r4DlD0vlXc0KHrNQxvMvuMXVCJWVVMRRWHN/RLaF5s
sshd[1859]: userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedKeyTypes [preauth]
```

**Expected behavior**
I would expect that libssh2 would automatically upgrade the key no matter whether FIPS is enabled or not. 

I should add that the RHEL-provided `ssh` CLI works as expected, and upgrades the key in both cases.

**Version (please complete the following information):**
 - OS and version: RHEL 8
 - libssh2 version: 1.10.0 (with https://github.com/libssh2/libssh2/commit/64a555d6f5aafed504a10e5b756e85c91b1d56ce cherry-picked on top) 
 - crypto backend: OpenSSL 1:1.1.1k-7.el8_6

**Additional context**
I have found that `session->server_sign_algorithms` is NULL at https://github.com/libssh2/libssh2/blob/09f0ffd9fbd0fa1442b8fcb097df49eea3164db9/src/userauth.c#L1207 

I have further found that this line is never reached, because the `SSH_MSG_EXT_INFO` message type is never handled. https://github.com/libssh2/libssh2/blob/2a2aaed3b6c3c1dc25e35e11afcfb23f88a18510/src/packet.c#L666

I have not dug any further.

**Comment by willco007** [comment]
I can't think of a reason why this would be disabled in fips mode in libssh2. Please verify `ext-info-c` is being sent in the key exchange list. If it's being send, the server isn't responding with the `SSH_MSG_EXT_INFO` packet as expected.

**Comment by jmuehlner** [comment]
@willco007 Good call, I think that's my problem. I'll verify and close the ticket if so.

**Comment by jmuehlner** [comment]
Ok, verified that this was user error on my part. I was ommitting "ext-info-c" from my preferred KEX algorithms. Adding it fixed the problem.
