### ISSUE TITLE
use libssh2_userauth_password failed 

### ISSUE THREAD

**Issue by lv-cpp** [libssh2/libssh2#748]
![image](https://user-images.githubusercontent.com/28625121/191648852-119ba1c6-fe01-4885-add4-6869ec6b5a81.png)

![image](https://user-images.githubusercontent.com/28625121/191648085-d2314a01-967f-4a82-a024-e28137600d1f.png)

when i use ssh -v: 
      > $ ssh -v 121.40.68.114 -p 60022 -l wanghui
      OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017
      debug1: Reading configuration data /etc/ssh/ssh_config
      debug1: /etc/ssh/ssh_config line 58: Applying options for *
      debug1: Connecting to 121.40.68.114 [121.40.68.114] port 60022.
      debug1: Connection established.
      debug1: permanently_set_uid: 0/0
      debug1: identity file /root/.ssh/id_rsa type 1
      debug1: key_load_public: No such file or directory
      debug1: identity file /root/.ssh/id_rsa-cert type -1
      debug1: key_load_public: No such file or directory
      debug1: identity file /root/.ssh/id_dsa type -1
      debug1: key_load_public: No such file or directory
      debug1: identity file /root/.ssh/id_dsa-cert type -1
      debug1: key_load_public: No such file or directory
      debug1: identity file /root/.ssh/id_ecdsa type -1
      debug1: key_load_public: No such file or directory
      debug1: identity file /root/.ssh/id_ecdsa-cert type -1
      debug1: key_load_public: No such file or directory
      debug1: identity file /root/.ssh/id_ed25519 type -1
      debug1: key_load_public: No such file or directory
      debug1: identity file /root/.ssh/id_ed25519-cert type -1
      debug1: Enabling compatibility mode for protocol 2.0
      debug1: Local version string SSH-2.0-OpenSSH_7.4
      debug1: Remote protocol version 2.0, remote software version SSHD_0.7.6
      debug1: no match: SSHD_0.7.6
      debug1: Authenticating to 121.40.68.114:60022 as 'wanghui'
      debug1: SSH2_MSG_KEXINIT sent
      debug1: SSH2_MSG_KEXINIT received
      debug1: kex: algorithm: ecdh-sha2-nistp256
      debug1: kex: host key algorithm: ssh-rsa
      debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha2-256 compression: none
      debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha2-256 compression: none
      debug1: kex: ecdh-sha2-nistp256 need=32 dh_need=32
      debug1: kex: ecdh-sha2-nistp256 need=32 dh_need=32
      debug1: sending SSH2_MSG_KEX_ECDH_INIT
      debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
      debug1: Server host key: ssh-rsa SHA256:MEvpZXjLSK5ha3ejlIMEZ+CaK4qvU4qgkMdWmgLOc6M
      debug1: Host '[121.40.68.114]:60022' is known and matches the RSA host key.
      debug1: Found key in /root/.ssh/known_hosts:8
      debug1: rekey after 4294967296 blocks
      debug1: SSH2_MSG_NEWKEYS sent
      debug1: expecting SSH2_MSG_NEWKEYS
      debug1: SSH2_MSG_NEWKEYS received
      debug1: rekey after 4294967296 blocks
      debug1: SSH2_MSG_SERVICE_ACCEPT received
      debug1: Authentications that can continue: publickey,password
      debug1: Next authentication method: publickey
      debug1: Offering RSA public key: /root/.ssh/id_rsa
      debug1: Authentications that can continue: publickey,password
      debug1: Trying private key: /root/.ssh/id_dsa
      debug1: Trying private key: /root/.ssh/id_ecdsa
      debug1: Trying private key: /root/.ssh/id_ed25519
      debug1: Next authentication method: password
      wanghui@121.40.68.114's password: 
      Authenticated with partial success.
      debug1: Authentications that can continue: keyboard-interactive
      debug1: Next authentication method: keyboard-interactive
      Two-Step Vertification required
      Please Input Mfa Code (OTP): 

the passwd is successful, next is keyboard。
what should i do?

**Comment by willco007** [comment]
Your server is requesting a OTP code via the keyboard-interactive prompt. You'll need to provide it.

In the future, please request implementation help on the email list, not the bug tracker. Thanks!

**Comment by lv-cpp** [comment]
> Your server is requesting a OTP code via the keyboard-interactive prompt. You'll need to provide it.
> 
> In the future, please request implementation help on the email list, not the bug tracker. Thanks!
sorry，I'm not sure if this is a bug
i know the server need a OTP code。 but the  Authentications methods is: publickey and password 。
When I test using ssh -v ,the password can successful。
Which interface should I call for authentication.
you mean I should use libssh2_userauth_keyboard_interactive ？ i have tried , also failed。

**Comment by willco007** [comment]
In the logs, you can see authentication methods change as you move through the login process (the message: Authentications that can continue:). You need to read that value and respond accordingly.

**Comment by lv-cpp** [comment]
Thank you. You answer me。
I saw the re-authentication change when I use ssh -v ， But, I don't know how to code，Which authentication interface should I call？ There are examples?

**Comment by lv-cpp** [comment]
I tried it based on the SSH-V log  ,some logs like 
Next authentication method: publickey 
,Next authentication method: password
......


First I did public key authentication, I don't have the public key. 
Of course it'll fail and the error is: LIBSSH2_ERROR_FILE                      -16.

Then I did the password authentication ,fail too。the error is:  LIBSSH2_ERROR_AUTHENTICATION_FAILED     -18

this is my code:

![image](https://user-images.githubusercontent.com/28625121/192182006-a7b75956-19d9-4d2a-897f-c119cac49370.png)

And here's what makes me wonder,I didn't provide a public key why can ssh-v  certificate with a public key?

![image](https://user-images.githubusercontent.com/28625121/192182823-dc3980d3-da1c-41e6-a6de-8d6b8fa178d9.png)

**Comment by josusky** [comment]
If I read your log correctly, the one time password is requested as keyboard interactive authentication:
> "debug1: Next authentication method: keyboard-interactive" so when "libssh2_userauth_password" fails, you should call something like:
```
// try keyboard interactive authentication
if (libssh2_userauth_keyboard_interactive_ex(session, username, strlen(username), response_callback) != 0)
{
```

where the "response_callback" is as described in https://www.libssh2.org/libssh2_userauth_keyboard_interactive_ex.html
Implementation of this callback function will need a way how to reach the user that can provide the one time password.

**Comment by lv-cpp** [comment]
> 如果我正确阅读了您的日志，则要求一次性密码作为键盘交互式身份验证：
> 
> > “debug1：下一个身份验证方法：键盘交互”所以当“libssh2_userauth_password”
> 
> 因此，在对“libssh2_userauth_password”的准不成功调用之后，您应该调用如下内容：
> 
> ```
> // try keyboard interactive authentication
> if (libssh2_userauth_keyboard_interactive_ex(session, username, strlen(username), response_callback) != 0)
> {
> ```
> 
> 其中“response_callback”如https://www.libssh2.org/libssh2_userauth_keyboard_interactive_ex.html中所述 。此回调函数的实现将需要一种方法来联系可以提供一次性密码的用户。

















> 如果你的密码要求密码作为我的身份验证，我则阅读身份验证：
> 
> > “debug1验证方法：密码下一个密码_密码”所以当“lib_userauth2_userauthpassword”
> 
> 因此，在对“libssh2_userauth_password”的准不成功调用之后，您应该调用如下内容：
> 
> ```
> // try keyboard interactive authentication
> if (libssh2_userauth_keyboard_interactive_ex(session, username, strlen(username), response_callback) != 0)
> {
> ```
> 
> 其中“responsecallback”如[https://www.libssh2.org/libssh2_userauth_keyboard_interactive_html](https://www.libssh2.org/libssh2_userauth_keyboard_interactive_ex.html)用户中规定。此函数的实现将需要方法来联系可以提供多种密码。



————————————————————————————————————————————————————————
thank you.  I've tried this interface  Still fail  ，not even the callback function fires   and return the "LIBSSH2_ERROR_AUTHENTICATION_FAILED     -18"


![image](https://user-images.githubusercontent.com/28625121/194692151-820fa497-f9f3-4549-85a7-d86ef5dc562e.png)
![image](https://user-images.githubusercontent.com/28625121/194692175-c8e633fe-9d03-4c36-a4a6-741b8d5ce737.png)

I used the same code to test ssh-server configured with opt,it was right。

**Comment by lv-cpp** [comment]
thank you,I have already fixed
