### ISSUE TITLE
Request: Build static libs on windows using nmake

### ISSUE THREAD

**Issue by justnoxx** [libssh2/libssh2#76]
Hello, is that possible to build static libs on windows? I didn't found how to do that. I tried to compile with an option /DENABLE_STATIC, but with no luck.
Could you please add somewhere description of the compilation process under windows?

Thanks.

**Comment by alamaison** [comment]
I assume you are not generating the NMake file with CMake, because static libs are default there.  If you not getting static libs with CMake, maybe you specified `BUILD_SHARED_LIBS=ON` while configuring.  Just pass `-DBUILD_SHARED_LIBS=OFF` when reconfiguring to fix that.

**Comment by justnoxx** [comment]
Thanks, got it, was able to compile static libs.
