### ISSUE TITLE
EVP_CipherUpdate breaks support for private keys encrypted with aes256-cbc

### ISSUE THREAD

**Issue by jakob** [libssh2/libssh2#764]
**Describe the bug**
OpenSSH private keys encrypted with aes256-cbc no longer work

**To Reproduce**
1) Create an ed25519 private key encrypted with aes256-cbc

```zsh
ssh-keygen -t ed25519 -Z aes256-cbc -f id_ed25519_aes256-cbc -N secretpassphrase
```
2) Try to authenticate with that private key:

```c
int status = libssh2_userauth_publickey_fromfile_ex(ssh_session, user, strlen(user), NULL, "id_ed25519_aes256-cbc", "secretpassphrase")
```
libssh2 fails with status = `LIBSSH2_ERROR_FILE` and the following error message:

> Unable to extract public key from private key file: Wrong passphrase or invalid/unrecognized private key file format

**Expected behavior**
I expect libssh2 to try to authenticate with the provided key, but it does not work. When I revert commit 17c9c1fcdf48ea033a307ce77c432f039ead4584 it works again.

Keys encrypted with the aes256-ctr (=default for ssh-keygen) work fine.

**Version (please complete the following information):**
 - OS and version: macOS 12.4
 - libssh2 version: 1.10.1-dev (0ba6e74bec99c67c358f9fdb461c37c368479e06)
 - crypto backend: OpenSSL (openssl-1.1.1q)

**Additional context**
Possibly related to #739?

**Comment by willco007** [comment]
@haydenroche5 looks like https://github.com/libssh2/libssh2/pull/629#discussion_r719861907 is having some fallout given this and #739 both are pointing to that change. Any chance you'd be willing to tweak this and insure it works with wolfSSL while keeping the original `EVP_Cipher` call?

**Comment by jakob** [comment]
If I'm reading the docs correctly, it would seem that `EVP_CipherUpdate` needs to be followed by `EVP_CipherFinal_ex`, but I'm not sure where that should go in the code.

**Comment by willco007** [comment]
Calling `final` means you will no longer call update which doesn't seem like the correct solution here. Looking at the OpenSSL code, both `EVP_Cipher()` and EVP_CipherUpdate()` eventually call into `ctx->cipher->do_cipher()`. The later doing a lot more legwork before calling `do_cipher()`. It seems like there may be a slight incompatibility in how they work.

**Comment by willco007** [comment]
Using `EVP_CipherUpdate()` requires a call to `EVP_CipherFinal()` but the way libssh2 is currently built there is no concept of final function on the `LIBSSH2_CRYPT_METHOD` struct so using the modern API will not work as a drop in replacement.

**Comment by xeno-john** [comment]
I'm sorry if I came here without fully understanding the context. 
It seems that an issue about using ed25519 keys is propagating to a Python module (ssh2-python) that is based on libssh2. https://github.com/ParallelSSH/ssh2-python/issues/178 - here it mentions that the issue might be related to libssh2.

Can someone tell me if it is somehow related to this issue or if a new issue has to be created? As i mentioned earlier, the technical details might be over my knowledge, especially when C code is involved.

**Comment by willco007** [comment]
@xeno-john you're probably looking for the fix in https://github.com/libssh2/libssh2/commit/3fdcff2485a29544e974bf1d73dd5cfd275c6a47

**Comment by xeno-john** [comment]
@willco007  This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

**Comment by willco007** [comment]
@xeno-john That's because I landed it on `master` shortly after I replied to you and deleted the MR branch.
