### ISSUE TITLE
tar.gz file contains incorrect version number in libssh2.h

### ISSUE THREAD

**Issue by grafster** [libssh2/libssh2#771]
**Describe the bug**
Download the tar.gz file of the source code from this url:-

https://github.com/libssh2/libssh2/archive/libssh2-1.10.0.tar.gz

Inside this archive, the include\libssh2.h file contains:-

#define LIBSSH2_VERSION                             "1.9.0_DEV"

**To Reproduce**

**Expected behavior**
I would expect to get version 1.10 of libssh2 from the above url

**Version (please complete the following information):**
N/A

**Comment by doorsdown** [comment]
Confirmed but the tarball coming from the libssh2.org site appears to be correct

**Comment by bagder** [comment]
The *blessed* and *signed* releases are provided on libssh2.org. Any other archives, like the ones generated by GitHub are just a collection of files from the tag.. They are not the official releases.
