### ISSUE TITLE
website issue with `libssh2.org` when serving via HTTPS

### ISSUE THREAD

**Issue by vszakats** [libssh2/libssh2#78]
https://www.libssh2.org/ now has a certificate (which is great!), but the certificate belongs to a mismatched domain: `[subdomain].haxx.se`.

When instructed to be ignored, the content is served for that other domain.

**Comment by bagder** [comment]
Yes, sorry, we're not officially running the site on HTTPS just yet. It should be fixed "really soon now" B)

**Comment by vszakats** [comment]
Thanks Daniel, no problem, just wanted to let you know. It's real nice to have the *.haxx domains secured now.

**Comment by bagder** [comment]
Yeps, and the plan is to get all sites I admin to HTTPS asap. libssh2.org is on this list.

**Comment by bagder** [comment]
Fixed!

**Comment by vszakats** [comment]
Thank you Daniel!
