### ISSUE TITLE
Null pointer dereference in `crypt_encrypt`

### ISSUE THREAD

**Issue by daniel-heater-imprivata** [libssh2/libssh2#783]
**Describe the bug**
`cctx` pointer is NULL and unchecked in `crypt_encrypt`

**To Reproduce**
I am using ASIO and ASIO TCP client. I pass the socket's `native_handle()` which should be the fd when this gets triggered. The handshake seems to succeed.  This code worked prior to switching from standard BSD-style sockets to ASIO.  **I'll debug that portion.  I just wanted to report the unchecked NULL pointer here.**

**A recipe or example code that reproduces the problem? A stack trace from a crash**

<img width="1702" alt="image" src="https://user-images.githubusercontent.com/112510548/209984223-aa02c136-bbc3-4133-9edf-5a50ca8a132c.png">

**Expected behavior**
Check for NULL pointer and throw an error instead of dereferencing the NULL pointer.

**Version (please complete the following information):**
 - OS and version: MacOS
 - libssh2 version: 1.10.0
 - crypto backend: OpenSSL

**Comment by willco007** [comment]
I'd be interested in knowing how you got that far into the connection process with a null cctx.  Any insight into a better place to handle the error being triggered rather than just adding a protective null check would be a better fix.

**Comment by daniel-heater-imprivata** [comment]
Yes. Sorry, its been a while and I can't remember the exact circumstances.

**Comment by vszakats** [comment]
Without more info it will be almost impossible to act on this. Closing with the note that we're happy to hear any more details about this.
