### ISSUE TITLE
How can I build a x86_64 dylib when running under macOS on an M2 processor ?

### ISSUE THREAD

**Issue by duncangroenewald** [libssh2/libssh2#786]
Is there an easy way to configure things such that an x86_64 library will get built ?  The default produces and arm64 library.

Thanks

**Comment by duncangroenewald** [comment]
I am following the instructions in doc INSTALL_CMAKE.md 

mkdir bin
cd bin
cmake ..

At this point I get an error saying could not find OpenSSL and to set the OPENSSL_ROOT_DIR

then I run

cmake -DOPENSSL_ROOT_DIR="/Users/duncangroenewald/Downloads/CrSDK_v1/openssl" ..

at which point the command seems to complete without errors.

But in order to build a shared x86_64 library I used the following:

cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_OSX_ARCHITECTURES=x86_64 -DOPENSSL_ROOT_DIR="/Users/duncangroenewald/Downloads/CrSDK_v1/openssl" ..

and then

cmake  --build .

**Comment by vszakats** [comment]
I don't think there is an easier solution to this than the one you've found above. It's a cross-build, where CMake needs to be told what the desired target is and point to matching dependencies, as you did.
