### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "transport read" }'

### ISSUE THREAD

**Issue by ivan-hz** [libssh2/libssh2#795]
I ran the code with the following error, and found that the device received the command when "$env: RUST_BACKTRACE=1;" was not added. But the code reports an error

**Describe the bug**

C:\rust\shell>cargo run
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "transport read" }', src\main.rs:18:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

C:\rust\shell> $env:RUST_BACKTRACE=1 ; cargo run
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: Session(-8), msg: "Unable to exchange encryption keys" }', src\main.rs:11:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\core\src/panicking.rs:65:14
   2: core::result::unwrap_failed
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\core\src/result.rs:1791:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6\library\core\src/result.rs:1113:23
   4: shell::main
             at .\src\main.rs:11:5
   5: core::ops::function::FnOnce::call_once
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6\library\core\src\ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\shell.exe` (exit code: 101)

**To Reproduce**
use std::net::TcpStream;
use ssh2::Session;
use std::io::prelude::*;

fn main() {
    let tcp = TcpStream::connect("xxxx:22").unwrap();
    let mut sess = Session::new().unwrap();
    sess.set_tcp_stream(tcp);
    sess.handshake().unwrap();
    
    sess.userauth_password("xxxx","xxx").unwrap();

    let mut channel = sess.channel_session().unwrap();
    channel.exec("show ip int brie").unwrap();
    let mut s = String::new();
    channel.read_to_string(&mut s).unwrap();
    println!("{}",s);
    channel.wait_close();
    
}

**Expected behavior**
Please help to see how to solve this problem，I'm a beginner. I'm trying to make an interactive web ssh

**Comment by dfandrich** [comment]
This doesn't look like it has anything to do with libssh2.

**Comment by ivan-hz** [comment]
Sorry, I wrote the wrong place
