### ISSUE TITLE
Unable to complete handshake on Windows 10

### ISSUE THREAD

**Issue by ChrisG0x20** [libssh2/libssh2#799]
**Describe the bug**
I'm unable to complete a call to libssh2_session_handshake() on Windows10. I've tried building with WinCNG and mbedTLS. When I debug it fails trying to exchange keys.

**To Reproduce**
Build on Windows10 with either WinCNG or mbedTLS.
Run an example program.
Attempt to connect to Ubuntu or Synology sshd.

**Expected behavior**
Key exchange completes successfully.

**Version (please complete the following information):**
 - Windows Version 10.0.19044 Build 19044
 - libssh2 version: 1.10.0 master branch commit af1e591
 - crypto backend: MbedTLS 3.3.0 master branch commit e2a9f86 or WinCNG

**Comment by willco007** [comment]
You're going to need to attach a trace log if you'd like help debugging this issue. I'm guessing your server and client aren't agreeing on encryption protocols.

**Comment by ChrisG0x20** [comment]
Willco007 thanks for the quick response. Since I wrote that last night I was debugging a bit more and figured out I was missing the LIBSSH2_DH_GEX_NEW option in my debug build. After reading your response I found the LIBSSH2DEBUG option to enable trace logging. Tracing produced the information I needed to figure out the rest.

It's working now with mbedTLS!
