### ISSUE TITLE
Public and Private Keys stopped working in later versions (CURL)

### ISSUE THREAD

**Issue by fborges22** [libssh2/libssh2#854]
Greetings,

I am having problems with libcurl and curl that I cannot access my SFTP server using my private and public keys. Recently, when libcurl and curl was updated it stopped working. Please note that my login certificates types are:

/home/fborges/Shared/SFTPDEV_PREFERED/nopass/id_rsa.pub: OpenSSH RSA public key
/home/fborges/Shared/SFTPDEV_PREFERED/nopass/id_rsa: PEM RSA private key

I did this
curl --key ~/Shared/SFTPDEV_PREFERED/nopass/id_rsa --pubkey ~/Shared/SFTPDEV_PREFERED/nopass/id_rsa.pub sftp://[alien@server2.borges.tec.br](mailto:alien@server2.borges.tec.br)/home/alien

I expected the following
Sucessfully access to my SFTP Server

curl/libcurl version
[curl -V output]

curl 7.88.1 (x86_64-pc-linux-gnu) libcurl/7.88.1 OpenSSL/3.0.8 zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.10.0 nghttp2/1.52.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd

In the my Oracle Linux 8.5 Client, I noticed that the curl commands works normally. This issue was also reported previously in the curl official repository but I was informed that this is not a curl directly issue and must be in the SSH layer.

**Comment by fborges22** [comment]
I am getting these at my SSH server according to systemctl status sshd

Mar 16 18:48:34 server2 systemd[1]: Starting OpenSSH server daemon...
Mar 16 18:48:34 server2 sshd[2972]: Server listening on 0.0.0.0 port 22.
Mar 16 18:48:34 server2 sshd[2972]: Server listening on :: port 22.
Mar 16 18:48:34 server2 systemd[1]: Started OpenSSH server daemon.
Mar 16 18:48:46 server2 sshd[2978]: userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]
Mar 16 18:48:46 server2 sshd[2978]: Connection closed by authenticating user alien 177.143.134.22 port 54204 [preauth]

**Comment by willco007** [comment]
As I suspected, your rsa key is no longer being accepted by the server. Disabling ssh-rsa by default was made in OpenSSH 8.8, you can read about it by googling.

`userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms`

I'm going to close this as it's a configuration issue, not an issue with libssh2.

**Comment by fborges22** [comment]
When I try to use the curl binary built with LIBSSH (not LIBSSH2) the SFTP works normally. I think there maybe something wrong in LIBSSH2.

curl 7.88.1 (x86_64-suse-linux-gnu) libcurl/7.88.1 OpenSSL/3.0.8 zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh/0.10.4/openssl/zlib nghttp2/1.51.0
Release-Date: 2023-02-20
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd

**Comment by willco007** [comment]
If you build `master` you'll get rsa key upgrading which will fix your issue. The version you're using doesn't support rsa key upgrading which is why the server is blocking the connection and it's not working.

**Comment by fborges22** [comment]
I builded the LIBSSH2 from the master branch along with latest version of OpenSSL and CURL. I noticed that did not worked either. Please take a look of this:

```
[fborges@Athena:bin]$ ./curl -v --key ~/Shared/SFTPDEV_PREFERED/withpass/id_rsa --pubkey ~/Shared/SFTPDEV_PREFERED/withpass/id_rsa.pub sftp://alien@server2.borges.tec.br/home/alien
*   Trying [2603:c021:c001:1f00:a543:d230:9ea9:43e5]:22...
* Connected to server2.borges.tec.br (2603:c021:c001:1f00:a543:d230:9ea9:43e5) port 22 (#0)
* Found host server2.borges.tec.br in /home/fborges/.ssh/known_hosts
* Set "ssh-ed25519" as SSH hostkey type
* SSH MD5 public key: NULL
* SSH SHA256 public key: NULL
* SSH host check: 0, key: AAAAC3NzaC1lZDI1NTE5AAAAIMkOzm/4p+gXPDyzGojBVbV1P7Z/o34xhY+Bg6snBRkt
* SSH authentication methods available: publickey,gssapi-keyex,gssapi-with-mic
* Using SSH public key file '/home/fborges/Shared/SFTPDEV_PREFERED/withpass/id_rsa.pub'
* Using SSH private key file '/home/fborges/Shared/SFTPDEV_PREFERED/withpass/id_rsa'
* SSH public key authentication failed: Callback returned error
* Failure connecting to agent
* Authentication failure
* Closing connection 0
curl: (67) Authentication failure
[fborges@Athena:bin]$ ./curl -V
curl 8.1.0-DEV (x86_64-pc-linux-gnu) libcurl/8.1.0-DEV OpenSSL/3.2.0 zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.10.1_DEV nghttp2/1.52.0 librtmp/2.3
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTPS-proxy IDN IPv6 Largefile libz NTLM NTLM_WB PSL SSL threadsafe TLS-SRP UnixSockets zstd
[fborges@Athena:bin]$ 
```

Also, here is my sshd log from systemctl:

```
Apr 06 17:37:44 server2 systemd[1]: Starting OpenSSH server daemon...
Apr 06 17:37:44 server2 sshd[169401]: Server listening on 0.0.0.0 port 22.
Apr 06 17:37:44 server2 sshd[169401]: Server listening on :: port 22.
Apr 06 17:37:44 server2 systemd[1]: Started OpenSSH server daemon.
Apr 06 17:39:36 server2 sshd[169450]: Accepted publickey for alien from 177.143.134.22 port 53178 ssh2: RSA SHA256:ap02hXg0X/Q+xGOFd1l/nHzv76gEnrHVKf2zP5lvN7w
Apr 06 17:39:36 server2 sshd[169450]: pam_unix(sshd:session): session opened for user alien(uid=1006) by (uid=0)
Apr 06 17:39:37 server2 sshd[169450]: pam_unix(sshd:session): session closed for user alien
Apr 06 17:40:48 server2 sshd[169471]: userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]
Apr 06 17:40:48 server2 sshd[169471]: Connection closed by authenticating user alien 2804:14d:6885:49c4:7345:98e4:862f:88a7 port 57246 [preauth]
Apr 06 19:52:58 server2 sshd[169628]: Connection closed by authenticating user alien 2804:14d:6885:49c4:7345:98e4:862f:88a7 port 48842 [preauth]
```

Please note that I enabled the ssh-rsa in my /etc/ssh/sshd_config file to force the ssh-rsa support.

**Comment by willco007** [comment]
Without a full log from both libssh and libssh2 I can only guess as to why libssh is working and libssh2 isn't. According to this log, your server isn't set up to accept ssh-rsa keys, which is why libssh2 is failing. Are you sure when you auth with libssh you're not using a different key?

**Comment by fborges22** [comment]
Yes, I am sure that I am not using any different key. Also, I have this line set in my /etc/ssh/sshd_config file:

PubkeyAcceptedAlgorithms +ssh-rsa

**Comment by fborges22** [comment]
Here is the difference when I run the curl command (from my system Arch Linux) and from the curl that I built from master branch:

`[fborges@Athena:bin]$ ./curl -v --key ~/Shared/SFTPDEV_PREFERED/nopass/id_rsa --pubkey ~/Shared/SFTPDEV_PREFERED/nopass/id_rsa.pub sftp://alien@server2.borges.tec.br/home/alien
*   Trying [2603:c021:c001:1f00:a543:d230:9ea9:43e5]:22...
* Connected to server2.borges.tec.br (2603:c021:c001:1f00:a543:d230:9ea9:43e5) port 22 (#0)
* Found host server2.borges.tec.br in /home/fborges/.ssh/known_hosts
* Set "ssh-ed25519" as SSH hostkey type
* SSH MD5 public key: NULL
* SSH SHA256 public key: NULL
* SSH host check: 0, key: AAAAC3NzaC1lZDI1NTE5AAAAIMkOzm/4p+gXPDyzGojBVbV1P7Z/o34xhY+Bg6snBRkt
* SSH authentication methods available: publickey,gssapi-keyex,gssapi-with-mic
* Using SSH public key file '/home/fborges/Shared/SFTPDEV_PREFERED/nopass/id_rsa.pub'
* Using SSH private key file '/home/fborges/Shared/SFTPDEV_PREFERED/nopass/id_rsa'
* Initialized SSH public key authentication
* Authentication complete
* Closing connection 0
curl: (79) Error in the SSH layer
[fborges@Athena:bin]$ ./curl -v --key ~/Shared/SFTPDEV_PREFERED/nopass/id_rsa --pubkey ~/Shared/SFTPDEV_PREFERED/nopass/id_rsa.pub sftp://alien@server2.borges.tec.br/home/alien
*   Trying [2603:c021:c001:1f00:a543:d230:9ea9:43e5]:22...
* Connected to server2.borges.tec.br (2603:c021:c001:1f00:a543:d230:9ea9:43e5) port 22 (#0)
* Found host server2.borges.tec.br in /home/fborges/.ssh/known_hosts
* Set "ssh-ed25519" as SSH hostkey type
* SSH MD5 public key: NULL
* SSH SHA256 public key: NULL
* SSH host check: 0, key: AAAAC3NzaC1lZDI1NTE5AAAAIMkOzm/4p+gXPDyzGojBVbV1P7Z/o34xhY+Bg6snBRkt
* SSH authentication methods available: publickey,gssapi-keyex,gssapi-with-mic
* Using SSH public key file '/home/fborges/Shared/SFTPDEV_PREFERED/nopass/id_rsa.pub'
* Using SSH private key file '/home/fborges/Shared/SFTPDEV_PREFERED/nopass/id_rsa'
* Initialized SSH public key authentication
* Authentication complete
* Closing connection 0
curl: (79) Error in the SSH layer
[fborges@Athena:bin]$ 
`

**Comment by willco007** [comment]
This doesn't have enough logging to see the entire handshake from libssh2. I can only see your server is rejecting it with this logged line from above:

`Apr 06 17:40:48 server2 sshd[169471]: userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]`

**Comment by fborges22** [comment]
Here is the log when it fails to logon into my server:

`● sshd.service - OpenSSH server daemon
     Loaded: loaded (/usr/lib/systemd/system/sshd.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2023-04-06 21:02:58 GMT; 7s ago
       Docs: man:sshd(8)
             man:sshd_config(5)
   Main PID: 169948 (sshd)
      Tasks: 1 (limit: 34468)
     Memory: 1.6M
        CPU: 60ms
     CGroup: /system.slice/sshd.service
             └─169948 "sshd: /usr/sbin/sshd -D [listener] 0 of 10-100 startups"

Apr 06 21:02:58 server2 systemd[1]: Starting OpenSSH server daemon...
Apr 06 21:02:58 server2 sshd[169948]: Server listening on 0.0.0.0 port 22.
Apr 06 21:02:58 server2 sshd[169948]: Server listening on :: port 22.
Apr 06 21:02:58 server2 systemd[1]: Started OpenSSH server daemon.
Apr 06 21:03:03 server2 sshd[169954]: Accepted publickey for alien from 2804:14d:6885:49c4:7345:98e4:862f:88a7 port 56368 ssh2: RSA SHA256:ap02hXg0X/Q+xGOFd1l/nHzv76gEnrHVKf2zP5lvN7w
Apr 06 21:03:03 server2 sshd[169954]: pam_unix(sshd:session): session opened for user alien(uid=1006) by (uid=0)
Apr 06 21:03:03 server2 sshd[169954]: pam_unix(sshd:session): session closed for user alien
`

**Comment by willco007** [comment]
As I noted before, the Curl logging doesn't show enough information about the handshake to debug it. Can you enable more verbose logging?

**Comment by willco007** [comment]
This log looks like you log in, do a stat, then try downloading a file and it fails. Auth seems to work just fine.

**Comment by willco007** [comment]
The original issue you reported was that RSA keys didn't work.  It was closed due to a configuration issue, you fixed it, now you're seeing a new download error from curl after successful login. Please feel free to do a more debugging and figure out exactly if libssh2 is failing inside of curl; if it is a libssh2 issue please open a new bug with additional information.
