### ISSUE TITLE
libssh2.dll - What type of dll ?

### ISSUE THREAD

**Issue by RogerCabo** [libssh2/libssh2#882]
Hi everyone, 

id like to use the libssh2.dll inside of a standard win32 application on windows 10.
The libssh2.dll sits in the exe directory. Other dll's can be found in the same folder as well.

When declaring the function:  Function libssh2_init() Lib "libssh2.dll"  As Long 
I got the error: **The libssh2.dll cannot be found to call libssh2_init().**

Does anyone know what happen to? 
Thank you..

**Comment by vszakats** [comment]
Assuming both caller and the DLL were built for the same CPU (e.g. x64) and platform (Windows, and not Cygwin), and the DLL can load all its depencencies, it depends on what compiler (e.g. MSVC or MinGW) was used to build this `libssh2.dll` and with what build options. Automatic DLL interfaces require certain calling convention (e.g. cdecl or stdcall) and naming conventions (e.g. leading underscore or not) to successfully call into them. Caller tools often have options to tweak these to match the DLL.

In practice MSVC-built DLLs used to have a better chance to work out-of-the box in such scenarios.

**Comment by vszakats** [comment]
This project doesn't ship precompiled DLLs, so it's not possible to tell what kind of DLL that may be.
