### ISSUE TITLE
Possible (unconsequential) source bug.

### ISSUE THREAD

**Issue by Markus-Schmidt** [libssh2/libssh2#919]
I'm currently researching ways to implement the "rsa-sha2-256" and "rsa-sha2-512" hostkey mechanism and stumbled upon an issue in the source code.

hostkey.c, line 252ff (libssh2 1.10).

static const LIBSSH2_HOSTKEY_METHOD hostkey_method_ssh_rsa = {
    "ssh-rsa",
    **MD5_DIGEST_LENGTH**,
    hostkey_method_ssh_rsa_init,
    hostkey_method_ssh_rsa_initPEM,
    hostkey_method_ssh_rsa_initPEMFromMemory,
    hostkey_method_ssh_rsa_sig_verify,
    hostkey_method_ssh_rsa_signv,
    NULL,                       /* encrypt */
    hostkey_method_ssh_rsa_dtor,
};

I believe this should be SHA1_DIGEST_LENGTH because hostkey_method_ssh_rsa_sig_verify() creates a SHA1.  

I did check and the hash_len field in the LIBSSH2_HOSTKEY_METHOD struct doesn't appear to be used in critical places but looking at the other hostkey methods, I believe MD5 length is wrong.

It also appears for the "ssh-dss", which I believe also computes a SHA1.

**Comment by vszakats** [comment]
@Markus-Schmidt Nice catch! Also applies to `ssh-rsa-cert-v01@openssh.com` in 1.10.1-DEV.
