### ISSUE TITLE
ENGINE_load_builtin_engines => Unnecessary memory leaks?

### ISSUE THREAD

**Issue by Zenju** [libssh2/libssh2#95]
1. The current OpenSSL-related libssh2 initialization/teardown is very confusing. Reading all kinds of documentation distributed all over the web does not help much. What's missing is official libssh2-specific documentation on how OpenSSL is supposed to be used with libssh2_crypto_init/libssh2_crypto_exit.
   Currently using a default libssh 1.7 installation leads to memory leaks, ignoring these leaks is not acceptable since it renders the leak checker unusable for other purposes while flooding the logs with OpenSSL-related leaks. => A libssh2 user has to change libssh2-sources (libssh2_crypto_init/libssh2_crypto_exit) to fix this which requires knowledge about which OpenSSL tear-down is needed. This libssh2-implementation-specific info is currently not available (and has to inferred/guessed, which is a very brittle solution).
2. New with libssh 1.7 [openssl.h](https://github.com/libssh2/libssh2/blob/master/src/openssl.h) has added two new ENGINE_\* initialization calls:
# define libssh2_crypto_init() \

  OpenSSL_add_all_algorithms(); \
  ENGINE_load_builtin_engines(); \
  ENGINE_register_all_complete()

=> The call "ENGINE_register_all_complete" is redundant, since ENGINE_load_builtin_engines() internally calls ENGINE_register_all_complete. 

=> I think(!) ENGINE_load_builtin_engines() is also redundant. I couldn't find a single "ENGINE" use in libssh2, so why init it?

=> using ENGINE_load_builtin_engines() leads to memory leaks since no corresponding "ENGINE_cleanup()" is available. I understand this is due http://trac.libssh2.org/ticket/298 
but still the very least requirement when adding new initialization calls that create memory leaks if clean-up is misssing should be that this is documented somewhere (or have I just not found the page?) so that a developer can write the cleanup code himself _with confidence_.

**Comment by topilski** [comment]
Good day @Zenju , agree with you, guys from libssh2 please try to fix it!
Now i use next line:
```
#define libssh2_crypto_init() OpenSSL_add_all_algorithms();
#define libssh2_crypto_exit() EVP_cleanup();
```
and connection to ssh server is successful.

**Comment by Zenju** [comment]
Issue is obsolete. libssh2 is working great with the latest OpenSSL 1.1.1
