### ISSUE TITLE
userauth_password can not run into passwd_change_cb

### ISSUE THREAD

**Issue by 1987jy** [libssh2/libssh2#950]
**Describe the bug**
sftp auth func userauth_password can not access passwd_change_cb when openssh server response that you need change pwd

**To Reproduce**
sftp user "test" is pwd expire
Last password change                                    : Apr 09, 2023
Password expires                                        : Apr 09, 2023
Password inactive                                       : never
Account expires                                         : never
Minimum number of days between password change          : 0
Maximum number of days between password change          : 0
Number of days of warning before password expires       : 7

this is ssh response on terminal when i use openssh
ssh test@127.0.0.1
Password: 
You are required to change your password immediately (password aged)
Changing password for test.
(current) UNIX password: 

but when i use libssh2 to connect the same host，the auth result is SSH_MSG_USERAUTH_SUCCESS,not SSH_MSG_USERAUTH_PASSWD_CHANGEREQ.
so it can not run into passwd_change_cb

**Expected behavior**
i hope to debug passwd_change_cb in my app, so i expect he auth result is SSH_MSG_USERAUTH_PASSWD_CHANGEREQ.
what should i do

**Version (please complete the following information):**
 - OS and version: Windows, Linux
 - libssh2 version: 1.10.0
 - crypto backend: OpenSSL

**Comment by 1987jy** [comment]
i found libssh2_userauth_keyboard_interactive can active change password callback, did userauth_password support?

**Comment by willco007** [comment]
The callback called depends on what the auth list response is from the server. When using password auth, OpenSSH actually uses keyboard interactive instead of straight password. I suspect that will be the case with most servers these days.

**Comment by 1987jy** [comment]
what situation that ssh server will return SSH_MSG_USERAUTH_PASSWD_CHANGEREQ when i call userauth_password?

**Comment by willco007** [comment]
Honestly, I haven't used this particular callback and haven't heard of any of our users running in to a case where it was expected. I'm not a lot of help I'm afraid.

**Comment by 1987jy** [comment]
ok. thank you very much for answer my question
