### ISSUE TITLE
linker error with Borland

### ISSUE THREAD

**Issue by davidwed** [libssh2/libssh2#98]
I've got several linker errors by linking the libssh2 with the Embarcadero ( Borland/ bcc32 ) compiler.

The version 1.6.0 works fine.

The makefile was created via cmake - Borland makefiles with "CRYPTO_BACKEND" = OpenSSL.

But it seems that the the crypt32.lib is needed even though I want to use the OpenSSL crypto backend.

[Linker Error] Unresolved external 'CertGetCertificateContextProperty' referenced from C:\PROJECTS\IOPENSSL\OUT32\LIBEAY32.LIB|e_capi
[Linker Error] Unresolved external 'CertOpenStore' referenced from C:\PROJECTS\OPENSSL\OUT32\LIBEAY32.LIB|e_capi
[Linker Error] Unresolved external 'CertFindCertificateInStore' referenced from C:\PROJECTS\OPENSSL\OUT32\LIBEAY32.LIB|e_capi
[Linker Error] Unresolved external 'CertEnumCertificatesInStore' referenced from C:\PROJECTS\OPENSSL\OUT32\LIBEAY32.LIB|e_capi
[Linker Error] Unresolved external 'CertDuplicateCertificateContext' referenced from C:\PROJECTS\OPENSSL\OUT32\LIBEAY32.LIB|e_capi
[Linker Error] Unresolved external 'CertFreeCertificateContext' referenced from C:\PROJECTS\OPENSSL\OUT32\LIBEAY32.LIB|e_capi
[Linker Error] Unresolved external 'CertCloseStore' referenced from C:\PROJECTS\OPENSSL\OUT32\LIBEAY32.LIB|e_capi

**Comment by alamaison** [comment]
This also happens with VS builds.  OpenSSL uses Windows APIs defined in crypt32.lib now.  What I don't understand is why we are only seeing this with libssh2 1.7.0.  Perhaps we only recently started calling an OpenSSL API that had that dependency and the linker doesn't link what it doesn't need so we didn't get an error before.

The obvious quick fix is to always add crypt32.lib to the link libraries when on Windows.  I'll make this change to the CMake files.

**Comment by davidwed** [comment]
Ok. I'll link the crypt32.lib with my project.

**Comment by rhuijben** [comment]
Did you start using a statically compiled OpenSSL? (Or statically linked engines) If you use the DLL version the dependency wouldn't be necessary.

The OpenSSL e_capi.c file is the CAPI engine, which usually links into a separate 'capi.dll' file with a shared library build.

**Comment by alamaison** [comment]
That's true, crypt32.lib is only needed for statically linked OpenSSL. I've used a static OpenSSL for a while and this issue only appeared recently.

**Comment by davidwed** [comment]
I've linked the OpenSSL lib staticaly. Thank you for your quick reply. :-)
