### ISSUE TITLE
Crash at libssh2!channel_send_eof

### ISSUE THREAD

**Issue by manojpattanaik** [libssh2/libssh2#99]
I am developing an application using libssh2 1.4.3 on Windows.
The application works fine on most of the Windows environment but it started crashing on some Windows 2012 Server R2 systems. From the crash dump I found following stack trace.

025dac44 76ee05bf 025dac5c 025dacac 025dac5c ntdll!ZwWow64CallFunction64+0x1fd3
025dafe4 003953a4 00000000 025db000 00000005 ntdll!KiUserExceptionDispatcher+0xf
025db014 00395619 0219e7f8 025db02c 00000000 libssh2!channel_send_eof+0x64 [c:\libssh2-1.4.3\src\channel.c @ 2129]
025db02c 003957dc 0219e7f8 56e6ebdc 00000000 libssh2!_libssh2_channel_close+0x49 [c:\libssh2-1.4.3\src\channel.c @ 2264]
025db048 00aeee35 0219e7f8 716fbc81 01b243d0 libssh2!libssh2_channel_close+0x2c [c:\libssh2-1.4.3\src\channel.c @ 2335]

Any suggestion will be helpful.

~Manoj

**Comment by manojpattanaik** [comment]
Can someone provide an update on this issue? 

~Manoj

**Comment by bagder** [comment]
I suggest you first try with the latest released version to see if the problem persists.

Then I'd suggest you run a debug version of the lib and check out the crash and its local variables etc with a debugger.
